### ISSUE TITLE
nextclade on S gene -  recombinant clade ?

### ISSUE THREAD

**Issue by JeromeAmbroise** [nextstrain/nextclade#1002]
Hello,

When I try to apply nextclade (cli) on the s gene part of the genome, I obtain a lot of results associated 'recombinant' clade identification.
**One example:**
I downloaded the virus OM263444.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/human/USA/0-56447-4/2021, complete genome from ncbi.
I applied nextclade on the full genome and I obtained (as expected) the clade 'BA.1'.
Then I extracted the gene s from the genome and I ran nextclade with the '--genes=S' option.
I obtained the following result for the clade : "recombinant".

I would be interested to know why I obtain this result .. and if there is a solution to obtain the clade 'BA.1' attribution based on the gene S only.

Thank you in advance

Jérôme

**Comment by corneliusroemer** [comment]
Hi Jérôme,

It's a known issue that short sequences can get incorrectly called as recombinants.

The way to work around this is to use the "no-recombinants" dataset: `sars-cov-2-no-recomb` that is identical to the standard dataset but lacks all recombinants.

<img width="1707" alt="image" src="https://user-images.githubusercontent.com/25161793/192366526-cf3dc017-45a7-4d58-9566-a5f5ae2d8ec9.png">

`nextclade run -d sars-cov-2-no-recomb ...`

<img width="918" alt="image" src="https://user-images.githubusercontent.com/25161793/192366611-2c607da6-562f-4542-8857-07c91f6f0ae1.png">

Recombinants with breakpoint outside spike are indistinguishable to the parent that donated the spike when you only have spike present.

The long term solution is for us to bias against assigning recombinants - when a non-recombinant fits just as well.
