### ISSUE TITLE
Parsing tree throws recursion limit error halfway through moderately-sized tree

### ISSUE THREAD

**Issue by sidneymbell** [nextstrain/nextclade#1018]
Tree has ~2k tips, not sure how it's throwing a recursion error. JSON works just fine on auspice.us; happy to slack it over if helpful.

```
(base) sbell@CZIMACOS3553 nextclade % nextclade run --input-dataset ~/bin/nextclade-data/hcv --output-selection csv tree errors --output-basename hcv-nextclade --output-all ./output/ ../data/raw/hcv-genotypes-ictv.fasta
Error: 
   0: When parsing Auspice Tree JSON file "/Users/sbell/bin/nextclade-data/hcv/tree.json"
   1: When parsing Auspice Tree JSON contents
   2: When parsing JSON
   3: recursion limit exceeded at line 539826 column 286

Location:
   packages_rs/nextclade/src/io/json.rs:7
```

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/12618847/194972230-fc2dd13c-43bb-4e5c-afff-b94a66892f1b.png">

**Comment by ivan-aksamentov** [comment]
@sidneymbell Oh no! How strange.

Yes, please drop me on Trevor's Slack all the files required to run the command to reproduce the error. I'll investigate.

**Comment by sidneymbell** [comment]
Sent! Thanks @ivan-aksamentov

**Comment by sidneymbell** [comment]
Ach! Thank you. I've been running SC2 builds for so long where we have the
`keep_polytomies` flag on by default that I forgot I need to add it
explicitly. Let me iterate a bit here.
