### ISSUE TITLE
BUG: Alignment start/end in tsv output seems to be 0-indexed, in contrast to rest of TSV positions

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#1036]
I received this issue via @shay671 who got it from Talya on his team:

I noticed that when downloading the Nextclade results in tsv format the alignment start is a position below what is found in the aligned FASTA files (at the last '-' instead of one position after). Thought at the beginning that the count might start from 0 but the deletion ranges by nucleotide position are compatible with a count that starts from 1 and so is the alignment end position (in the alignment end I did not find a similar problem in the few examples I looked at).
Here are 2 examples for sequences in which I saw this problem: EPI_ISL_10096833, EPI_ISL_10014324

**Comment by shay671** [comment]
@talyashe

**Comment by ivan-aksamentov** [comment]
I attempted to fix that in https://github.com/nextstrain/nextclade/pull/1037

It is currently building. 

After the build is done, could you please check again, either in
 - Nextclade Web preview deployment: the "Preview" link in the message of "Vercel bot"
 - Nextclade CLI: I prepared binaries [here](https://app.circleci.com/pipelines/github/nextstrain/nextclade/3697/workflows/07f018a8-bc6d-4cb2-b078-591f5aae7a88): click to desired OS and architecture, then the "Artifacts" tab
