### ISSUE TITLE
Enable 'lite' version of QC analysis and mutations without a `tree.json` file

### ISSUE THREAD

**Issue by sidneymbell** [nextstrain/nextclade#1041]
For many pathogens, it would be super useful to be able to do at least a 'lite' version of QC analysis and mutation calling with just the reference sequence / i.e., without requiring a `tree.json` file. 

Context being that this would cut the time required to prep a new pathogen-specific reference dataset by probably 75%+ (making the tree also implies having to gather and clean a representative dataset, infer and iterate on `clade_membership` assignments, advanced understanding of how to use augur, etc.)

**Comment by corneliusroemer** [comment]
This may be quite easy to do, either by having a template for a dummy tree with just a single tip=root, or by modifying Nextclade to set up such a dummy tree.

**Comment by corneliusroemer** [comment]
Dummy tree implementation is trivial, I just made one. Here is one anyone can use, needs no modification whatsoever for it to work :)
[tree.json.txt](https://github.com/nextstrain/nextclade/files/9873467/tree.json.txt)

**Comment by sidneymbell** [comment]
Ahhh beautiful, thank you!!

**Comment by ivan-aksamentov** [comment]
Cleaning up old issues.

This is now possible since Nextclade v3 - it does not require a tree to run.
