### ISSUE TITLE
Improve documentation on output files

### ISSUE THREAD

**Issue by MarieLataretu** [nextstrain/nextclade#1052]
Hi there,

I wanted to double-check my understanding of the `missing` column in the documentation, but it does not match what I expect:

<html><body>

missing | List of detected nucleotide insertions
-- | --

</body>
</html>

I'd suggest something like `List of Ns`.

Are these the positions in the alignment? Because they don't match exactly in the unaligned fasta file.

**Comment by ivan-aksamentov** [comment]
Thanks! Should be resolved in #1053 and will be reflected on the docs website after next Nextclade release.

**Comment by ivan-aksamentov** [comment]
> Are these the positions in the alignment? Because they don't match exactly in the unaligned fasta file.

Yes, positions are after alignment and after all insertions are stripped. I clarified this additionally in the docs in [aa87b68df863a9d15fc05235a6b8ff3ed42d8e1b](https://github.com/nextstrain/nextclade/commit/aa87b68df863a9d15fc05235a6b8ff3ed42d8e1b)

**Comment by MarieLataretu** [comment]
Super, thanks for the clarification! 🙂 👍
