### ISSUE TITLE
request to have option to output mutations as nucleotides not aa

### ISSUE THREAD

**Issue by rrdavis77** [nextstrain/nextclade#1054]
Could there be an option to have mutations outputted as nucleotides and not as an amino acid when using the CLI?  Or is there an easy way to convert the nextclade output to do this?

Thanks!

**Comment by corneliusroemer** [comment]
HI @rrdavis77, if I don't misunderstand your use case, you can get a list of nucleotide mutations from the csv/tsv output, see https://docs.nextstrain.org/projects/nextclade/en/stable/user/output-files.html#tabular-csv-tsv-results

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/25161793/204953991-fc1280ae-da9e-4427-a4dd-ee27d2937dd2.png">

This is how you get the tsv/csv:

```
nextclade run  input.fasta -d sars-cov-2 -t path/to/output_tsv
```

**Comment by rrdavis77** [comment]
Hi Cornelius,

Sorry I realized the title of the question was more descriptive than the body.  I am wondering if it's possible to get those mutations listed in a nucleotide format instead of the amino acid format?

Thanks!

**Comment by rrdavis77** [comment]
Let's say the nextclade output has S:V213E ; could we instead see T2200A? the website client will display that info for a few mutations but interested in the CLI and its outputs.

**Comment by corneliusroemer** [comment]
But that's exactly what the `substitution` column of the CLI output is, see above. Exactly that output you want _is_ in the CLI output when run as shown above.

**Comment by rrdavis77** [comment]
Yep, you are correct!  So sorry!  I thought I had seen it before but when I opened it with libreoffice that column had a very small width and I glanced right over it and went to aa subs! facepalm!

**Comment by corneliusroemer** [comment]
I guess it would help if it was called ntSubsitutions to be clear - but well that's where we are, unless it contains `aa` it's nucleotides ;)
