### ISSUE TITLE
Request for RSV A and B nextclade dataset

### ISSUE THREAD

**Issue by laura-bankers** [nextstrain/nextclade#1071]
Hello! Are there any plans for nextclade data to include RSV (A and B)? If so, is there an approximate timeline?

**Comment by corneliusroemer** [comment]
Hi Laura, RSV datasets are work in progress. @rneher will know better what the timeline is.

You can already test a recent alpha version here:
RSV A: https://clades.nextstrain.org/?dataset-url=github:nextstrain/nextclade_data@add-rsv@/data/datasets/rsv_a/references/LR699737/versions/2022-12-18T14:59:42Z/files
RSV B: https://clades.nextstrain.org/?dataset-url=github:nextstrain/nextclade_data@add-rsv@/data/datasets/rsv_b/references/MW020595/versions/2022-12-18T14:59:42Z/files

**Comment by corneliusroemer** [comment]
We have an early Christmas present for you @laura-bankers 🎄: The first RSV A and B Nextclade datasets have just been released: https://github.com/nextstrain/nextclade_data/releases/tag/2022-12-23--16-36-09--UTC

You can find them on the main Nextclade website
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/25161793/209374562-73e2e822-c06e-49f2-ada8-4389b0b5ebdf.png">
