### ISSUE TITLE
Bogus mutations in definition of BE.9

### ISSUE THREAD

**Issue by silcn** [nextstrain/nextclade#1077]
Lineage BE.9 contains a huge deletion 27508-27751del. The Brazilian bioinformatics pipelines have had issues with this, producing the erroneous substitutions A27508C and A27749G. Since the lineage arose in Brazil, Nextclade lists these two substitutions as defining and so non-Brazilian BE.9 sequences are not getting recognised as BE.9. See [https://github.com/cov-lineages/pango-designation/issues/1430](https://github.com/cov-lineages/pango-designation/issues/1430)

**Comment by corneliusroemer** [comment]
Thanks @silcn for digging into this! I'll do a manual override of these lineage defining mutations and it'll be fixed in the next release.

Are you aware of the same problem in any other lineages?

**Comment by silcn** [comment]
@corneliusroemer thanks! Not aware of any other cases like this but I haven't been looking out for them.
