### ISSUE TITLE
Alternative Splicing

### ISSUE THREAD

**Issue by fanninpm** [nextstrain/nextclade#1079]
I was thinking of making Nextclade datasets for the human adenoviruses, starting with hAdV-F (NCBI accession: [NC_001454.1](https://www.ncbi.nlm.nih.gov/nuccore/NC_001454.1)), but I ran into a snag almost right away. The expression of certain genes uses [alternative splicing](https://viralzone.expasy.org/1943), but Nextclade has a hard time reconciling discontiguous coding segments that contribute to the same polypeptide, especially when an intron interrupts a codon.

For example, [the E1A gene](https://www.ncbi.nlm.nih.gov/nuccore/NC_001454.1?from=387&to=1326) has [an intron](https://www.ncbi.nlm.nih.gov/nuccore/NC_001454.1?from=1012&to=1087) that splits [the coding region](https://www.ncbi.nlm.nih.gov/nuccore/NC_001454.1?location=486:1011,1088:1311) in the middle of a codon.

**Comment by ivan-aksamentov** [comment]
@fanninpm In https://github.com/nextstrain/nextclade/pull/1073 I am currently working on reimplementing genome annotation, and related parts of translation and analysis to account for  not only gene features (in [GFF3](https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md) / [sequence ontology](http://www.sequenceontology.org/browser/obob.cgi) lingo), but also [CDS](http://www.sequenceontology.org/browser/current_release/term/SO:0000316), and potentially [mature protein regions](http://www.sequenceontology.org/browser/current_release/term/SO:0002249). This should hopefully include your case with hAdV.

Could you please provide some of the examples of genome annotations in GFF3 format which are relevant for your current or future work?

The consequences of this feature is quite complex for Nextclade internals, so it might take some time.

**Comment by ivan-aksamentov** [comment]
Cleaning up old issues.

Nextclade supports splicing since v3. Give it a try if not yet.

Open a new u=issue if there's outstanding problems.
