### ISSUE TITLE
Dataset download not working

### ISSUE THREAD

**Issue by denise0593** [nextstrain/nextclade#1083]
Dear team,
I'm trying to download the human MonkeyPox reference, I've tried to download it with the following command line, but nothing happened.
`docker run -it --rm nextstrain/nextclade:latest nextclade dataset get --name 'hMPXV' --reference 'NC_063383.1' --output-dir data/human_monkey`
 
What I'm doing wrong?
Thanks a lot

**Comment by ivan-aksamentov** [comment]
@denise0593  What are you expecting to happen? You are downloading a dataset into the container filesystem. If you want it on your host machine, mounting a volume and setting output dir to that volume as @fanninpm mentioned should help. This does not seem to be an issue in Nextclade. But if you think there is, feel free to comment and/or ope a new issue.
