### ISSUE TITLE
Genomic x axis not aligned with annotations

### ISSUE THREAD

**Issue by theosanderson** [nextstrain/nextclade#1084]
Thanks as ever for Nextclade.

When I load (even with the example FASTA from the site) sequences, the x axis annotation does not line up with the bars indicating variation, e.g. 

![image](https://user-images.githubusercontent.com/19732295/212406472-a47d9c18-390a-4a98-ba90-215a57b8ec90.png)

I think it used to?

I'm on Chrome on MacOS and this is with version 2.9.1 (commit: 3baa16a, branch: release)

Edit: it does line up for e.g. RSV

**Comment by ivan-aksamentov** [comment]
Ooops. Thanks for reporting

**Comment by ivan-aksamentov** [comment]
Should be resolved in https://github.com/nextstrain/nextclade/pull/1093. 

@theosanderson Please double-check if you have a second. The link to preview build is in the Vercel bot message.

**Comment by theosanderson** [comment]
LGTM, thanks!
