### ISSUE TITLE
REST API to POST fastas

### ISSUE THREAD

**Issue by nbx0** [nextstrain/nextclade#1091]
Is there a REST endpoint to POST fasta sequences to nextclade, returning a URL with the staged fasta for calling `https://clades.nextstrain.org?dataset-name=sars-cov-2&input-fasta=https://example.com/sequences.fasta` ?

Thanks and Cheers,
Ben Rambo-Martin

**Comment by corneliusroemer** [comment]
Nextclade web is purely client-side - there is no server (other than the static one serving the assets). So I don't think what you're requesting works.

Instead: you can just post the fastas wherever you want to store them and then pass that URL to Nextclade. For example, you could post it to transfer.sh and download from there, or do I misunderstand your requirements?

**Comment by nbx0** [comment]
Thank for rapid response. I understand now.  Excellent feature!

Ben

**Comment by corneliusroemer** [comment]
Do I understand it correctly that you thought you couldn't just include any URL but had to post the sequences to some Nextclade server first? Just trying to understand how you came up with the idea for wanting to POST to Nextclade. Or is there another use case you're thinking about?

**Comment by corneliusroemer** [comment]
If you want to interact purely programatically with Nextclade, consider using the CLI: https://docs.nextstrain.org/projects/nextclade/en/stable/user/nextclade-cli.html#quick-example

Though there is no way to get a GUI this way, output is purely textfile based.
