### ISSUE TITLE
Nextclade XBP seems include other unrelated BQ.1/BA.2.75 recombinant lineages

### ISSUE THREAD

**Issue by FedeGueli** [nextstrain/nextclade#1103]
@corneliusroemer i noticed that Nextclade ( and i think pangolin too) over include sequences in this lineage probably merging in it the other 4 BQ.1/Ba.2.75 proposed lineages.:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=XBP*&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&
 

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1c419_cdaf00.json
<img width="1155" alt="Schermata 2023-02-03 alle 11 06 08" src="https://user-images.githubusercont
<img width="1116" alt="Schermata 2023-02-03 alle 11 06 24" src="https://user-images.githubusercontent.com/87669813/216572227-7399c2a7-932a-4bf3-b355-f78ada2c9c0d.png">
ent.com/87669813/216572155-2f065e35-f744-4429-b77f-7322decc866a.png">

**Comment by corneliusroemer** [comment]
Yeah this is quite inevitable with the current design.

Unless this is due to short Austrian sequences which is something I'm working on fixing.
