### ISSUE TITLE
Extend XBB.1.16 update to Nextclade beyond the dev/vercel app version. 

### ISSUE THREAD

**Issue by FedeGueli** [nextstrain/nextclade#1120]
I gently ask in behalf of some scientists which asked me from the area where this variant is fastly spreading if it is possible to urge the update to Official Nextclade of XBB.1.16 , i tipped them with the vercel app nextclade version.
The ideal thing it would be a double update to Nextclade and then to CovSpectrum via @chaoran-chen if it is possible.

I know you all re working hard already on this so very sorry for bothering but it seems a bit more than the usual thing.

**Comment by corneliusroemer** [comment]
Update will come soon, thanks for ping

**Comment by FedeGueli** [comment]
Thank you @corneliusroemer for your work

**Comment by karyakarte** [comment]
Thanks, Vercel helped today for XBB.1.16 identification.

**Comment by corneliusroemer** [comment]
We'll release tomorrow, less than 24hr - sorry for the wait
