### ISSUE TITLE
Minor visual bug: Unknown sequence range marker on last aa does not go all the way to end of gene view

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#1121]
Noticed a small visual bug: the X marker (and frameshift bar) for the last amino acid in a gene does not extend all the way to the end of the gene - which is unexpected because the last amino acid is the last and there shouldn't be anything afterwards:

![image](https://user-images.githubusercontent.com/25161793/224650899-19e73fea-59b8-4e10-86f7-0d5969ad1bf9.png)

Reproduce with this, and go to ORF8 view:
https://master.clades.nextstrain.org/?dataset-name=sars-cov-2&input-fasta=https://gist.githubusercontent.com/corneliusroemer/54037470cfe9009da65d41d1fb22de17/raw/6a60ca513c68c19fe1c714577413ed6fef32d14d/XP.fasta.txt

**Comment by ivan-aksamentov** [comment]
Seems to be fixed now

![001](https://github.com/nextstrain/nextclade/assets/9403403/54914ad9-87b5-4c9d-b3e5-94383aa95ea5)

Comment/reopen if not
