### ISSUE TITLE
Error compiling development instance

### ISSUE THREAD

**Issue by ArtPoon** [nextstrain/nextclade#1140]
Following recipe in `docs/dev/developed-guide.md`, installation process seems to have gone okay but script threw an exception:
```
    Finished dev [unoptimized + debuginfo] target(s) in 5m 20s
     Running `target/debug/nextclade run data_dev/sequences.fasta --input-dataset=data_dev/ --output-fasta=out/nextclade.aligned.fasta --output-tsv=out/nextclade.tsv --output-tree=out/nextclade.tree.json --in-order --include-reference`
Error: 
   0: --input-dataset: path is invalid. Expected a directory path or a zip archive file path, but got: '"data_dev/"'
```
There is no `data_dev` folder at project root.  I'm on `master` branch, commit c0807f5a1f4c8b44b7e8749b398157df4990ea22
If I point the command to `data/sars-cov-2` instead, another exception is thrown about missing `primers.csv`, which is a deprecated file.  

OS: Ubuntu 20.04.6
cargo 1.67.1

**Comment by ivan-aksamentov** [comment]
@ArtPoon The comment in the guide suggests to retrieve a dataset:

https://github.com/nextstrain/nextclade/blob/c0807f5a1f4c8b44b7e8749b398157df4990ea22/docs/dev/developer-guide.md?plain=1#L33-L36

This is what Nextclade software requires as inputs.

It is mentioned only briefly in dev docs, because when I wrote it, I assumed Nextclade devs are already familiar with Nextclade from user's standpoint. But we've actually already had a similar situation where this assumption turned out to be incorrect. So perhaps we need to add a command for downloading a dataset to the dev docs.

**Comment by ArtPoon** [comment]
Yes that did the trick.  Sorry for my noob question!
```console
(venv) art@Kestrel:~/git/nextclade$ cargo run --bin=nextclade -- dataset get --name=sars-cov-2 --output-dir=data_dev
    Finished dev [unoptimized + debuginfo] target(s) in 0.41s
     Running `target/debug/nextclade dataset get --name=sars-cov-2 --output-dir=data_dev`
(venv) art@Kestrel:~/git/nextclade$ cargo run --bin=nextclade -- run   data_dev/sequences.fasta   --input-dataset=data_dev/   --output-fasta='out/nextclade.aligned.fasta'   --output-tsv='out/nextclade.tsv'   --output-tree='out/nextclade.tree.json'   --in-order   --include-reference
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
     Running `target/debug/nextclade run data_dev/sequences.fasta --input-dataset=data_dev/ --output-fasta=out/nextclade.aligned.fasta --output-tsv=out/nextclade.tsv --output-tree=out/nextclade.tree.json --in-order --include-reference`
(venv) art@Kestrel:~/git/nextclade$ cargo build --release --bin=nextclade
   Compiling libc v0.2.126
...
   Compiling nextclade v2.13.1 (/home/art/git/nextclade/packages_rs/nextclade)
   Compiling nextclade-cli v2.13.1 (/home/art/git/nextclade/packages_rs/nextclade-cli)
    Finished release [optimized] target(s) in 3m 47s
(venv) art@Kestrel:~/git/nextclade$ ./target/release/nextclade run \
>   data_dev/sequences.fasta \
>   --input-dataset=data_dev/ \
>   --output-fasta='out/nextclade.aligned.fasta' \
>   --output-tsv='out/nextclade.tsv' \
>   --output-tree='out/nextclade.tree.json' \
>   --in-order \
>   --include-reference
```

However there is no `nextclade` binary.

**Comment by ArtPoon** [comment]
Ok `find` command located binary in `target/release`.  Just did a brute force copy of binary to `/usr/local/bin`.

**Comment by ivan-aksamentov** [comment]
We should probably link to the Rust Book and Cargo Book in the docs.

https://doc.rust-lang.org/book/

https://doc.rust-lang.org/cargo/

And perhaps also docs for other important tech stack components: Typescript, Node.js, yarn, React, Recoil and Next.js

There's a lot of things to know before a complex app like this can be understood.

**Comment by ArtPoon** [comment]
Certainly linking this particular page would be helpful:
https://doc.rust-lang.org/book/ch01-03-hello-cargo.html
