### ISSUE TITLE
Make Installation docs  more prominent rather than GitHub releases?

### ISSUE THREAD

**Issue by theosanderson** [nextstrain/nextclade#1167]
I am installing the CLI for the first time and have some very small UX feedback in case you're interested.

As someone wanting to install my instinct was to hit the "Downloads" button at the top of the Nextstrain CLI box in https://clades.nextstrain.org/, sending me to the GitHub releases page, which I needed to expand to see the relevant download for me. In fact I think I'd have done much better to head to https://docs.nextstrain.org/projects/nextclade/en/stable/user/nextclade-cli.html which has direct links to the most relevant files, as well as command line instructions. My suggestion would maybe be to make the Downloads button link to the top of that docs page and the Documentation button link to Usage.

Tiny issue - do close without action.

**Comment by ivan-aksamentov** [comment]
I think this have been resolved in v3. We now have "CLI" link in the navbar which leads to the CLI docs.
