### ISSUE TITLE
Display some of the PCR primers

### ISSUE THREAD

**Issue by ivan-aksamentov** [nextstrain/nextclade#119]
We want to highlight some of the the primers typically used in PCR.
This can also be further extended to highlighting mutations in these regions.

**Comment by nabito** [comment]
I'm also interested in this feature.

Any idea how to implement it? Or where to first look.

**Comment by ivan-aksamentov** [comment]
@nabito Hello,

For this we will need a list of places where the PCR primers typically are in the DNA/RNA of the virus. Then we just need to highlight them in the SequenceView.

We might also loop over all the mutations in a given sequence and check if it falls into a primer fragment. This can be done somewhere in the analysis part of the algorithm. If there are mutations detected in any of the primer fragments, we may report this in the tooltip of this sequence.

The difficulty here is to find and gather PCR primer data and to convert it to the format convenient to use in the web app (e.g. JSON, containing an array of ranges: { begin, end }, or similar).
