### ISSUE TITLE
[v3] error attaching nodes to tree

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/nextclade#1207]
_@ivan-aksamentov  I'm sure you're aware of these so feel free to close if it's on your radar to fix_

Nextclade (v3, built from 3653a044) when running HBV data, including the provided test sequences, raises the following error:

```console
./target/release/nextclade run -j 1 --input-dataset test_datasets/hbv/files \
  --output-all <dir> --output-basename v3 \
  test_datasets/hbv/files/sequences.fasta

Error: 
   0: When attaching the new node for query sequence 'OP153999.1 |Hepatitis B virus isolate HBV_OBI_UFD1193, complete genome' to the tree
   1: Parent node is expected, but not found. This is an internal error. Please report it to developers

Location:
   packages_rs/nextclade/src/tree/tree_builder.rs:191
```

You can see this in the [web UI too](https://nextclade-git-v3-nextstrain.vercel.app/?dataset-url=github:nextstrain/nextclade@/v3@/test_datasets/hbv/files&input-fasta=example)

I wondered whether this was due to using a dummy `tree.json` in that (test) dataset. I created a proper tree (will share in slack) and swapped the dataset to that. This resulted in a different error:

```console
Error: 
   0: When attaching the new node for query sequence 'OP255998.1 |Hepatitis B virus isolate HBV_OBI_SPb274, complete genome' to the tree
   1: When splitting mutations between query sequence and the child node 'NODE_0001450'
   2: When splitting private nucleotide substitutions
   3: Found mutations with the same position, but different reference letters: C2740A and T2740C. This is an internal error. Please report it to developers

Location:
   packages_rs/nextclade/src/tree/split_muts.rs:118
```

In both cases the alignments, translations + metadata are written out before the program exits code 1

**Comment by ivan-aksamentov** [comment]
@jameshadfield Thanks! 

The first error is reproducible. We will check it with Richard.

Regarding the second error, could you please share the tree (or better full dataset) so that we can reproduce?

**Comment by ivan-aksamentov** [comment]
I merged https://github.com/nextstrain/nextclade/pull/1208, which should solve the first error.

**Comment by ivan-aksamentov** [comment]
The second part should be addressed in https://github.com/nextstrain/nextclade/pull/1211
