### ISSUE TITLE
Files required to configure a custom dataset when using nextclade for pathogens not provided by nextclade

### ISSUE THREAD

**Issue by gksruf0323** [nextstrain/nextclade#1225]
I would like to ask you to use nextclade better.

I want to analyze new pathogens that do not correspond to the species provided by nextclade (covid, mpox, etc.) using nextclade. I understand that a custom dataset is required for this.

When creating a custom dataset
1. reference tree
2. root sequence
3. quality control
4. Virus properties
5. gene map
6. PCR primers

I found out from your explanation that you need a total of six, but I couldn't find a way to create them. I would appreciate it if you could tell me how to make it.

Thanks!

**Comment by ivan-aksamentov** [comment]
Hi @gksruf0323 right now the only way is to look at the existing datasets and to try to repeat the same. You can find source data here:
https://github.com/nextstrain/nextclade_data/tree/master/data/datasets

There is also a little bit of info in the docs:
https://docs.nextstrain.org/projects/nextclade/en/stable/user/datasets.html#creating-a-custom-dataset

Just copy the folder of the dataset from a pathogen that is the most resembling your new pathogen, and modify the files to fit your needs. Most files should be straightforward (you can find meaning of files in the docs). For things you don't need, you can leave empty/dummy files. Building a good reference tree JSON might be challenging.

The trees for the current datasets are prepared using Nextstrain Augur by Cornelius here:
https://github.com/neherlab/nextclade_data_workflows
Refer to Augur's docs and tutorials for more info.

You could also find some thoughts, tips and tricks in these PRs:
https://github.com/nextstrain/nextclade_data/pull/57
https://github.com/nextstrain/nextclade_data/pull/44
but they are very chaotic.

Note that, we are in the process of preparing the next major release of Nextclade, version 3, which will come with breaking changes, including the new dataset format. You can sneak peek on the v3 work happening here, but it is very early and things will still break a lot in the coming weeks:

https://github.com/nextstrain/nextclade_data/pull/79

https://github.com/nextstrain/nextclade/pull/1185

One of the goals of v3 is to make dataset creation simpler and to document the process. As  well as to allow community to share new datasets more easily. Stay tuned!

**Comment by gksruf0323** [comment]
I could get a lot of help.

Thank you!
