### ISSUE TITLE
why nextclade.csv download from the website can not in good format in excel?

### ISSUE THREAD

**Issue by liamxg** [nextstrain/nextclade#1230]
<img width="1170" alt="image" src="https://github.com/nextstrain/nextclade/assets/46078579/92c1578c-9a25-4ab9-87d9-e5bfce943ce1">

**Comment by tsibley** [comment]
@liamxg It's rude to tag everyone who's contributed to this repo like you've been doing. Please don't do so in the future. Thank you.

From your screenshot it looks like you need to import the file to Excel with the delimiter set to `;` instead of `,`.
