### ISSUE TITLE
Add user's giude

### ISSUE THREAD

**Issue by ivan-aksamentov** [nextstrain/nextclade#128]
We want to explain our users the basics of how our app operates and what they are seeing.

We want to cover particularly carefully the places where we use some conventions (color, notation, terminology, etc.), no matter how well-known they are.

**Comment by rneher** [comment]
yes, will do. could you stub out a place where these explanations go?

**Comment by ivan-aksamentov** [comment]
For future readers:

This s now implemented as a standalone documentation website: https://docs.nextstrain.org/projects/nextclade

If there are remaining questions, feel free to:
 - submit a new issue: https://github.com/nextstrain/nextclade/issues/new/choose
 - join the discussion forum: https://discussion.nextstrain.org/
