### ISSUE TITLE
Parsing PCR primers

### ISSUE THREAD

**Issue by FatemehA-bio** [nextstrain/nextclade#1342]
Dear Nextclade developers,

I faced this error when uploading customized primer file. I want to align a list of primers. 
Could you please help me?
Thank you.
Best
Fatemeh

Error message: Error: When initializing Nextclade runner: When parsing PCR primers: CSV deserialize error: record 1 (line: 1, byte: 69): missing field `Country (Institute)`: missing field `Country (Institute)`

Nextclade version 2.14.1 (commit: 85e00e8, branch: release)

Memory available: 2089 MBytes

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

Browser details: {"browser":{"name":"Chrome","version":"109.0.0.0"},"os":{"name":"Windows","version":"NT 10.0","versionName":"10"},"platform":{"type":"desktop"},"engine":{"name":"Blink"}}

Call stack:

Error: When initializing Nextclade runner: When parsing PCR primers: CSV deserialize error: record 1 (line: 1, byte: 69): missing field `Country (Institute)`: missing field `Country (Institute)`
    at M (https://clades.nextstrain.org/_next/static/chunks/68.daad1778960b5734.js:1:15774)
    at https://clades.nextstrain.org/_next/static/wasm/cf835b4f9fbcf56c.wasm:wasm-function[1547]:0x1e3d5c
    at new a (https://clades.nextstrain.org/_next/static/chunks/68.daad1778960b5734.js:1:9424)
    at https://clades.nextstrain.org/_next/static/chunks/68.daad1778960b5734.js:1:24056
    at u (https://clades.nextstrain.org/_next/static/chunks/444.170c49d0571b2ba1.js:1:28086)
    at Generator._invoke (https://clades.nextstrain.org/_next/static/chunks/444.170c49d0571b2ba1.js:1:29376)
    at a.<computed> [as next] (https://clades.nextstrain.org/_next/static/chunks/444.170c49d0571b2ba1.js:1:28489)
    at p (https://clades.nextstrain.org/_next/static/chunks/68.daad1778960b5734.js:1:21841)
    at d (https://clades.nextstrain.org/_next/static/chunks/68.daad1778960b5734.js:1:22038)
    at https://clades.nextstrain.org/_next/static/chunks/68.daad1778960b5734.js:1:22097

**Comment by ivan-aksamentov** [comment]
How does your file look like?

This is the format that's used in Nextclade v2
https://github.com/nextstrain/nextclade_data/blob/049af8721b1f9d58a1ef3690afef31bfcf001069/data/datasets/sars-cov-2/references/MN908947/versions/2023-10-26T12%3A00%3A00Z/files/primers.csv?plain=1

However, PCR primer functionality will be removed from Nextclade v3. Can you tell us a little how you use it and whether it will still be required for your work?

**Comment by ivan-aksamentov** [comment]
How does your file look like?

This is the format that's used in Nextclade v2
https://github.com/nextstrain/nextclade_data/blob/049af8721b1f9d58a1ef3690afef31bfcf001069/data/datasets/sars-cov-2/references/MN908947/versions/2023-10-26T12%3A00%3A00Z/files/primers.csv?plain=1

However, PCR primer functionality will be removed from Nextclade v3. One of the reasons was that noone could figure out the format and it was rarely used feature as far as we can tell.


By the prase "I want to align a list of primers." it is not entirely clear to me you understand what PCR primer detection does in Nextclade.

Can you tell us a little how you use it and whether it will still be required in Nxtclade v3 for your work? How do you imagine it should work? What input file formats would you like it to accept? This will help us to plan the upcoming changes better.

**Comment by ivan-aksamentov** [comment]
I will close the issue for now. Please comment or create a new one if there's still outstanding problems.
