### ISSUE TITLE
how many SARS-COV-2 sequences can nextclade handle in a MSA file?

### ISSUE THREAD

**Issue by liamxg** [nextstrain/nextclade#1345]
Dear @nextclade team,

I have more than 5 million SARS-COV-2 sequences need to align, can nextclade handle this?

**Comment by ivan-aksamentov** [comment]
Hi, @liamxg, it depend on what version you want to use.

Nextclade Web (the web version, on https://clades.nextstrain.org) can handle ~1000 sequences at a time, depending on your browser and computer resources (computation is done inside your browser, on your computer). If you need to use Nextclade Web, then we recommend to split your data into smaller batches and/or subsample it.

For large-scale analysis we recommend using Nextclade CLI (command line version; see docs here: https://docs.nextstrain.org/projects/nextclade/en/stable/user/nextclade-cli.html). You can see how we use it internally in:
 - https://github.com/nextstrain/ncov-ingest (fetching from GISAID and Genbank databases, alignment and basic analysis)
 - https://github.com/nextstrain/ncov (phylogenetic analysis)

Feel free to join our discussion forums, where you can discuss your case with other users and with Nextstrain team: https://discussion.nextstrain.org/

**Comment by ivan-aksamentov** [comment]
What's inside `data/sars-cov-2`?

**Comment by ivan-aksamentov** [comment]
@liamxg If Nextclade cannot find dataset files, it means you probably confused your directories. This is not related to Nextclade, so you will have to figure this out yourself, sorry. I'd suggest to delete everything and start over paying attention to what paths you are giving to Nextclade and what these paths actually contain. Make sure you read `nextclade --help`, `nextclade dataset get --help` and `nextclade run --help`.

Please open a new issue if you have questions or reports related to Nextclade.
