### ISSUE TITLE
Short sequences are flagged with a QC pass

### ISSUE THREAD

**Issue by george-githinji** [nextstrain/nextclade#135]
1. Very short sequences (1 or even 2 nucleotide) with no ambiguous bases  are flagged as a pass. Could implement a filter for sequence length.

2. How are  lead and trailing 5' and 3' UTRs handled? Should N's in these region comprise a fail in QC?

**Comment by rneher** [comment]
the main issue should be solved. but QC for short sequences is not adequately addressed. We are looking into a better organization of the QC procedure, so will hopefully tackle this along with it.

**Comment by rneher** [comment]
I don't view missing 5' and 3' parts as a QC issue. It likely means only a fragment was sequenced. But the QC criteria should be scaled relative to length of the fragment. Let us know how you'd expect the app to behave.

**Comment by george-githinji** [comment]
One approach might be to disregard Ns within the 3' and 5' regions. This implies identifying these regions from a submitted sequence.
