### ISSUE TITLE
web(minor): when customizing dataset files, it always says "pasted sequences" even if the field is for tree

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#1365]
See 
<img width="757" alt="image" src="https://github.com/nextstrain/nextclade/assets/25161793/ae391bbe-b964-4ab2-8089-7204c9fe5320">

It shouldn't always say "pasted sequences" when it's a tree etc.

**Comment by ivan-aksamentov** [comment]
These are the ones you've pasted into the "Text" tab, right? So the "pasted" is correct and "sequences" is wrong.

Can you propose a correct text universal for all fields?

**Comment by corneliusroemer** [comment]
"Pasted text" ?
