### ISSUE TITLE
I upload 1490 sequences to nextclade, and upload to auspice.us, why it shows me 4255 sequences?

### ISSUE THREAD

**Issue by liamxg** [nextstrain/nextclade#1371]
Dear @huddlej ,

<img width="1326" alt="image" src="https://github.com/nextstrain/nextclade/assets/46078579/da1cb263-02f1-4b5a-a7e9-04a7ff4c0ac0">

**Comment by rneher** [comment]
these are the sequences you analyzed + the tips in the reference tree.

**Comment by ivan-aksamentov** [comment]
I will close the issue for now. Please comment or create a new one if there's still outstanding problems.
