### ISSUE TITLE
Can support be extended for SC2 Datasets V2 for another month? 

### ISSUE THREAD

**Issue by ammaraziz** [nextstrain/nextclade#1397]
Hi Nextclade Team,

Thank you for creating and maintaining this amazing software. 

For SC2 sequencing surveillance we use the [wf-artic pipeline](https://github.com/epi2me-labs/wf-artic/) which has not yet updated to Nextclade V3. In other words we're stuck on V2 and the associated datasets (which look to be already behind by one version). 

The pipeline uses docker images to run Nextclade, and these are custom built on a base image that's not public. So internally I would have trouble copying + modifying the image to run Nextclade V3. [I have submitted an issue to the repo](https://github.com/epi2me-labs/wf-artic/issues/107). I think quiet a few labs rely on ONT wf-X pipelines which all seem to use the same docker image.

I realise this is a big request and probably an annoying request at that but it would help those of us stuck on V2 enough time to transition to V3.

**Comment by corneliusroemer** [comment]
V2 is not yet behind by 1 month! It's currently both at the same release (otherwise let me know and I'll fix it).

Yes, I think we could do another v2 release if this would be so useful. Thanks for writing a justification!

**Comment by ammaraziz** [comment]
Apologies I misunderstood, I thought [2024-01-16--20-31-02Z](https://github.com/nextstrain/nextclade_data/releases/tag/2024-01-16--20-31-02Z) was the latest SC2 release but it looks to be the release to convert V2 datasets to V3. 

Another release of V2 would be greatly appreciated!

**Comment by ammaraziz** [comment]
wf-artic has been updated to Nextclade V3. https://github.com/epi2me-labs/wf-artic/releases/tag/v1.1.0

Thank you @ivan-aksamentov and @corneliusroemer for your all your help and support. 

Closing, no longer needed!
