### ISSUE TITLE
Feature Request: Dataset download all datasets within specified path

### ISSUE THREAD

**Issue by ammaraziz** [nextstrain/nextclade#1410]
Hi Nextclade Folks,

I'd like to run nextclade on all influenza genes for many samples. The first step is to `nextclade dataset get` the required datasets:

```
nextclade dataset get --name "nextstrain/flu/h3n2/pa" --output-dir outputdir/pa
nextclade dataset get --name "nextstrain/flu/h3n2/mp" --output-dir outputdir/mp
...
``` 
I would need to enter/code 8x `nextclade dataset get` commands.

 It would be amazing if I could just simply do:
```
nextclade dataset get --name "nextstrain/flu/h3n2/*" --output-dir outputdir/
```
Note the `*` to stop accidentally downloading all the datasets.

There are multiple `ha` datasets which are downloaded - this is okay in my opinion but not ideal. In such cases maybe download the `flu_h3n2_ha_broad`?

An alternative solution would be to create a new shortcut that downloads a set of predefined datasets.

Feel free to close this issue if you think it's frivolous.

**Comment by ammaraziz** [comment]
> We have been thinking how to simplify making multiple runs with a single command, for example for different flu segments. And perhaps even to combine results for different segments and process them further. But haven't figured anything quite yet. Is this your use-case?

Yes it's very close to the use case! 

> In your proposal, how would you access the downloaded datasets afterwards? There is no way of knowing what's being downloaded and to where and how many. And you'd still need to copy-paste nextclade run 8 times. Also, datasets come and go, today it might be 8, tomorrow there's 32.

I had not considered this, this puts a big red ! on my request. But as you hinted above, the ability to make multiple runs with a single command falls within this idea.

> I did not understand how * should stop downloading all datasets. Usually in paths * denotes so-called wildcard, that is any path under that particular path. Does nextclade currently downloads all datasets if you omit the *? (if so, it's a bug!) Can you clarify?

To stop accidentally entering in: `nextstrain/flu/` which will download all datasets for all species of full (but as you said this doesn't generalise to other species supported by nextclade).

> While wildcard downloads are not supported yet, in the meantime, there is a couple of other approaches you might consider: 
> ....

Thank you for the code and the explanation, this does achieve my task (or what instigated this feature request). You've perfectly represented what I was trying to do in the code, that is not hard code the flu datasets. 

Going back to this:

>We have been thinking how to simplify making multiple runs with a single command, for example for different flu segments. 

This feature request would be part of this bigger picture of running multiple runs with a single command. Therefore, closing this issue as in hindsight it should have been a discussion.

Thanks again!

**Comment by rneher** [comment]
@ammaraziz, what might be useful for you is `nextclade sort`. We are currently refining some of the matching parameters, but what you can do for example is
```
nextclade sort all_my_rsv_sequences.fasta --output-dir split_by_dataset --output-results-tsv table_with_matches.tsv
```
this will split your input sequences into files corresponding to datasets (and their prefixes).

**Comment by ammaraziz** [comment]
Hi Richard,

That's actually the usecase which triggered this request.

Thanks again :)
