### ISSUE TITLE
21L Tree Updates?

### ISSUE THREAD

**Issue by ryhisner** [nextstrain/nextclade#1431]
Are there any plans to update the 21L tree? It's been an invaluable resource for me, and now that it hasn't been updated in a couple months, I'm unable to make sense of the variants that have been designated since then.

**Comment by corneliusroemer** [comment]
It's now called BA.2 🙃 sorry for that not having been clear

https://nextstrain.org/staging/nextclade/sars-cov-2/BA.2?branchLabel=aa&c=designation_recency

**Comment by ryhisner** [comment]
Awesome. Thanks, @corneliusroemer!
