### ISSUE TITLE
how to generate the result table by the cli version auspice

### ISSUE THREAD

**Issue by baimianer** [nextstrain/nextclade#1441]
![image](https://github.com/nextstrain/nextclade/assets/21122009/ee159f20-dd03-4878-90cb-cc3d9bca14b8)

**Comment by ivan-aksamentov** [comment]
@baimianer There is no way to do this currently. The table is for web only. But after CLI run you have alignment fasta and TSV outputs which contain the same information and even more. You can analyze it further and render it any way you like. A simple way - you can open TSV output in Excel, Google Sheets or any other spreadsheet.

**Comment by baimianer** [comment]
![image](https://github.com/nextstrain/nextclade/assets/21122009/f2725ab4-2397-4946-b6d5-5ea32ce7726c)
For example, by using auspice cli version , I can view the tree on the browser. So I want to know if there are any tools that can display the result table? The results nextclade web presents are very perfect.

**Comment by ivan-aksamentov** [comment]
> So I want to know if there are any tools that can display the result table?

Nope

**Comment by baimianer** [comment]
Thank you for your answer
