### ISSUE TITLE
Community build cache validity bug

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/nextclade#1450]
Loading a dataset via the `dataset-url` query ([e.g.](https://clades.nextstrain.org/?dataset-url=https://github.com/nextstrain/measles/tree/use-nextclade-dataset/nextclade_dataset)) seems to use a locally cached version without thoroughly checking the underlying dataset for changes. (I presume this is via `LocalStorage.Nextclade-storage-v4`.) In the example URL above (and where this was first noticed by @kimandrews and myself) the cached / now out-of-date version looks like this:

<img width="510" alt="image" src="https://github.com/nextstrain/nextclade/assets/8350992/08335387-ae87-46bf-84bd-11972dbfc6e4">

and the same URL in a private-browsing window shows the updated metadata (reference name):

<img width="511" alt="image" src="https://github.com/nextstrain/nextclade/assets/8350992/56c1fa4e-880b-4873-8e87-3a3e988c7f0b">

**Comment by ivan-aksamentov** [comment]
Does this fix the problem?

[fix(web): update current dataset when remote pathogen.json changes #1453
](https://github.com/nextstrain/nextclade/pull/1453)

**Comment by jameshadfield** [comment]
🙏  Thanks @ivan-aksamentov - the original link now correctly displays (unknown whether the cache's expired vs the new code is working as intended, but I'm going to guess the latter!).
