### ISSUE TITLE
Add ability to provide custom tree and root sequence in the web app

### ISSUE THREAD

**Issue by ivan-aksamentov** [nextstrain/nextclade#205]
CLI already have this capability, so all that's needed is to add UI elements to accept the files, read the files content and to pass it to the algorithm instead of defaults.

We might have an expandable section on main page for the advanced params and file uploads #210

**Comment by rneher** [comment]
If we don't want to deal with UI at first, you could also do this via URL queries... just like the input fasta. 

In this context, there is also a longstanding issue to include the full root sequence into the auspice json (or via a side-car json). That would reduce the number of things that need fetching...

**Comment by ivan-aksamentov** [comment]
@rneher We could do that. Although there are funny corner cases need to be figured out.

For example, what to do if tree is provided, but fasta is not, remember the tree and show a main page? show an error? 

Some more curious situations may happen when we allow for multiple viruses #213, like different files passed into the app belonging to a wrong virus.

**Comment by ivan-aksamentov** [comment]
#247 now allows for fetching these via URl params

The proper UI is discussed in #210.
