### ISSUE TITLE
input-fasta URL parameter truncates after first URL parameter

### ISSUE THREAD

**Issue by jshoe** [nextstrain/nextclade#246]
- I did a test run with an AWS S3 presigned link in this format: `https://clades.nextstrain.org/?input-fasta=https://bucket-name.s3.amazonaws.com/path/consensus.fa?AWSAccessKeyId=<redacted>&Signature=<redacted>&x-amz-security-token=<redacted>&Expires=1604519170`

- The presigned link works in the browser by itself, but it looks like the hosted Nextclade is only parsing through the first URL parameter `AWSAccessKeyId`, so it misses the `&Signature` and rest of the URL. Would be great if it could parse the rest to support presigned links like this!

![Screen Shot 2020-11-04 at 10 47 06 AM](https://user-images.githubusercontent.com/5652739/98156276-6ee9c180-1e8c-11eb-9786-807754b3e26d.png)

**Comment by ivan-aksamentov** [comment]
@jshoe Thanks Jonathan,

The best practice would be to urlencode the values, such that the `?`, `&` and other significant characters are escaped.

Currently we are using the whatever URL parsing Next.js Router provides and it probably just splits the URL on `?` and `&`, thinking that `AWSAccessKeyId` and `Signature` are the parameters destined for Nextclade itself, not as a part of the fasta URL.

Even if I use another implementation and get the whole query string, as you posted. I cannot see immediately how I can parse that correctly in all cases, especially given the #247 introduces more URL params (and even more coming in the future) and these parameters can be in any order. I just don't know when one param starts and another ends.

I don't have any immediate solution in mind. How about you?

**Comment by jshoe** [comment]
Thanks Ivan! Using `encodeURIComponent()` on my end is totally fine for what I'm thinking of right now. Will close this one.
