### ISSUE TITLE
What is Private Mutations QC column?

### ISSUE THREAD

**Issue by tjbutler003** [nextstrain/nextclade#265]
Hello, I think I understand most of the QC columns but am having a difficult time understanding what 'qc.privateMutations.*' columns stand for. I wasn't able to find any information on that one, could you provide more?
Thanks, T.J.

**Comment by ivan-aksamentov** [comment]
Hi @tjbutler003,

We call "private mutations" the mutations which belong to the analyzed sequence only, and which it does not share with its predecessors on a phylogenetic tree.

We find these private mutations when traversing the reference tree and looking for the best matching ("nearest") reference node (to know where to attach the analyzed sequence, and what clade we need to assign to it). The algorithm goes roughly as follows:

 - start with the root node of the reference tree

 - traverse all of the children nodes recursively

 - for every node encountered, add the node's mutations to a set (think of this set as a set of "public mutations")

 - when evaluating the encountered reference node for fitness ("distance") relative to the analyzed sequence:
   - make a set of all mutations in the analyzed sequence in a set

   - subtract previously gathered "public" mutations from it (set difference operation)

   - the result of the difference will be the set of private mutations


The number of private mutations show how much changes appeared after the sequence branched-out its genome from the node. Number of private mutations (among other things) affects the distance metric on which we base the decision which reference node is the "nearest". Indeed, if there are few private mutations relative to a node, the sequence belong more to this node, compared to a node for which the sequence has more private mutations. 

Additionally, if there's too many private mutations in a sequence, we might suspect sequencing errors or other mistakes. This is reflected in the Quality Control (QC) score and status that we assign for every analyzed sequence.

The CSV, TSV and JSON exports contain:

 - `qc.privateMutations.total` is the total number of private mutations
 - `qc.privateMutations.total` is the total number of private mutations, computed as explained above
 - `qc.privateMutations.cutoff` and  `qc.privateMutations.excess` are the parameters that were used to calculate the `qc.privateMutations.score` (how much is "too many"). You can find the default values here: 
https://github.com/nextstrain/nextclade/blob/088c5cee0d87586cfcd86924b04d46e9db8548d2/packages/web/src/algorithms/defaults/sars-cov-2/qcRulesConfig.ts#L4-L8
 - `qc.privateMutations.score` is the score that we assigned for this particular QC metric, based on the numbers above
 - `qc.privateMutations.status` is the rough status of this metric (good/mediocre/bad), based on the score

Soon we might add a page with a little write up, that will explain this and other components of Nextclade's algorithms.

I hope it clarifies this for you. Let us know if you have more questions.

**Comment by tjbutler003** [comment]
Hi @ivan-aksamentov thank you very much for the clarification, that makes sense now!
I wanted to ask a follow up question of how the determination of "too many" private mutations was determined? My data analysis will be looking at the location of mutations using the reference sequence as compared to various genomic features, so I am trying to make sure that I have a justification especially for removing sequences that appear to have a lot of mutations.

**Comment by ivan-aksamentov** [comment]
> how the determination of "too many" private mutations was determined? Was that based on some sort of empirical rule?

Yes, the default QC parameters are empirical.

Note that Nextclade web application allows setting custom QC parameters in "QC Settings" dialog accessible with "Settings" button on results page.

And the command-line version of Nextclade has `--input-qc-config` flag to set these in JSON format.

**Comment by TYMichaelsen** [comment]
Was just looking for an explanation on the same columns, awesome! @ivan-aksamentov when will there be a elaborate explanation of all the columns of nextclade output available, as mentioned above?

**Comment by ivan-aksamentov** [comment]
@TYMichaelsen I am sorry, no ETA yet. I admit, our documentation is lagging behind.

If someone else stumbles upon this, contributions are super welcome.

**Comment by TYMichaelsen** [comment]
@ivan-aksamentov no problem - guess you are super-busy like the rest of us!

**Comment by ivan-aksamentov** [comment]
For anyone who stumbled across this thread, these points should have been explained in the documentation now:
 - https://docs.nextstrain.org/projects/nextclade

There might be still unclear parts and missing information there. In this case, please reach out with questions by either:
 - creating a new issue: https://github.com/nextstrain/nextclade/issues/new/choose
 - opening a discussion on the forum: https://discussion.nextstrain.org/

For project maintainers it is not always easy to find points users struggle with. We are grateful for any improvements to the documentation. If you found a dark spot, please submit an issue or a pull request to the `docs/` directory:
 - https://github.com/nextstrain/nextclade/blob/master/docs/README.md
