### ISSUE TITLE
Web based nextclade calling too many variants

### ISSUE THREAD

**Issue by staciawyman** [nextstrain/nextclade#285]
Hi Nextclade Folks,
I submitted sequences to the webtool this morning and it is giving huge numbers of mutations for some genomes. I'm attaching 
a fasta files here for one genome where it says there are 102 mutations, but iVar only calls 15. Is it calling N's as mutations?
Thanks,
Stacia
[SC2013_IGI-1005.fa.txt](https://github.com/nextstrain/nextclade/files/5752096/SC2013_IGI-1005.fa.txt)

**Comment by rneher** [comment]
Thanks for flagging this, Stacia. nextclade seems to be thrown off by the string of `N` at the beginning of the sequence.`N` aren't counted as mutations, but somehow the banded alignment seems to go astray when the sequence starts with lots of `N`s. We'll investigate.

**Comment by ivan-aksamentov** [comment]
@staciawyman The [fix](https://github.com/nextstrain/nextclade/pull/286) is released in version 0.10.1. It will be live [in a few minutes](https://travis-ci.com/github/nextstrain/nextclade/builds/211315028).
