### ISSUE TITLE
Extreme missing data

### ISSUE THREAD

**Issue by staciawyman** [nextstrain/nextclade#288]
Hi nextclade folks,
Perhaps I should not be putting such garbage "genomes" into nextclade, but it does seem like nextclade should not let these pass the quality checks. 
![garbage](https://user-images.githubusercontent.com/31453684/103386013-b1f19b00-4ab1-11eb-89ae-74fbecbc20c6.jpg)

**Comment by rneher** [comment]
Hi Stacia,

what exactly did you submit here. A sequence that is basically just `N`? We now trim `N` from the ends before aligning. maybe we should add them back so that they are counted and displayed. But my thinking was that terminal `N`s are essentially just missing data.

**Comment by staciawyman** [comment]
Sorry, I should have been clearer. This was a batch of very high Ct samples and so there was no genome recovered for some of them--and had just 1 locus with reads (likely contamination I suspect). I didn't prune out the no-genome samples and just submitted the whole run to nextclade. Here is what the actual sequence was for the top of the two samples:  
`>hCov-19/USA/CA-IGI-0776.1/2020
CACATAAACGAACTTATGGATTTGTTTATGAGAATCTTCACAATTGGAAC
TGTAACTTTGAAGCAAGGTGAAATCAAGGATGCTACTCCTTCAGATTTTG
TTCGCGCTACTGCAACGATACCGATACAAGCCTCACTCCCTTTCGGATGG
CNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN`
 
And the second one was a *lot* of N's followed by:
`NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNATAATACAGATTTTTCCAGAGTTAGTGCTAAACCACGCGCGGAGAT
CAATTTAAACACCTCANNNNNNNNNNNNNNNNNNNNNNTCCTTGGAATGT
AGTGCGTATAAAGATTGTACAAATGTTAAGTGACACACTTAAAAATCTCT
CTGACAGAGTCGTATTTGTCTTATGGGCACATGGCTTTGAGTTGACATCT
ATGAAGTATTTTGTAAAAATAGGACCTGANNNNNNNNN` 

I filed this as a feature request since it's not technically doing anything wrong, but I would like to see these colored red. 
Thanks!
Stacia

**Comment by rneher** [comment]
Thanks, Stacia. This makes sense. Basically you are proposing to handle

`(first 10kb not sequenced) ACTGGTG....ACTCT (last xkb not sequenced)`

differently from 

`(lots of N...) ACTGGTG....ACTCT (lots of N)`

The question then boils down to whether terminal `N`s are interpreted as "there should be smth here, so this is bad" vs "not part of the that data". I see that the former makes sense. We would need to memorize that the terminal `N`s we trim and add them back. 

best,
richard
