### ISSUE TITLE
Seems to have a bug

### ISSUE THREAD

**Issue by sium007** [nextstrain/nextclade#290]
Hi,

I faced an issue today. While using the Nextclade, one of my 565 sequences (hCoV-19/Bangladesh/DNAS-CPH-467/2020|EPI_ISL_445213) showed more than 500 mutations and the tree structure was weird. Which is not likely to be happened. I used 538 sequences including that sequence and ran on Nextclade before, but that time it was okay and showed 16 mutations only.

Please find all the documents in [this file](https://drive.google.com/drive/folders/16fad5onoLX4X64g4f_TVXDUpscuz2GkU?usp=sharing). Hope you will fix the problem soon. 
![Screenshot from 2021-01-05 11-11-26](https://user-images.githubusercontent.com/52605249/103610878-4c872980-4f4b-11eb-9e75-d720ea38863e.png)

Lastly, thank you so much for all your efforts. You are doing really great. Keep going.  

Regards,
Syed Muktadir Al Sium
Child Health Research Foundation, Dhaka, Bangladesh
email: sium.muktadir@gmail.com or sium.muktadir@chrfbd.org

**Comment by ivan-aksamentov** [comment]
Hi @sium007,
Thank you for the report and for your kind words!
We will try to investigate what's happened here.

**Comment by rneher** [comment]
This is hopefully fixed in 0.11.0 with PR #291 

@sium007: let us know if you encounter other weird cases. Such reports are very useful.
