### ISSUE TITLE
argument for clade definition file wanted

### ISSUE THREAD

**Issue by TYMichaelsen** [nextstrain/nextclade#294]
Hi Nextclade team,

We are actively using nextclade to monitor the V501.V1/B.1.1.7 development in DK - so your software is being used directly by the government to make policy decisions! Awesome tool!

Would it be possible to more dynamically assign clades using nextclade by adding an argument to use a specific clade .tsv file? I think of something similar to `augur clades` and the `--clades` argument. That will enable us to faster lookup new variants and build upon the work of others.

**Comment by rneher** [comment]
Hi Thomas,

the clade assignment is deducted from the phylogenetic placement. So if the tree you use has the clades you want, it will assign those. `nextclade` doesn't actually use the `clades.tsv` directly (we used to, but assignment through phylo placement is more stable). This tree could be a regular augur export, but we don't use the time scaling in nextclade. So you can speed up this calculation by using this profile

https://github.com/nextstrain/nextclade/tree/master/packages/web/tools/augur_profile

there are however a few undocumented quirks. This profile expects to be symlinked inside a `ncov` repo as `clades_profile` and it is using a rule that is not part of the main branch of `ncov`. I am running this from this fork of the ncov repo:

https://github.com/neherlab/ncov-europe

best,
richard

**Comment by TYMichaelsen** [comment]
Hi Richard,
Thanks for quick reply!
I see. I'm not familiar with snakemake, could you specify how exactly this speed-up is made? Are you just using a regular phylogenetic tree? The bottleneck for us running the "standard" nextstrain pipeline is the timetree step. 

PS: we do have snakemake people in-house, so whatever you already made should be possible to implement for us ;) 

Best,
Thomas

**Comment by rneher** [comment]
yes, the timetree step is the slowest, at least for large trees. This switches it off:

https://github.com/nextstrain/nextclade/blob/master/packages/web/tools/augur_profile/builds.yaml#L27
