### ISSUE TITLE
Seq indexing issue for B.1.1.7 deletion S:HV69-70?

### ISSUE THREAD

**Issue by SarahNadeau** [nextstrain/nextclade#298]
Nextclade seem to report "S:V70X" instead of the expected deletion "S:V70-" for the second of a 20-amino acid deletion found in the pangolin B.1.1.7 lineage. Could there be some sort of indexing bug here? The deletion is nucleotide positions 21765-21770, amino acids HV 69-70 deletion, reported [here](https://virological.org/t/preliminary-genomic-characterisation-of-an-emergent-sars-cov-2-lineage-in-the-uk-defined-by-a-novel-set-of-spike-mutations/563).

[example_alignment.txt](https://github.com/nextstrain/nextclade/files/5815114/example_alignment.txt)
is an example alignment of some sequences from the B.1.1.7 lineage.
The sequences have nucleotides "------" at positions 21765-21770 (aligned to reference Wuhan-Hu-1, aka GenBank  MN908947.3). 
However, the nextclade csv output reports a deletion at positions 21766-21772 and amino acid changes S:I68X,S:V70X,S:H69-.
I would expect the nextclade output to report S:H69- and S:H70- instead.

Any explanation or help would be really appreciated!

**Comment by rneher** [comment]
this deletion is out-of-frame generating too partial codons and one fully deleted one. The two partial ones conspire to a valid amino acid. but nextclade doesn't handle this properly atm.

**Comment by SarahNadeau** [comment]
Ooof, that's a tricky case that I hadn't imagined. Would the correct handling then be that for out-of-frame deletions with multiple-of-three length, the first codon is kept and the last one has been deleted (even though some bases from the first codon are deleted and some from the last codon are retained)?

**Comment by ivan-aksamentov** [comment]
@SarahNadeau This has been resolved in https://github.com/nextstrain/nextclade/pull/308 and is released in version 0.12.0, which will [go live in a few minutes](https://travis-ci.com/github/nextstrain/nextclade/builds/213951645). Don't hesitate to open a new issue if the problem persists.
