### ISSUE TITLE
S:Y144 (21994-21997) deletion not reported

### ISSUE THREAD

**Issue by bede** [nextstrain/nextclade#299]
**Current Behavior**
SARS-COV-2 S:Y144 deletion is missing from the `aaDeletions` column of results.tsv and from the Nextclade web interface when a B.1.1.7 sequence is uploaded.

**Expected behavior**
Where present, Y144 deletion should appear in the aaDeletions field of results.tsv and results.json, and be annotated by the Nextclade web interface

**How to reproduce**
Steps to reproduce the current behavior:
1. Either upload a [S:Y144 deletion genome](https://www.dropbox.com/s/drv5snl8sbrtluz/tst.fa?dl=1) to the Nextclade web interface or analyse using the Nextstrain docker image. Aligned or unaligned does not seem to make a difference.
2. `aaDeletions` in results does not contain 144 deletion, and web interface shows `Aminoacid deletions (0)` although both do report missing 21994-21997

[Screenshot](https://www.dropbox.com/s/bla8u15bxk7jpw3/nextclade.png?dl=0)

**Your environment:**
 - Firefox 84.01 (Mac) 2021-01-14
 - Docker image from 2021-01-13

**Comment by rneher** [comment]
thanks for flagging this. The problem here is that the alignment currently implemented in nextclade doesn't put this deletion at the beginning of a codon. Instead, codons 143 and 144 are partially deleted, both of which then are translated as `X`. We are working on fixing this.

**Comment by ivan-aksamentov** [comment]
@bede This has been resolved in https://github.com/nextstrain/nextclade/pull/308 and is released in version 0.12.0, which will [go live in a few minutes](https://travis-ci.com/github/nextstrain/nextclade/builds/213951645). Don't hesitate to open a new issue if the problem persists.

**Comment by bede** [comment]
Great work!
