### ISSUE TITLE
ENH: List instead of merely counting private mutations

### ISSUE THREAD

**Issue by proychou** [nextstrain/nextclade#302]
Nextclade lets users know how many private mutations are in a sequence but it would be great if it could generate a list of these private mutations. This could be either flagging them in the list of changes with a * or (P), or listing them separately a new column of the csv report. 

_Why is this useful?_
Number of private mutations and mutation clusters are both really helpful QC metrics that tell us about sequence quality and flag potential errors. Private mutations and clusters can sometimes be due to issues with trimming or quality issues at the ends of reads combined with low coverage at these sites leading to them being called in consensus. Having a list of where these private mutations (and maybe also mutation clusters) are will help us to go back to the bams or vcfs, review read support for each mutation, determine whether they are real and clean up the sequence.

**Comment by rneher** [comment]
Thanks, Pavitra! I like this suggestion and it should be pretty straightforward to implement.

**Comment by GonzaloYebra** [comment]
Hey Richard! Sorry to jump in, but is this feature implemented in the web version? It would be great being able to get the list of private mutations.

Thanks for a super helpful tool!

Gonzalo

**Comment by emmahodcroft** [comment]
@GonzaloYebra !!!!!! 😁 It is lovely to see you, even if it's on a github issue thread! 🙃

**Comment by GonzaloYebra** [comment]
Haha likewise Emma! Any little corner would do in this day and age :P

**Comment by corneliusroemer** [comment]
@proychou We've implemented this for a while now - both in web as well as in the TSV export

<img width="625" alt="image" src="https://user-images.githubusercontent.com/25161793/189883335-97d9163e-d08f-4d0f-afc8-a822c92e5183.png">

![Uploading image.png…]()

Thanks for the idea!
