### ISSUE TITLE
Error in annotating frameshift at the end of ORF8 (previously: "X" in amino acid substitutions)

### ISSUE THREAD

**Issue by iskandr** [nextstrain/nextclade#303]
Sorry this is a repost from the Nextstrain discussion site, but since it's specific to Nextclade, this might be a more appropriate venue. 

I just ran a collection of samples through the Nextclade web interface and one of the recurrent mutations is “ORF8:I121X”. I assume this isn’t a nonsense mutation, since those appear to be annotated like “ORF14:Q46*”. However, there is also an (empty) deletions columns, so I’m guessing the “X” doesn’t mean deleted. So what does it mean?

Thanks,
Alex

**Comment by iskandr** [comment]
Looking through the Nextclade source code I've found that this "amino acid unknown" from an error in translation.

**Comment by iskandr** [comment]
Also, suspiciously -- every sample with the ORF8:I121X annotation has a deletion at genomic position 28254. 

Is Nextclade not able to correctly translate frameshifts?

**Comment by iskandr** [comment]
From looking at the SARS-CoV-2 genome browser it looks like position 28254 corresponds to the last codon (121) of ORF8 before the stop. The deletion frameshifts the isoleucine-stop into S-K-R...

**Comment by rneher** [comment]
yes, nextclade doesn't deal with frame-shifts or out-of-frame deletions very gracefully atm. We are hoping to fix this soon, but it requires some bigger rearrangements.

**Comment by iskandr** [comment]
One simple band-aid might be to check codon length when annotating the alt
amino acid and emit "fs" instead of "X" if it's not a multiple of 3.

I can make that into a PR if you all are interested.

**Comment by ivan-aksamentov** [comment]
@iskandr This has been resolved in https://github.com/nextstrain/nextclade/pull/308 and is released in version 0.12.0, which will [go live in a few minutes](https://travis-ci.com/github/nextstrain/nextclade/builds/213951645). Don't hesitate to open a new issue if the problem persists.

**Comment by iskandr** [comment]
Thanks!
