### ISSUE TITLE
Annotation of insertions and deletions doesn't seem right

### ISSUE THREAD

**Issue by iskandr** [nextstrain/nextclade#305]
I'm looking at 15 samples which contain the following indel mutations

Deletions:
* 28254
* 21-23

Insertions:
* 21639:C
* 8114:G

Somehow there are no reported amino acid deletions or insertions. I checked one of the variants manually (del28254) and it's a frameshift in ORF8 but gets annotated as a substitution to "X". The others don't have an obvious corresponding substitution.  

Related: https://github.com/nextstrain/nextclade/issues/303

**Comment by ivan-aksamentov** [comment]
@iskandr This has been resolved in https://github.com/nextstrain/nextclade/pull/308 and is released in version 0.12.0, which will [go live in a few minutes](https://travis-ci.com/github/nextstrain/nextclade/builds/213951645). Don't hesitate to open a new issue if the problem persists.
