### ISSUE TITLE
Accuracy of assign_clades.py 

### ISSUE THREAD

**Issue by XubCherif** [nextstrain/nextclade#307]
assign_clades.py python script in ncov repo don’t work properly.

**Comment by ivan-aksamentov** [comment]
Hi @XubCherif this script is out of date and is not supported. We should probably remove it. How did you learn about it? If there's a documentation section about it, we shouldp probably remove that too.

The recommended way to run Nextclade locally is to use the official command-line tool NPM package, or a Docker container:

https://github.com/nextstrain/nextclade/blob/master/packages/cli/README.md
https://www.npmjs.com/package/@neherlab/nextclade
https://hub.docker.com/r/neherlab/nextclade

Alternatively, if you need user interface, you could build and run Nextclade web version locally as described in Developer's guide:
https://github.com/nextstrain/nextclade/blob/master/README.md#%EF%B8%8F-developers-guide

**Comment by XubCherif** [comment]
Hi Ivan thank you so much, I cloned ncov repo yesterday and it includes assign_clades.py (it worked for me before and now you confirmed it is outdated). 
NPM works well. 
PS: By mistakes, I deleted some part of my first comment

**Comment by ivan-aksamentov** [comment]
@XubCherif 
> assign_clades.py (it worked for me before and now you confirmed it is outdated)

I was confused. I'm not sure whether the file in `assign_clades.py` in `ncov` is outdated or not. I was referring to the file with the same name in `nextclade` repo, but we removed it some time ago.

**Comment by ivan-aksamentov** [comment]
I will close this. But don't hesitate to comment or to open another issue if there are still problems.
