### ISSUE TITLE
Issue running yarn dev on Windows 10

### ISSUE THREAD

**Issue by asharonbaltazar** [nextstrain/nextclade#313]
Hello there! I'm trying to contribute a little to your project, but for some reason, the script (`yarn dev`) provided in the `Readme` doesn't work. I'm running it in `nextclade/packages/web`. This is the error I'm getting:
![image](https://user-images.githubusercontent.com/58940073/105735124-f6c5f180-5ef8-11eb-8640-8b8999bfea63.png)

I believe this is an issue with Windows. Can someone confirm? 

Thank you in advance.

**Comment by ivan-aksamentov** [comment]
Hi @asharonbaltazar,

Thanks for trying!

I am not aware of anyone developing on Windows unfortunately.
It is strange that the Next.js script contains Linux-specific bash code on Windows. We have `node_modules/.bin/next` hardcoded, but maybe it meanto run another file on windows?

Maybe you will have better luck with a Unix environment? For example with [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) or, Docker.

We have a little [docker-compose file](https://github.com/nextstrain/nextclade/blob/master/packages/web/docker/docker-compose.dev.yml) (you can remove [this part](https://github.com/nextstrain/nextclade/blob/7f9a327d528fe93c77357d40bfe3e8cd7f1e91d3/packages/web/docker/docker-compose.dev.yml#L25-L32), it's optional)

**Comment by ivan-aksamentov** [comment]
@asharonbaltazar We had the same problem in another repo and one of our contributors fond a solution here: https://github.com/hodcroftlab/covariants/pull/71

Feel free to try it out and let us know if that works for you. And if it does, don't hesitate to send a pull request if you have time.

**Comment by asharonbaltazar** [comment]
Thanks for the mention! I'll give it a try.
