### ISSUE TITLE
amino acid insertions

### ISSUE THREAD

**Issue by proychou** [nextstrain/nextclade#319]
Insertions are only shown at nucleotide level, i.e. there's no aaInsertions column.

**Comment by rneher** [comment]
True, we currently don't translate insertions. We could add this, but I am not sure how strong the use case is for that. In any case, this is probably something we would look into after we finished some major changes we are doing a the moment.

**Comment by fritzo** [comment]
@rneher thanks for creating this great tool!  Do you know how much effort it would be to add an `aaInsertions` column?  I'm not sure exactly how to extract that information directly, and I would like to search among amino-acid-level insertions.

Is there something unusual about insertions that makes them difficult to represent, e.g. is it more common e.g. for insertions to be coupled with substitution as in `A -> GP`?  Thanks!

**Comment by proychou** [comment]
Yes, would be great to include, especially in light of variants like 21H/1.621
https://covariants.org/variants/21H
Thanks!

**Comment by RaverJay** [comment]
Bumping this, as it's very relevant now for Omicron with its S:R214REPE insertion.

Please add this asap =)

Thanks and best wishes!

**Comment by ivan-aksamentov** [comment]
@proychou @fritzo @RaverJay,

Hi folks, 

We have released a new version of Nextclade (web 1.13.0, cli 1.10.0), which now displays and outputs aminoacid insertions. Better late then never, right? ;)

**Comment by RaverJay** [comment]
Thanks Ivan! We are already very ready for this release :D
Best wishes
