### ISSUE TITLE
expected .csv format for primer files?

### ISSUE THREAD

**Issue by dannydesloover2** [nextstrain/nextclade#333]
Is there a template or document that details the expected input formatting for a custom primer file (".csv" file) ?

is it expected in .bed format, 5'->3'  fasta? 
Expected columns or header? 
An example in the documentation or webapp would be great!

**Comment by ivan-aksamentov** [comment]
Hi @dannydesloover2, 

You could use the default `pcrPrimers.csv` file as a reference. It is  in:
[packages/web/src/algorithms/defaults/sars-cov-2/pcrPrimers.csv](https://github.com/nextstrain/nextclade/blob/fc12af4c3a3d414763f4db1f15ef13ea076bebb9/packages/web/src/algorithms/defaults/sars-cov-2/pcrPrimers.csv)
