### ISSUE TITLE
Support uploading multiple FASTA files (not just one FASTA file contains multiple genomes)

### ISSUE THREAD

**Issue by xzhub** [nextstrain/nextclade#342]
It would be good to have a feature to allow users to upload multiple genome files. In the backend, we can just cat these uploaded files together before the analysis. 

It's useful because in many cases we download sequence files here and there, and sometimes we have our own assembled genome files for each different strain one by one. It's inconvienient in Windows to concatenate these files into one mutli-entry FASTA file, therefore this feature could be very useful in my opinion.

**Comment by corneliusroemer** [comment]
Someone else asked for this on our nextstrain forum.

Would be cool if we could get this at some point :) 

https://discussion.nextstrain.org/t/upload-more-than-one-fasta-on-nexclade-web/1070
