### ISSUE TITLE
How is calculate qc.overallScore in Nexclade output

### ISSUE THREAD

**Issue by nbargues** [nextstrain/nextclade#355]
I didn’t found a proper documentation that explain how each result in the nexclade output is generated and what it represent ?

Specifically the parameters qc.overallScore and qc.overallStatus.

Can someone please paste me the link to this documentation (or explain me those parameters) ?

Cheers

**Comment by ivan-aksamentov** [comment]
Hi @nbargues,

Great question!

> documentation

Unfortunately it does not exist yet. But hopefully soon!


If you can follow some simple javascript, here is the implementation of the entire QC part:

https://github.com/nextstrain/nextclade/tree/62a127780647ecd9a0f351e61f01f8b81f1237b8/packages/web/src/algorithms/QC

Basically, there are 4 rules (each rule manifests itself as a circle in the web interface on results page). The rules are implemented as functions, and each calculates a score, based on the analysis results and some rule-specific parameters.

Then the scores are added together as follows:

https://github.com/nextstrain/nextclade/blob/62a127780647ecd9a0f351e61f01f8b81f1237b8/packages/web/src/algorithms/QC/runQC.ts#L39

Basically, `overallScore = sum(score_i * score_i / 100)`.

Then status is defined as "bad" if the overallScore is above 100, "good" if overallScore is below 30, and "mediocre" if in between.

https://github.com/nextstrain/nextclade/blob/62a127780647ecd9a0f351e61f01f8b81f1237b8/packages/web/src/algorithms/QC/QCRuleStatus.ts#L7-L15


These are all relatively arbitrary empirical choices we've made over time, making sure it works well in practice. You should not worry too much about the exact values of these scores, but you can use the scores to compare quality of sequences between each other. If you think the QC is to strict or to lax for your purposes, you can enable and disable rules and tweak the rule-specific parameters using "Options" button, until you find a set of satisfactory parameters.

We also hope to add more rules later on.

Let us know how it works for you and if you have further questions or ideas. Don't hesitate to open new issues for new topics. We are also always glad to consider contributions to code and documentation.

**Comment by nbargues** [comment]
Thanks for the answer. 

I have another question about nexclade's output.

How to know the reliability of the assignment of the clade? If a sample is stamped "bad" we have to doubt its assignment?

Cheers

**Comment by rneher** [comment]
Hi @nbargues

the assignment of clades is done by finding the closest node and reporting the clade of that node. Reliability hence depends critically on how well the sample can be placed on the tree. In most cases, this is fairly unambiguous, but partial genomes might not be reliably placed. 

A bad sample doesn't necessarily mean it doesn't assign well. But long stretches of `N` will decrease reliability.
