### ISSUE TITLE
[Nextalign] Consider packaging and uploading to different package managers and container repos

### ISSUE THREAD

**Issue by ivan-aksamentov** [nextstrain/nextclade#357]
Despite Nextalign being a [single-file download](https://github.com/nextstrain/nextclade/releases), we might also consider packaging it for even simpler installation.

We might package for:
 - Conda
 - Homebrew
 - Various Linux distros with deb and rpm
 - Possibly various scientific package managers
 - Chocolatey, when Windows native binaries are available

What is your favorite package manager? Let us know.

We welcome community contributions in this area!

Related: #422

**Comment by cjw85** [comment]
Hi, I'm just considering creating a package for conda to go in bioconda.

I'll let you know how I get on.

**Comment by rneher** [comment]
@cjw85 We'd love to have this in bioconda!

**Comment by cjw85** [comment]
I've put nextalign for linux there using your binaries on the Github release page. This seems to be acceptable given the number of bioconda packages create with static binaries. There's a bit more work to do it for the macOS binaries.

**Comment by ivan-aksamentov** [comment]
@cjw85 Thanks!

Further we could use [selectors](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#preprocessing-selectors) to download files for different platforms (in conda terms that will be `linux64`, `osx` and `arm64`) and to use [destination directory and filename](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#destination-path) to keep the `build.sh` script platform-independent.

P.S. The package recipe is here if someone wants to try to add other platforms: https://github.com/bioconda/bioconda-recipes/tree/master/recipes/nextalign

**Comment by huddlej** [comment]
Thank you @cjw85 and @ivan-aksamentov! I've [added support for x86 OS X in a PR](https://github.com/bioconda/bioconda-recipes/pull/26919). If this goes through, I'll add support for arm64 OS X, too.

**Comment by Batsi-2015** [comment]
@ivan-aksamentov and @cjw85 is it possible to also have Nextclade on bioconda?

**Comment by cjw85** [comment]
For the time being we've (Oxford Nanopore Technologies) have added the nextclade node CLI to a custom conda channel: 

https://anaconda.org/epi2melabs/np-artic/

**Comment by ivan-aksamentov** [comment]
[Nextclade](https://anaconda.org/bioconda/nextclade) and [Nextalign](https://anaconda.org/bioconda/nextalign) are now semi-automatically released on bioconda (they still require manual approval for PRs).

This is additional to the main venues: [GitHub Releases](https://github.com/nextstrain/nextclade/releases) and [Docker](https://hub.docker.com/r/nextstrain/nextclade), as described in the documentation.

We will unlikely have resources to implement and maintain any additional packaging. But if someone in community wants to add other packaging automation [to our CI](https://github.com/nextstrain/nextclade/tree/master/.github/workflows), then we are happy to review your pull requests.

Feel free to comment, open issues and PRs as you see fit.
