### ISSUE TITLE
Nextclade and Nextstrain report different clades

### ISSUE THREAD

**Issue by Arash-Iranzadeh** [nextstrain/nextclade#362]
Hi,

We submitted a set of SARS-Cov2 assembled genomes to the Nextclade web interface, it assigned these samples to clade 20H/501Y.V2. However, when we downloaded the report file in the csv format we could not find S:N501Y mutation for almost half of samples assigned to clade 20H/501Y.V2. We ran the Nextstrain pipeline and found out that these samples were from clade 20C. Can you please advise? Why reported clades are different and which one is more reliable? 

Best regards,
Arash

**Comment by rneher** [comment]
Hi Arash-Iranzadeh,

thanks for filing the issue. This obviously shouldn't happen. Nextclade tries to infer clades by looking for close matches in the tree, the nextstrain augur pipeline uses a set of signature mutations. It is thus possible that there are discrepancies, but this obviously shouldn't be. Do you have some accession numbers of example genomes that cause this issue?

thanks again,
richard

**Comment by Arash-Iranzadeh** [comment]
Thanks Richard- Please check these sequences:
EPI_ISL_1040716
EPI_ISL_1040714
EPI_ISL_1040676
EPI_ISL_1040672
EPI_ISL_1040712
EPI_ISL_1040707
EPI_ISL_1040754
EPI_ISL_1040708
EPI_ISL_1040697
EPI_ISL_1040698
EPI_ISL_1040696
EPI_ISL_1040683
EPI_ISL_1040758
EPI_ISL_1040692
EPI_ISL_1040693
EPI_ISL_1040685
EPI_ISL_1040659
EPI_ISL_1040658
EPI_ISL_1040646
EPI_ISL_1040656
EPI_ISL_1040657
EPI_ISL_1040660
EPI_ISL_1040654
EPI_ISL_1040652
EPI_ISL_1040649
EPI_ISL_1040653
EPI_ISL_1040661
EPI_ISL_1040648
EPI_ISL_1040663
EPI_ISL_1040644
EPI_ISL_1040650
EPI_ISL_1040651
EPI_ISL_1040645

**Comment by Arash-Iranzadeh** [comment]
The next clade assigned some of these samples to 20H/501Y.V2 while they do not harbor the 501Y mutation, however, Nextstrain assigns them to the calde 20C.

**Comment by rneher** [comment]
I just ran them through nextclade, and it seems to me that the majority do have the 501Y mutation, but not all. Those without 501Y still have a number of other mutations that are signature mutations of V2. So nextclade assigns them to V2. Most sequences also have the PANGO lineage B.1.351, consistent with nextclade's annotation. 

but you are right that some sequences don't have all mutations, which likely makes the annotation a little shaky,

**Comment by rneher** [comment]
Here is  the nextclade output I get:
![image](https://user-images.githubusercontent.com/8379168/109183437-3a2cad80-778e-11eb-83f9-9c716f33b08c.png)

**Comment by Arash-Iranzadeh** [comment]
Thanks! My question is about the inconsistency between the Nextclade and Nextstrain outputs. In your figure all samples except 1 are from 20H/501Y.V2, but below is the output of the Nextstrain pipeline, several samples were assigned to 20C, it may be due to the algorithms that Nextclade and Nextstrain apply. My question is which output is more reliable?

![Screenshot from 2021-02-27 14-36-53](https://user-images.githubusercontent.com/26380396/109387315-720c3000-7909-11eb-80eb-81e2cac39143.png)

**Comment by rneher** [comment]
I see, Clade assignment in the nextstrain pipeline will only work if you have a diverse set of sequences in your analysis. Nextstrain finds clades by identifying signature mutations and if the there aren't enough sequences to pin down the overall structure of the tree, the clade designations will go astray.
