### ISSUE TITLE
Nextclade error: Cannot find module '/usr/lib/node_modules/@neherlab/nextclade/dist/worker.js

### ISSUE THREAD

**Issue by Batsi-2015** [nextstrain/nextclade#364]
Hi, 

I installed Nextclade using the following command: 'npm install --global @neherlab/nextclade'. When I do nextclade --h its showing that its working, but if i try to do an analysis e.g 'nextclade -i seqs.fa -c nextclade_results.csv' I get the error pasted below. I am running npm version 7.5.1 and node version 10.19.0 on Linux Ubuntu version 20.04. The docker version is working okay but wanted to install this version. Thank you in advance. 

`Node worker_threads not available. Trying to fall back to tiny-worker polyfill...
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/usr/lib/node_modules/@neherlab/nextclade/dist/worker.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Error: Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().
    at Timeout.setTimeout [as _onTimeout] (/usr/lib/node_modules/@neherlab/nextclade/dist/nextclade.js:934:2216)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)`

**Comment by rneher** [comment]
This is likely due to the old node-version. Do you by any chance install node via the nextstrain conda environment?

I would try and get node via 
https://github.com/nvm-sh/nvm

**Comment by tsibley** [comment]
Node.js 10.19.0 is [what's packaged in Ubuntu 20.04](https://packages.ubuntu.com/search?keywords=nodejs&searchon=names&suite=focal&section=all), so the Conda environment may not be implicated here.

@Batsi-2015 You'll need at least Node.js 12. The [Nextclade CLI README](https://github.com/nextstrain/nextclade/tree/master/packages/cli#locally) says:

> Nextclade CLI supports Node.js versions >= 12, version >= 14.15.0 LTS is recommended.

NVM, as @rneher recommended, is a good way to get alternate Node.js versions.

**Comment by tsibley** [comment]
Ah, and the Node.js version in use is installed into the `/usr` prefix, which indicates it's not Conda-managed.

I was surprised that `npm install` succeeded even though Nextclade CLI requires Node.js 12+, and indeed, the version compat was incorrect in its package metadata. I've [submitted a PR to fix](https://github.com/nextstrain/nextclade/pull/365).

**Comment by ivan-aksamentov** [comment]
Hi @Batsi-2015,

As Richard pointed out this is due to old version of Node.js. In our [local installation instructions](https://github.com/nextstrain/nextclade/tree/master/packages/cli#locally) we recommend NVM to manage Node versions. Using Node from Ubunty's repositories is almost never a good idea, as it is very old and requires root permissions to install packages.

You can also try our [docker container image](https://github.com/nextstrain/nextclade/tree/master/packages/cli#with-docker) if you don't want to juggle with Node versions. Container image already includes everything needed.

**Comment by rneher** [comment]
We no longer use `node` in the CLI. But let us know if you have any issues with newly released C++ version of nextclade.
