### ISSUE TITLE
Frame-preserving deletion reported in AA space as (incorrect) deletion + substitution 

### ISSUE THREAD

**Issue by acorvelo** [nextstrain/nextclade#366]
Hello,
Thank you for nextclade! I'm running v.0.13.0 (command-line) but the following issue also exists on the webtool. On a particular genome I have the following 12bp deletion:

`21984-21996`

which, from my understanding, should have been translated into:

`S:L141-,S:G142-,S:V143-,S:Y144-`

but it was instead translated into two different events:

`S:G142-,S:V143-,S:Y144-,S:Y145-` (which is shifted one position downstream) and `L141Y`.

It appears that nextclade is getting the wrong deletion position but at the same time "correcting it" by converting the first AA that should have been deleted into the last one that was erroneously deleted.

It would be great if this issue could be fixed. Many thanks

**Comment by rneher** [comment]
thanks for flagging it, I'll look into this. We currently have a somewhat adhoc way of fixing partial codons that we will hopefully resolve soon. But I'll add a fix for this soon.

**Comment by rneher** [comment]
thanks again. This should be fixed with the next release with commit

https://github.com/nextstrain/nextclade/commit/d266fa71da6cdc6549dbf2d873ee94d6326634bf

(and hopefully soon in a more comprehensive manner).

**Comment by ivan-aksamentov** [comment]
Should be fixed in Nextclade 0.14.0, which should be live shortly
