### ISSUE TITLE
'ERR_STRING_TOO_LONG' error with input FASTA file larger than ~500MB

### ISSUE THREAD

**Issue by matthuska** [nextstrain/nextclade#367]
When assigning clades to large (just > 500MB) multifasta file using the nextclade cli tool (version 0.13.0), I get the following error:

```
Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (node:buffer:592:37)
    at Buffer.toString (node:buffer:789:14)
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:23) {
  code: 'ERR_STRING_TOO_LONG'
}
```

This seems to be related to the maximum size of a buffer in nodejs. Maybe the sequences could be read in chunks to work around this issue.

**Comment by rneher** [comment]
yes, this is indeed a problem with the nodejs buffers that we will hopefully get around soon by porting much of this to C++. We currently chunk the input data with a simple bash script into chunks of about 1k sequences.

**Comment by ivan-aksamentov** [comment]
Hi @matthuska,

Sorry for this.

As it started as a very simple web application, we never thought Nextclade would need to process this much data. As Richard mentioned, we decided to not invest anymore into Node.js implementation, so this is wontfix unfortunately. We are porting Nextclade to C++ which will not have this problem.

We had the same problem in Nextstrain's main ingest pipeline and we have this hack while awaiting a better implementation:

https://github.com/nextstrain/ncov-ingest/blob/3ac7c2b2a76a417e4e7e2c2885f46db2427abb83/bin/run-nextclade

It also allows for better use of hardware concurrency and I/O.

Please try it out.

Don't hesitate to comment or open another issue if there are problems to resolve.

**Comment by TheBready** [comment]
Here are my lines for a quick fix from single line fasta to nextclade tsv. 
```
# remove duplicates by ID
awk '/^>/{f=!d[$1];d[$1]=1}f' in.fasta> dedup.fasta

# Single line to multi line fasta
fold -b80 dedup.fasta > multi.fasta

# Split in n parts
pyfasta split -n <n> multi.fasta

# Execute nextclade
find *.fasta | parallel nextclade --input-fasta {} --output-tsv {}.tsv --jobs <n>
```

Everything can be installed using conda.
