### ISSUE TITLE
🌍 Translation. We are looking for translators!

### ISSUE THREAD

**Issue by ivan-aksamentov** [nextstrain/nextclade#37]
We are looking to extend and improve our translations.

We are using `i18next` and `react-i18next` modules in the app.
The extraction of English strings is performed with `yarn i18n`.
The extracted strings are in [`packages/web/src/i18n/resources`](https://github.com/neherlab/webclades/tree/master/packages/web/src/i18n/resources)

We use GitLocalize service to perform the translation:

Step-by-step guide:
 - Register with GitLocalize, for example using your GitHub account: https://gitlocalize.com
 - Go to our GitLocalize repo: https://gitlocalize.com/repo/4819
 - Click a language name from the table (other than English)
 - Navigate to `packages web/src/i18n/resources/en/common.json` file or use these direct links for some of the languages:
    - ar: https://gitlocalize.com/repo/4819/ar/packages/web/src/i18n/resources/en/common.json
    - de: https://gitlocalize.com/repo/4819/de/packages/web/src/i18n/resources/en/common.json
    - es: https://gitlocalize.com/repo/4819/es/packages/web/src/i18n/resources/en/common.json
    - fr: https://gitlocalize.com/repo/4819/fr/packages/web/src/i18n/resources/en/common.json
    - it: https://gitlocalize.com/repo/4819/it/packages/web/src/i18n/resources/en/common.json
    - ko: https://gitlocalize.com/repo/4819/ko/packages/web/src/i18n/resources/en/common.json
    - pt: https://gitlocalize.com/repo/4819/pt/packages/web/src/i18n/resources/en/common.json
    - ru: https://gitlocalize.com/repo/4819/ru/packages/web/src/i18n/resources/en/common.json
    - zh: https://gitlocalize.com/repo/4819/zh/packages/web/src/i18n/resources/en/common.json

  If your language is missing, please write a message here and we will add it

 - Translate the strings: look at the string in the leftmost column of the table and write the translated result into the rightmost column. Do not modify names inside double braces `{{ }}` - these are used in the program to substitute values, such as numbers and other strings. These names could give you a hint as to what will be substituted. 
      Note, there might be multiple pages in this table (the pagination is in the bottom of the page)
      Note that there's a "Machine translation" button to get you started with some basics, but the most often automatic translation requires manual correction and rephrasing
 - After you are done, Click "Create review request"
 - If you have this capability, click "Create Pull Request" (otherwise write in this issue and one of the maintainers could grant you permissions)
 - GitLocalize will create the pull request with translated strings so that we can integrate them into the app in the next release

**Comment by stroudn1** [comment]
Happy to help with Spanish translation if needed! Thanks!

**Comment by ivan-aksamentov** [comment]
Hi @stroudn1, very much needed!

I extracted some fresh strings, so feel free to either use GitLocalize as described above
https://gitlocalize.com/repo/4819/es/packages/web/src/i18n/resources/en/common.json

or copy the English version to Spanish:
```
cp packages/web/src/i18n/resources/{en,es}/common.json 
```
translate, and submit in a PR.

I will now add Spanish and some other languages into the dropdown.

Thanks

**Comment by ivan-aksamentov** [comment]
Okay, I submitted machine translations for currently present languages.

**Comment by stroudn1** [comment]
Thank you for the info @ivan-aksamentov ! I had one question, for the string "Back", is this referring to back as in anatomy or back as in moving back or going back in a page?

I looked through GitLocate and the .json files and I didn't find any missing translations so I looked through what was translated and revised if needed. Please let me know if this is incorrect and if there are strings missing translations. Thanks!

**Comment by ivan-aksamentov** [comment]
@stroudn1  Yep, everything's  great. 

> or the string "Back", is this referring to back as in anatomy or back as in moving back or going back in a page?

back as in navigate to the previous page

Thanks a lot!

**Comment by stroudn1** [comment]
Sent a PR reflecting the correct meaning of 'back'. Thanks for the clarification! 

By the way, I love the concept of this project! Happy to do more Spanish translations whenever you need it, thank you!

**Comment by thewindsofwinter** [comment]
Hi, I'd be willing to do ZH translation at some point, I'm a bit busy rn but maybe in a few days?

**Comment by Fareysia** [comment]
Hello!

I'd love to do the German translation, if it's still needed. (:

**Comment by felix-khlmnn** [comment]
Hi there!
I corrected a few machine-made mistakes in German and sent a request on GitLocalize.

Some scientific terms might still need to be checked, but I don't have the expertise to do so.
Here's the link: https://gitlocalize.com/repo/4819/de/review/48381

**Comment by ammaraziz** [comment]
@ivan-aksamentov The above gitlocalize links are broken.

**Comment by ivan-aksamentov** [comment]
@ammaraziz True. Nobody really used it anyways. I'll close this issue.
