### ISSUE TITLE
Can I get gene position after alignment on Nextclade?

### ISSUE THREAD

**Issue by HuangGuna** [nextstrain/nextclade#370]
I want to know gene position like S gene in the sequences after aligning to the reference genome, can I get it from Nextalign?

**Comment by ivan-aksamentov** [comment]
Hi @HuangGuna,

The nextalign output strips insertions relative to the reference. The gene position in the query sequence is then the same as in the reference.

Therefore:
 - the position is the same as in the gene map that was used for the alignment
 - if you used our example gene map, you can find it here: [data/example/genemap.gff](https://github.com/nextstrain/nextclade/blob/master/data/example/genemap.gff)
 - if gene map was not used, but you used our example reference sequence, than, again, you can refer to the example gene map
 - if gene map was not used, and you used your own reference sequence, then the position will be the same as in your reference sequence (ask the source of your reference sequence for the  gene annotations)

Let me know if this solves the problem

**Comment by HuangGuna** [comment]
You suggest that I can get query gene regions by changing the refer gene sequence according to mutations which are called by Nextclade, do I understand that right? But I was confused by the symbol "X" in the amino acid sequence, like this:

I can't see these amino acid "X" in the export file of Nextclade web, but they are different from the reference genome in fact.
That's why I don't know how to acquire the geno region by nextclade. Can I get any help?





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ivan Aksamentov"<notifications@github.com&gt;; 
发送时间: 2021年3月8日(星期一) 晚上10:57
收件人: "nextstrain/nextclade"<nextclade@noreply.github.com&gt;; 
抄送: "白首太玄"<2609549366@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [nextstrain/nextclade] Can I get gene position after alignment on Nextclade? (#370)





 
Hi @HuangGuna,
 
The nextalign output strips insertions relative to the reference. The gene position in the query sequence is then the same as in the reference.
 
Therefore:
  
the position is the same as in the gene map that was used for the alignment
 
if you used our example gene map, you can find it here: data/example/genemap.gff
 
if gene map was not used, but you used our example reference sequence, than, again, you can refer to the example gene map
 
if gene map was not used, and you used your own reference sequence, then the position will be the same as in your reference sequence (ask the source of your reference sequence for the  gene annotations)
  
Let me know if this solves the problem

**Comment by ivan-aksamentov** [comment]
Hi @HuangGuna,

I am a bit confused. Are we talking about Nextclade or Nextalign?

Nextclade does not output sequences or genes, which makes me even more confused.

I cannot see your aminoacid example, I am sorry. Please try to reply in GitHub thread, rather than in email:
https://github.com/nextstrain/nextclade/issues/370

Could you please explain:
 - what you are running
 - what data and parameters you use
 - what results you see
 - what results you want to see
?

**Comment by rneher** [comment]
@HuangGuna , the tool now allows download of translations of all genes. The regions are defined in the genome annotation used in nextstrains builds 

https://github.com/nextstrain/ncov/blob/master/defaults/annotation.gff
