### ISSUE TITLE
 --output-tsv-clades-only does not produce any output

### ISSUE THREAD

**Issue by stefandiederich** [nextstrain/nextclade#373]
Hi, 
I am using nextclade version 0.14.0 and tried to get only the clade output with ` --output-tsv-clades-only`, but did not get any file output. 

The command I used was: `nextclade -i /media/Berechnungen/COVID/Run1/Run1.consensus.fa --output-tsv-clades-only /media/Berechnungen/COVID/Run1/nextclade/Clades.csv`

Did I do something wrong?

Bests Stefan

**Comment by ivan-aksamentov** [comment]
Hi @stefandiederich , 

Thanks for the report and sorry you experiencing this.

Indeed, I can confirm that there is no output produced. `--output-tsv-clades-only` was an internal flag for some time, for our pipelines, but it is no longer used and we might remove it. Use `--output-tsv` instead. It produces the same output in the `clade` column and some more.

**Comment by stefandiederich** [comment]
Hi @ivan-aksamentov ,

dont worry :-) I will use the tsv output instead.
Thanks for your quick reply!

Bests 
Stefan
