### ISSUE TITLE
Allow for compressed file streaming and reading from stdin

### ISSUE THREAD

**Issue by ivan-aksamentov** [nextstrain/nextclade#376]
We want Nextalign to be able to read the data from stdin, as well as in compressed file formats (which ones?), whether from stdin or from file. This is useful for integration into pipelines that use compressed formats, and to avoid disk I/O.

**Comment by huddlej** [comment]
For our future reference, [reading from stdin already works nicely for nextalign](https://github.com/nextstrain/ncov/blob/cceb3a1a7097f32f8d487d48086164d00d1a4689/workflow/snakemake_rules/main_workflow.smk#L78-L83).

**Comment by ivan-aksamentov** [comment]
Implemented in https://github.com/nextstrain/nextclade/pull/847, https://github.com/nextstrain/nextclade/pull/880, https://github.com/nextstrain/nextclade/pull/892, https://github.com/nextstrain/nextclade/pull/1029 and others.

See the docs on inputs/outputs and `nextclade run --help` or `nextaling run --help`.
