### ISSUE TITLE
Nucleotide deletion ranges have an extra site tacked on

### ISSUE THREAD

**Issue by alh321** [nextstrain/nextclade#377]
e.g., EPI_ISL_777976, which has a 3bp deletion from 22345-22347, is reported as having a deletion from 22344-22347

**Comment by rneher** [comment]
Thanks for flagging this. This is likely an inconsistent use of 0 or 1 based numbering conventions. We'll look into it.

**Comment by rneher** [comment]
This should be fixed in the new version. But thanks again for flagging!
