### ISSUE TITLE
Nucleotide position of amino acid change

### ISSUE THREAD

**Issue by jsan4christ** [nextstrain/nextclade#380]
Hello,

I use nextclade quite heavily, thanks for such a great tool. 

One thing I need to be able to do is have a mapping of the position of the nucleotide change to the amino acid. This is complicated by the fact that in the substitutions column, not all substitutions will result in aasubstitutions thus position and order may not be preserved.  Is there any way to get the genomic position of the aaSubstitution? e.g G204R at position 28883 or G28883C?

That would be super helpful

**Comment by rneher** [comment]
For simple substitutions, this would be possible and is done internally (if you mouse over a mutation in the web interface, it will tell you the associated amino acid mutations). But it is not always unique. There might for example be two mutations in a codon and only together they result in the specific amino acid substitution. For deletions this can also get a little bit more complicated. 

Do you suggest to include such a mapping in the output? Or do you simply want a procedure how to connect them?

**Comment by jsan4christ** [comment]
Thanks Richard for the prompt response, great tip for web interface, however, I need it more for the csv which I export further downstream analysis. I also use find the cli quite useful for integration with other tools/pipelines. Including the mapping in the output csv would be super helpful. A procedure on how to connect them would equally be appreciated.

Thanks

**Comment by rneher** [comment]
For each nucleotide substitution, you can 

 * find the gene this substitution falls into (sometimes these are several)
 * subtract the start of the gene from the position of the nucleotide
 * divide that difference by 3
-> this should give you the codon. If the amino acid this codon codes for changes, this will likely be the amino acid substitution you are looking for. 

you can find beginning and end of genes here:

**Comment by jsan4christ** [comment]
That is what I have been doing but sometimes you are off by 1 or 2,
depending on position in the codon that the change is. I. E. Second or
third position. I would like to be able to get the precise position.

Thanks

**Comment by rneher** [comment]
In the new version, each amino acid substitution reports its "context" in the nucleotide sequence in the tool tip. This isn't exported to the `csv` output, but is part of the `json` output.

**Comment by jsan4christ** [comment]
Thanks for following up, super helpful feature
