### ISSUE TITLE
Gaps at unexpected indices

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/nextclade#382]
When viewing B.1.1.7 and B.1.351 sequences via [clades.nextstrain.org](https://clades.nextstrain.org/) (v0.14.1), some of the expected deletions are reported at unexpected indices:

**B.1.1.7**

|Expected Deletions| Reported Deletions|
|--------------| --------------|
|21765–21770  | 21766-21772 |
|21991–21993  | 21994-21997|

**B.1.351:**
|Expected Deletions| Reported Deletions|
|--------------| --------------|
|22282–22290  | 22287-22296 |

**Comment by rneher** [comment]
Thanks, Jover!

I think there are two issues here: one is whether we report the deletions as open or closed intervals. 

The other is how we want to report ambiguous gaps. I only had a quick look, but I think in the cases you highlight, repeated sequence means that the gap placing is actually ambiguous.

![image](https://user-images.githubusercontent.com/8379168/111452240-9aba6500-8712-11eb-8611-bb51160a87e4.png)

![image](https://user-images.githubusercontent.com/8379168/111452402-c6d5e600-8712-11eb-8c07-19be53b0ddb5.png)

**Comment by rneher** [comment]
With the new alignment, this should be addressed.
