### ISSUE TITLE
How to Update with npm

### ISSUE THREAD

**Issue by stefandiederich** [nextstrain/nextclade#383]
Dear all, 

I am searching for a way to update my nextclade installation with npm. 
I tried to install it directly with `sudo npm install --global @nextstrain/nextclade@0.14.1` or by `sudo npm update -g nextclade`, but i did not get it the new version. Its still the old Version 0.14.0.

Bests 
Stefan

**Comment by ivan-aksamentov** [comment]
@stefandiederich I cannot tell for sure what is happening here. Could it be that you are using multiple Node.js installations and the one you are updating is not the same that comes first in your `$PATH`?

I am afraid that this is not Nextclade's problem, but rather a problem with your computer setup. Happily, we provide docker container images, so if you don't want to tinker with Node.js, you could just install Docker and run Nextclade in a container.

In any case, make sure you follow our [Getting Started Guide](https://github.com/nextstrain/nextclade/tree/master/packages/cli#getting-started)

Additionally, we discourage using Node.js provided by the operating system, and, especially, running any Node.js scripts as a superuser. OS-packaged Node.js is probably very old and Nextclade won't run on in anyways, and running any code from NPM as root is just wildly insecure.

**Comment by stefandiederich** [comment]
@ivan-aksamentov 
Thanks for your reply!I will go for the Docker installation for the next releases.
Bests
Stefan
