### ISSUE TITLE
ERR_STRING_TOO_LONG

### ISSUE THREAD

**Issue by marcadella** [nextstrain/nextclade#384]
```
Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (buffer.js:608:37)
    at Buffer.toString (buffer.js:805:14)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:58:23) {
  code: 'ERR_STRING_TOO_LONG'
}
```
0x1fffffe8 translates to roughly 500MB. Would be nice to not have this limitation.

**Comment by rneher** [comment]
this is a problem with the maximal buffer size of node js and the absence of proper streaming. We are working on a fix/replacement for this.

**Comment by ivan-aksamentov** [comment]
@marcadella sorry about that. The explanation and the workaround is in https://github.com/nextstrain/nextclade/issues/367.

Closing this as duplicate, but feel free to comment or open a new issue if there is more
