### ISSUE TITLE
How does X get assigned in place of alternate amino acid while running nextclade?

### ISSUE THREAD

**Issue by sofiabanu** [nextstrain/nextclade#393]
Why is a 1 nucleotide deletion assigned as an X instead of a frameshift?

**Comment by rneher** [comment]
hi @sofiabanu , nextclade currently translates the nucleotide alignment codon by codon. This results in frame-shifting indels being "papered over". We are working on a new version that will handle indels better. But given that most frameshifts are likely sequencing errors, the codon-by-codon translation is probably not so far off in many cases.

**Comment by rneher** [comment]
this should be addressed in the newly released version 1
