### ISSUE TITLE
Can I color the tree by Emerging Lineage/PANGO Lineage just like nextstrain?

### ISSUE THREAD

**Issue by xzhub** [nextstrain/nextclade#401]
Is it possible to show the Emerging Lineage and PANGO Lineage in nextclade just like the nextstrain? Here is the screenshot from nextstrain.
![image](https://user-images.githubusercontent.com/3990687/116601589-420af880-a95d-11eb-85bb-9783fec20fe7.png)

**Comment by rneher** [comment]
these will be included in the next release.

**Comment by xzhub** [comment]
Awesome! Thanks!
