### ISSUE TITLE
nextalign-cli does not include reference

### ISSUE THREAD

**Issue by tolot27** [nextstrain/nextclade#402]
The parameter `--include-reference` of nextalign 1.0.0-alpha.1 is intend to add the reference sequence to the output file. Unfortunately, only the header and an empty sequence is added.

**Comment by ivan-aksamentov** [comment]
@tolot27 Thanks! Should be fixed in #403, [building](1.0.0-alpha.2
) and will be [released](https://github.com/nextstrain/nextclade/releases) as 1.0.0-alpha.2 in a few momments
