### ISSUE TITLE
Amino-acid change not detected on ORF10

### ISSUE THREAD

**Issue by mjaillard** [nextstrain/nextclade#404]
I studied a sample labeled as 20E (EU1) : ERR4778919. 
An alternative tool (BIONUMERICS) finds the expected V30L mutation in ORF10 (https://covariants.org/variants/20A.EU1) : 
![image](https://user-images.githubusercontent.com/83459222/116703219-4faa9780-a9ca-11eb-892c-a11e58a1a22f.png)

However, when running nextclade (0.14.2-alpine3.12), the aa substitution is not detected, even though the nucleotide mutation seems to be well identified : 
json extract:
      {
        "pos": 29644,
        "refNuc": "G",
        "queryNuc": "T",
        "aaSubstitutions": [],
        "pcrPrimersChanged": []
      }
 
Do you have any clue on why this happens ? 
Is this because ORF10 is possibly not translated (https://www.discngine.com/blog/2020/3/27/sars-cov-2-2-from-the-viral-genome-towards-protein-structures) ?
Note that among the hundreds of other analysed samples, I've never seen any ORF10 mutation reported. 

Thanks a lot,
Magali

**Comment by ivan-aksamentov** [comment]
Hi Magali @mjaillard ,

Could you provide example sequence(es) (or EPI_ISL number if these are on GISAID) and the exact command line parameters you are using? This is in order for us to reproduce the problem.


Additionally, the new version of Nextclade, 1.0.0, is in alpha testing stage. It might produce better results in some cases. If you want to give it a try, you can use [docker tag](https://hub.docker.com/r/nextstrain/nextclade/tags) `nextstrain/nextclade:1` or download native executable on [releases page](https://github.com/nextstrain/nextclade/releases) (it does not require any dependencies).

**Comment by rneher** [comment]
@mjaillard, you are correct. ORF10 mutations are not reported. 

the evidence that ORF10 is important for SARS-CoV-2 is rather weak

https://pubmed.ncbi.nlm.nih.gov/33301543/

and we have removed this gene from the program (along with ORF14 as there is little evidence of translation https://www.nature.com/articles/s41586-020-2739-1).

**Comment by mjaillard** [comment]
@rneher thank you for your answer :)
