### ISSUE TITLE
Update on Clade reference (Indian Variant)

### ISSUE THREAD

**Issue by nbargues** [nextstrain/nextclade#405]
Hi,

Thanks for your amazing tool.

I have a question regarding the Indian Variant. I understand that it have a reference lineage (B.1.617) but it seems to not have the equivalent with Clade. Do you know why and do you work on implement a specific reference clade for this variant ?

Regards

**Comment by rneher** [comment]
thanks for tagging this. We will release a new version shortly.

**Comment by rneher** [comment]
done with 0.14.4
