### ISSUE TITLE
Log to stderr instead of stdout

### ISSUE THREAD

**Issue by huddlej** [nextstrain/nextclade#410]
Related to #376, we'd like to be able to stream nextalign's primary alignment output to a compression tool, to avoid writing large alignments to disk and then compressing them. The simplest way to stream the alignment for compression is to use `/dev/stdout` like so:

```
nextalign \
  --jobs=4 \
  --reference defaults/reference_seq.fasta \
  --genemap defaults/annotation.gff \
  --genes ORF1a,ORF1b,S,ORF3a,M,N \
  --sequences data/sequences_gisaid.fasta \
  --output-dir results/translations \
  --output-basename seqs_gisaid  \
  --output-fasta /dev/stdout \
  --output-insertions results/insertions_gisaid.tsv 2> alignment_errors.txt | gzip -c > results/aligned_gisaid.fasta.gz
```

However, [stdout is currently used for nextalign's logger output](https://github.com/nextstrain/nextclade/blob/3703f4013f69407c9b91172997abc2e19b902b91/packages/nextalign_cli/src/Logger.h#L34).

Could we update the logger class to print to stderr by changing these print commands to look like `fmt::print(stderr, format_str, args...);`?

**Comment by ivan-aksamentov** [comment]
Resolved in #411 and [released](https://github.com/nextstrain/nextclade/releases) in 1.0.0-alpha.6
