### ISSUE TITLE
B.1.1.7 lineage N: M1X AA replacement issue

### ISSUE THREAD

**Issue by manolisathan** [nextstrain/nextclade#417]
Hi, I have noticed that in the majority of B.1.1.7 samples (hCoV-19/Spain/HUD-67120832/2021|EPI_ISL_2332597|2021-04-22, hCoV-19/Italy/EMR-173643-007-01/2021|EPI_ISL_2332611|2021-05-18), nextclade identifies the AA replacement N: M1X that actually does not exists when looking the Tree based on the Genotype. When running custom variant calling, the specific AA exists in the sequence (ATG -> M).  Thanks again! Manos

**Comment by rneher** [comment]
thanks for bringing this up. This issue has to do with a deletion in a poly-A tract right before the N gene. The current alignment places this deletion in the first base of N, which results in a broken codon. The next release should fix it.

**Comment by manolisathan** [comment]
Great! Thanks for this! Keep doing the great job!
Best,

Manos
