### ISSUE TITLE
how to cite

### ISSUE THREAD

**Issue by RichardCorbett** [nextstrain/nextclade#418]
Hi folks,
How should I cite nextclade in a paper?

**Comment by rneher** [comment]
Hi @RichardCorbett,
we don't have a formal citation for nextclade yet (it is in the works). For the time being, you can either just cite the website, the github repo. The most appropriate authors for the time being would be Aksamentov and Neher. If such an informal reference is not sufficient, you can cite [Hadfield et al, 2018](https://pubmed.ncbi.nlm.nih.gov/29790939/) as a proxy.

**Comment by RichardCorbett** [comment]
OK doke. Thanks @rneher !

**Comment by corneliusroemer** [comment]
This has now been resolved with publication of a JOSS paper:

https://joss.theoj.org/papers/10.21105/joss.03773

If you use results obtained with Nextclade in a publication, please

- cite our paper:
```
Aksamentov, I., Roemer, C., Hodcroft, E. B., & Neher, R. A., (2021). Nextclade: clade assignment, mutation calling and quality control for viral genomes. Journal of Open Source Software, 6(67), 3773, https://doi.org/10.21105/joss.03773
```
[bibtex](https://clades.nextstrain.org/citation.bib)

where possible, provide a link to Nextclade Web:

https://clades.nextstrain.org
