### ISSUE TITLE
Report errors in CSV, JSON and FASTA outputs

### ISSUE THREAD

**Issue by ivan-aksamentov** [nextstrain/nextclade#436]
We were previously reporting errors in sequence analysis

In v1 the sequences are omitted from fasta outputs and, for consistency also from CSV and JSON.

Users expressed interest in bringing error reporting back.

How would we do that?

**Comment by ivan-aksamentov** [comment]
One difficulty is that FASTA files cannot contain anything other than sequence names and sequence data.
I imagine, we can output name and empty sequence (just a newline) in case of alignment error. But that might be misleading and even break processing pipelines, as empty seuqences is not something that is usually expected.

If we don't output errored sequence into fasta, but output CSV/TSV rows, then the FASTA and CSV will go out of sync. Which might or might not be a problem.

If synchronization with FASTA is not a concern, we might bring back the "Error" column in CSV/TSV results and add "error" property to the JSON output.

Alternatively, we can output a separate file that aggregates only the errors.

Any combination of the above is also possible. These possibilities van also be made configurable with command-line flags and switches in the web UI.

Thoughts?

**Comment by Tato14** [comment]
Thanks for the great feedback on this. I guess the easiest way is to generate a specific file with the errors. This way the structure could be a little bit more versatile and you can always merge both files after. In this sense, it would be great if this output would report as many information about the cause of the QC failling as possible (N, M, P, C metrics, specify regions where aligment fails if possible, muts, gaps, etc).

This are my thoughs but any other option would be siutable for me. 

PS.: For the ones wanting to solve this quick and dirty I guess you can always sort descending by QC the V1 output table and append the failing rows by copy and paste :smile:

**Comment by ivan-aksamentov** [comment]
> information about the cause of the QC failling as possible

The QC issues are not considered errors in Nextclade, and not even warnings. But, perhaps confusingly, errors in the table.

Errors mean that analysis was interrupted at some point and Nextclade was not able to calculate the sequence analysis results. For example, if alignment fails, there is no way to detect mutations, compute any of QC metrics etc.

The details of QC are reported briefly in CSV/TSV and in full in JSON output. Perhaps you find JSON file more useful?


>specify regions where aligment fails if possible

Now that sounds like a great idea! Can you submit a new issues (feature request)?
