### ISSUE TITLE
Frequent crashes in tree view

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#438]
I've had at least 3 crashes within an hour while looking at 160 sequences (all AY.1 from GISAID) in tree view on Brave:1.25.70/MacOS:11.3.1

2 of the crashes happened, when I tried to back out from a tree (clicking on the parent branch on the very left).

The entire browser freezes and needs to be force quit through activity monitor.

I couldn't yet figure out how to reproduce it. It doesn't seem to be a particular step that causes it, maybe more something like a memory leak in a particular situation.

Here is part of the crash report, not sure whether it helps:
<details>
  <summary>Click to expand!</summary>
Date/Time:        2021-06-13 15:43:12.894 +0200
End time:         2021-06-13 15:45:06.105 +0200
OS Version:       macOS 11.3.1 (Build 20E241)
Architecture:     x86_64h
Report Version:   32
Share With Devs:  Yes

Data Source:      Stackshots
Shared Cache:     94BDF3EE-CD67-34B0-91E1-19D61487C096 slid base address 0x7fff20358000, slide 0x358000

Command:          Brave Browser
Path:             /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Identifier:       com.brave.Browser
Version:          91.1.25.70 (125.70)
Parent:           launchd [1]
PID:              13920
Time Since Fork:  509956s

Event:            hang
Duration:         113.21s
Duration Sampled: 9.90s (process was unresponsive for 103 seconds before sampling)
Steps:            99 (100ms sampling interval)
Report threshold: 2.5s

Hardware model:   MacBookPro15,1
Active cpus:      12
Boot args:        chunklist-security-epoch=0 -chunklist-no-rev2-dev

Time Awake Since Boot: 164954s
Time Since Wake:  1431s

Fan speed:        5918 rpm

--------------------------------------------------
Timeline format: stacks are sorted chronologically
Use -i and -heavy to re-report with count sorting
--------------------------------------------------

Heaviest stack for the main thread of the target process:
  99  start + 1 (libdyld.dylib + 89917) [0x7fff20681f3d]
  99  main + 287 (Brave Browser + 12735) [0x10507f1bf]
  99  ChromeMain + 277 (Brave Browser Framework + 17973) [0x106ef3635]
  99  ChromeMain + 59067389 (Brave Browser Framework + 59085085) [0x10a74811d]
  99  ChromeMain + 59065673 (Brave Browser Framework + 59083369) [0x10a747a69]
  99  ChromeMain + 59070607 (Brave Browser Framework + 59088303) [0x10a748daf]
  99  ChromeMain + 59071712 (Brave Browser Framework + 59089408) [0x10a749200]
  99  ChromeMain + 18829264 (Brave Browser Framework + 18846960) [0x1080e84f0]
  99  ChromeMain + 18844930 (Brave Browser Framework + 18862626) [0x1080ec222]
  99  ChromeMain + 18838831 (Brave Browser Framework + 18856527) [0x1080eaa4f]
  99  ChromeMain + 65228219 (Brave Browser Framework + 65245915) [0x10ad282db]
  99  ChromeMain + 65444341 (Brave Browser Framework + 65462037) [0x10ad5cf15]
  99  ChromeMain + 65720172 (Brave Browser Framework + 65737868) [0x10ada048c]
  99  ChromeMain + 65724908 (Brave Browser Framework + 65742604) [0x10ada170c]
  99  -[NSApplication run] + 586 (AppKit + 194169) [0x7fff22f4a679]
  99  ChromeMain + 63660105 (Brave Browser Framework + 63677801) [0x10aba9569]
  99  ChromeMain + 65700178 (Brave Browser Framework + 65717874) [0x10ad9b672]
  99  ChromeMain + 63660304 (Brave Browser Framework + 63678000) [0x10aba9630]
  99  -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1364 (AppKit + 250629) [0x7fff22f58305]
  99  _DPSNextEvent + 864 (AppKit + 256818) [0x7fff22f59b32]
  99  _BlockUntilNextEventMatchingListInModeWithFilter + 70 (HIToolbox + 199939) [0x7fff2897ed03]
  99  ReceiveNextEventCommon + 587 (HIToolbox + 200549) [0x7fff2897ef65]
  99  RunCurrentEventLoopInMode + 292 (HIToolbox + 201219) [0x7fff2897f203]
  99  CFRunLoopRunSpecific + 563 (CoreFoundation + 522076) [0x7fff2075d75c]
  99  __CFRunLoopRun + 2400 (CoreFoundation + 526207) [0x7fff2075e77f]
  99  __CFRunLoopDoSource1 + 619 (CoreFoundation + 532725) [0x7fff207600f5]
  99  __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41 (CoreFoundation + 533012) [0x7fff20760214]
  99  mshMIGPerform + 182 (HIServices + 39228) [0x7fff259d893c]
  99  _XCopyElementAtPosition + 369 (HIServices + 309000) [0x7fff25a1a708]
  99  _AXXMIGCopyElementAtPosition + 336 (HIServices + 174635) [0x7fff259f9a2b]
  99  CopyElementAtPosition + 150 (AppKit + 4688267) [0x7fff2339398b]
  99  -[NSApplication(NSApplicationAccessibility) accessibilityHitTest:] + 342 (AppKit + 4881060) [0x7fff233c2aa4]
  99  -[NSWindow(NSWindowAccessibility) accessibilityHitTest:] + 309 (AppKit + 9445345) [0x7fff2381cfe1]
  99  ChromeMain + 25359785 (Brave Browser Framework + 25377481) [0x108722ac9]
  99  ChromeMain + 24781814 (Brave Browser Framework + 24799510) [0x108695916]
  99  ChromeMain + 17915963 (Brave Browser Framework + 17933659) [0x10800955b]
  99  ChromeMain + 17845620 (Brave Browser Framework + 17863316) [0x107ff8294]
  99  ChromeMain + 17845620 (Brave Browser Framework + 17863316) [0x107ff8294]
  99  ChromeMain + 17845620 (Brave Browser Framework + 17863316) [0x107ff8294]
  99  ChromeMain + 17845620 (Brave Browser Framework + 17863316) [0x107ff8294]
  99  ChromeMain + 17845620 (Brave Browser Framework + 17863316) [0x107ff8294]
  99  ChromeMain + 17845620 (Brave Browser Framework + 17863316) [0x107ff8294]
  99  ChromeMain + 17845620 (Brave Browser Framework + 17863316) [0x107ff8294]
  99  ChromeMain + 17845620 (Brave Browser Framework + 17863316) [0x107ff8294]
  99  ChromeMain + 17845548 (Brave Browser Framework + 17863244) [0x107ff824c]
  99  ChromeMain + 17841124 (Brave Browser Framework + 17858820) [0x107ff7104]
  99  ChromeMain + 94874302 (Brave Browser Framework + 94891998) [0x10c96dfde]
  98  ChromeMain + 94874860 (Brave Browser Framework + 94892556) [0x10c96e20c]
  98  ChromeMain + 94875475 (Brave Browser Framework + 94893171) [0x10c96e473]
  84  ChromeMain + 94875475 (Brave Browser Framework + 94893171) [0x10c96e473]
  33  ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467]
  29  ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa]

Process:          Brave Browser (Brave) [13920]
UUID:             6C564F6D-F7D3-33E4-99ED-48329F2BB908
App Version:      91.1.25.70
Build Version:    125.70
Path:             /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Architecture:     x86_64
Parent:           launchd [1]
UID:              501
Footprint:        1046.54 MB
Time Since Fork:  509956s
Num samples:      99 (1-99)
CPU Time:         9.863s (38.3G cycles, 41.7G instructions, 0.92c/i)
Note:             Unresponsive for 103 seconds before sampling
Note:             2 idle work queue threads omitted

  Thread 0x6d369    DispatchQueue "com.apple.main-thread"(1)    Thread name "CrBrowserMain"    99 samples (1-99)    priority 46-47 (base 46-47)    cpu time 9.789s (38.0G cycles, 41.5G instructions, 0.92c/i)
  <thread QoS user interactive (requested user interactive), process unclamped, process received importance donation from WindowServer [144], process received importance donation from distnoted [427], IO tier 0, priority 46 (46)>
  99  start + 1 (libdyld.dylib + 89917) [0x7fff20681f3d] 1-99
    99  main + 287 (Brave Browser + 12735) [0x10507f1bf] 1-99
      99  ChromeMain + 277 (Brave Browser Framework + 17973) [0x106ef3635] 1-99
        99  ChromeMain + 59067389 (Brave Browser Framework + 59085085) [0x10a74811d] 1-99
          99  ChromeMain + 59065673 (Brave Browser Framework + 59083369) [0x10a747a69] 1-99
            99  ChromeMain + 59070607 (Brave Browser Framework + 59088303) [0x10a748daf] 1-99
              99  ChromeMain + 59071712 (Brave Browser Framework + 59089408) [0x10a749200] 1-99
                99  ChromeMain + 18829264 (Brave Browser Framework + 18846960) [0x1080e84f0] 1-99
                  99  ChromeMain + 18844930 (Brave Browser Framework + 18862626) [0x1080ec222] 1-99
                    99  ChromeMain + 18838831 (Brave Browser Framework + 18856527) [0x1080eaa4f] 1-99
                      99  ChromeMain + 65228219 (Brave Browser Framework + 65245915) [0x10ad282db] 1-99
                        99  ChromeMain + 65444341 (Brave Browser Framework + 65462037) [0x10ad5cf15] 1-99
                          99  ChromeMain + 65720172 (Brave Browser Framework + 65737868) [0x10ada048c] 1-99
                            99  ChromeMain + 65724908 (Brave Browser Framework + 65742604) [0x10ada170c] 1-99
                              99  -[NSApplication run] + 586 (AppKit + 194169) [0x7fff22f4a679] 1-99
                                99  ChromeMain + 63660105 (Brave Browser Framework + 63677801) [0x10aba9569] 1-99
                                  99  ChromeMain + 65700178 (Brave Browser Framework + 65717874) [0x10ad9b672] 1-99
                                    99  ChromeMain + 63660304 (Brave Browser Framework + 63678000) [0x10aba9630] 1-99
                                      99  -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1364 (AppKit + 250629) [0x7fff22f58305] 1-99
                                        99  _DPSNextEvent + 864 (AppKit + 256818) [0x7fff22f59b32] 1-99
                                          99  _BlockUntilNextEventMatchingListInModeWithFilter + 70 (HIToolbox + 199939) [0x7fff2897ed03] 1-99
                                            99  ReceiveNextEventCommon + 587 (HIToolbox + 200549) [0x7fff2897ef65] 1-99
                                              99  RunCurrentEventLoopInMode + 292 (HIToolbox + 201219) [0x7fff2897f203] 1-99
                                                99  CFRunLoopRunSpecific + 563 (CoreFoundation + 522076) [0x7fff2075d75c] 1-99
                                                  99  __CFRunLoopRun + 2400 (CoreFoundation + 526207) [0x7fff2075e77f] 1-99
                                                    99  __CFRunLoopDoSource1 + 619 (CoreFoundation + 532725) [0x7fff207600f5] 1-99
                                                      99  __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41 (CoreFoundation + 533012) [0x7fff20760214] 1-99
                                                        99  mshMIGPerform + 182 (HIServices + 39228) [0x7fff259d893c] 1-99
                                                          99  _XCopyElementAtPosition + 369 (HIServices + 309000) [0x7fff25a1a708] 1-99
                                                            99  _AXXMIGCopyElementAtPosition + 336 (HIServices + 174635) [0x7fff259f9a2b] 1-99
                                                              99  CopyElementAtPosition + 150 (AppKit + 4688267) [0x7fff2339398b] 1-99
                                                                99  -[NSApplication(NSApplicationAccessibility) accessibilityHitTest:] + 342 (AppKit + 4881060) [0x7fff233c2aa4] 1-99
                                                                  99  -[NSWindow(NSWindowAccessibility) accessibilityHitTest:] + 309 (AppKit + 9445345) [0x7fff2381cfe1] 1-99
                                                                    99  ChromeMain + 25359785 (Brave Browser Framework + 25377481) [0x108722ac9] 1-99
                                                                      99  ChromeMain + 24781814 (Brave Browser Framework + 24799510) [0x108695916] 1-99
                                                                        99  ChromeMain + 17915963 (Brave Browser Framework + 17933659) [0x10800955b] 1-99
                                                                          99  ChromeMain + 17845620 (Brave Browser Framework + 17863316) [0x107ff8294] 1-99
                                                                            99  ChromeMain + 17845620 (Brave Browser Framework + 17863316) [0x107ff8294] 1-99
                                                                              99  ChromeMain + 17845620 (Brave Browser Framework + 17863316) [0x107ff8294] 1-99
                                                                                99  ChromeMain + 17845620 (Brave Browser Framework + 17863316) [0x107ff8294] 1-99
                                                                                  99  ChromeMain + 17845620 (Brave Browser Framework + 17863316) [0x107ff8294] 1-99
                                                                                    99  ChromeMain + 17845620 (Brave Browser Framework + 17863316) [0x107ff8294] 1-99
                                                                                      99  ChromeMain + 17845620 (Brave Browser Framework + 17863316) [0x107ff8294] 1-99
                                                                                        99  ChromeMain + 17845620 (Brave Browser Framework + 17863316) [0x107ff8294] 1-99
                                                                                          99  ChromeMain + 17845548 (Brave Browser Framework + 17863244) [0x107ff824c] 1-99
                                                                                            99  ChromeMain + 17841124 (Brave Browser Framework + 17858820) [0x107ff7104] 1-99
                                                                                              99  ChromeMain + 94874302 (Brave Browser Framework + 94891998) [0x10c96dfde] 1-99
                                                                                                35  ChromeMain + 94874860 (Brave Browser Framework + 94892556) [0x10c96e20c] 1-35
                                                                                                  35  ChromeMain + 94875475 (Brave Browser Framework + 94893171) [0x10c96e473] 1-35
                                                                                                    1   ChromeMain + 94875475 (Brave Browser Framework + 94893171) [0x10c96e473] 1
                                                                                                      1   ChromeMain + 94875475 (Brave Browser Framework + 94893171) [0x10c96e473] 1
                                                                                                        1   ChromeMain + 94875406 (Brave Browser Framework + 94893102) [0x10c96e42e] (running) 1
                                                                                                    1   ChromeMain + 94875392 (Brave Browser Framework + 94893088) [0x10c96e420] (running) 2
                                                                                                    8   ChromeMain + 94875475 (Brave Browser Framework + 94893171) [0x10c96e473] 3-10
                                                                                                      1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 3
                                                                                                        1   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 3
                                                                                                      1   ChromeMain + 94875475 (Brave Browser Framework + 94893171) [0x10c96e473] 4
                                                                                                        1   ChromeMain + 94875398 (Brave Browser Framework + 94893094) [0x10c96e426] (running) 4
                                                                                                      1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 5
                                                                                                        1   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 5
                                                                                                      1   ChromeMain + 94875454 (Brave Browser Framework + 94893150) [0x10c96e45e] (running) 6
                                                                                                      1   ChromeMain + 94875479 (Brave Browser Framework + 94893175) [0x10c96e477] (running) 7
                                                                                                      1   ChromeMain + 94875398 (Brave Browser Framework + 94893094) [0x10c96e426] (running) 8
                                                                                                      1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 9
                                                                                                        1   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 9
                                                                                                      1   ChromeMain + 94875454 (Brave Browser Framework + 94893150) [0x10c96e45e] (running) 10
                                                                                                    1   ChromeMain + 94875440 (Brave Browser Framework + 94893136) [0x10c96e450] (running) 11
                                                                                                    1   ChromeMain + 94875504 (Brave Browser Framework + 94893200) [0x10c96e490] (running) 12
                                                                                                    10  ChromeMain + 94875475 (Brave Browser Framework + 94893171) [0x10c96e473] 13-22
                                                                                                      1   ChromeMain + 94875504 (Brave Browser Framework + 94893200) [0x10c96e490] (running) 13
                                                                                                      1   ChromeMain + 94875454 (Brave Browser Framework + 94893150) [0x10c96e45e] (running) 14
                                                                                                      1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 15
                                                                                                        1   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 15
                                                                                                      1   ChromeMain + 94875458 (Brave Browser Framework + 94893154) [0x10c96e462] (running) 16
                                                                                                      2   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 17-18
                                                                                                        2   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 17-18
                                                                                                      3   ChromeMain + 94875454 (Brave Browser Framework + 94893150) [0x10c96e45e] (running) 19-21
                                                                                                      1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 22
                                                                                                        1   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 22
                                                                                                    1   ChromeMain + 94875392 (Brave Browser Framework + 94893088) [0x10c96e420] (running) 23
                                                                                                    12  ChromeMain + 94875475 (Brave Browser Framework + 94893171) [0x10c96e473] 24-35
                                                                                                      1   ChromeMain + 94875421 (Brave Browser Framework + 94893117) [0x10c96e43d] (running) 24
                                                                                                      3   ChromeMain + 94875454 (Brave Browser Framework + 94893150) [0x10c96e45e] (running) 25-27
                                                                                                      1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 28
                                                                                                        1   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 28
                                                                                                      3   ChromeMain + 94875454 (Brave Browser Framework + 94893150) [0x10c96e45e] (running) 29-31
                                                                                                      1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 32
                                                                                                        1   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 32
                                                                                                      1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] (running) 33
                                                                                                      1   ChromeMain + 94875489 (Brave Browser Framework + 94893185) [0x10c96e481] (running) 34
                                                                                                      1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 35
                                                                                                        1   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 35
                                                                                                1   ChromeMain + 94875018 (Brave Browser Framework + 94892714) [0x10c96e2aa] (running) 36
                                                                                                63  ChromeMain + 94874860 (Brave Browser Framework + 94892556) [0x10c96e20c] 37-99
                                                                                                  63  ChromeMain + 94875475 (Brave Browser Framework + 94893171) [0x10c96e473] 37-99
                                                                                                    1   ChromeMain + 94875475 (Brave Browser Framework + 94893171) [0x10c96e473] 37
                                                                                                      1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 37
                                                                                                        1   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 37
                                                                                                    1   ChromeMain + 94875440 (Brave Browser Framework + 94893136) [0x10c96e450] (running) 38
                                                                                                    6   ChromeMain + 94875475 (Brave Browser Framework + 94893171) [0x10c96e473] 39-44
                                                                                                      1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 39
                                                                                                        1   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 39
                                                                                                      1   ChromeMain + 94875454 (Brave Browser Framework + 94893150) [0x10c96e45e] (running) 40
                                                                                                      3   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 41-43
                                                                                                        1   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 41
                                                                                                        1   ChromeMain + 94566547 (Brave Browser Framework + 94584243) [0x10c922db3] (running) 42
                                                                                                        1   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 43
                                                                                                      1   ChromeMain + 94875454 (Brave Browser Framework + 94893150) [0x10c96e45e] (running) 44
                                                                                                    1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 45
                                                                                                      1   ChromeMain + 94566532 (Brave Browser Framework + 94584228) [0x10c922da4] (running) 45
                                                                                                    1   ChromeMain + 94875475 (Brave Browser Framework + 94893171) [0x10c96e473] 46
                                                                                                      1   ChromeMain + 94875475 (Brave Browser Framework + 94893171) [0x10c96e473] 46
                                                                                                        1   ChromeMain + 94875494 (Brave Browser Framework + 94893190) [0x10c96e486] (running) 46
                                                                                                    1   ChromeMain + 94875504 (Brave Browser Framework + 94893200) [0x10c96e490] (running) 47
                                                                                                    1   ChromeMain + 94875475 (Brave Browser Framework + 94893171) [0x10c96e473] 48
                                                                                                      1   ChromeMain + 94875454 (Brave Browser Framework + 94893150) [0x10c96e45e] (running) 48
                                                                                                    1   ChromeMain + 94875458 (Brave Browser Framework + 94893154) [0x10c96e462] (running) 49
                                                                                                    13  ChromeMain + 94875475 (Brave Browser Framework + 94893171) [0x10c96e473] 50-62
                                                                                                      1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 50
                                                                                                        1   ChromeMain + 94566547 (Brave Browser Framework + 94584243) [0x10c922db3] (running) 50
                                                                                                      1   ChromeMain + 94875454 (Brave Browser Framework + 94893150) [0x10c96e45e] (running) 51
                                                                                                      1   ChromeMain + 94875475 (Brave Browser Framework + 94893171) [0x10c96e473] 52
                                                                                                        1   ChromeMain + 94875398 (Brave Browser Framework + 94893094) [0x10c96e426] (running) 52
                                                                                                      4   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 53-56
                                                                                                        2   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 53-54
                                                                                                        1   ChromeMain + 94566532 (Brave Browser Framework + 94584228) [0x10c922da4] (running) 55
                                                                                                        1   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 56
                                                                                                      2   ChromeMain + 94875454 (Brave Browser Framework + 94893150) [0x10c96e45e] (running) 57-58
                                                                                                      1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 59
                                                                                                        1   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 59
                                                                                                      1   ChromeMain + 94875454 (Brave Browser Framework + 94893150) [0x10c96e45e] (running) 60
                                                                                                      1   ChromeMain + 94875475 (Brave Browser Framework + 94893171) [0x10c96e473] 61
                                                                                                        1   ChromeMain + 94875501 (Brave Browser Framework + 94893197) [0x10c96e48d] (running) 61
                                                                                                      1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 62
                                                                                                        1   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 62
                                                                                                    1   ChromeMain + 94875454 (Brave Browser Framework + 94893150) [0x10c96e45e] (running) 63
                                                                                                    2   ChromeMain + 94875475 (Brave Browser Framework + 94893171) [0x10c96e473] 64-65
                                                                                                      1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 64
                                                                                                        1   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 64
                                                                                                      1   ChromeMain + 94875454 (Brave Browser Framework + 94893150) [0x10c96e45e] (running) 65
                                                                                                    1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] (running) 66
                                                                                                    5   ChromeMain + 94875475 (Brave Browser Framework + 94893171) [0x10c96e473] 67-71
                                                                                                      1   ChromeMain + 94875454 (Brave Browser Framework + 94893150) [0x10c96e45e] (running) 67
                                                                                                      1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 68
                                                                                                        1   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 68
                                                                                                      1   ChromeMain + 94875454 (Brave Browser Framework + 94893150) [0x10c96e45e] (running) 69
                                                                                                      1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] (running) 70
                                                                                                      1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 71
                                                                                                        1   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 71
                                                                                                    1   ChromeMain + 94875440 (Brave Browser Framework + 94893136) [0x10c96e450] (running) 72
                                                                                                    4   ChromeMain + 94875475 (Brave Browser Framework + 94893171) [0x10c96e473] 73-76
                                                                                                      1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 73
                                                                                                        1   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 73
                                                                                                      1   ChromeMain + 94875454 (Brave Browser Framework + 94893150) [0x10c96e45e] (running) 74
                                                                                                      1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 75
                                                                                                        1   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 75
                                                                                                      1   ChromeMain + 94875489 (Brave Browser Framework + 94893185) [0x10c96e481] (running) 76
                                                                                                    1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 77
                                                                                                      1   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 77
                                                                                                    4   ChromeMain + 94875475 (Brave Browser Framework + 94893171) [0x10c96e473] 78-81
                                                                                                      1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 78
                                                                                                        1   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 78
                                                                                                      1   ChromeMain + 94875398 (Brave Browser Framework + 94893094) [0x10c96e426] (running) 79
                                                                                                      2   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 80-81
                                                                                                        2   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 80-81
                                                                                                    1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 82
                                                                                                      1   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 82
  <process frontmost, priority 47 (47)>
                                                                                                    7   ChromeMain + 94875475 (Brave Browser Framework + 94893171) [0x10c96e473] 83-89
                                                                                                      1   ChromeMain + 94875454 (Brave Browser Framework + 94893150) [0x10c96e45e] (running) 83
                                                                                                      2   ChromeMain + 94875440 (Brave Browser Framework + 94893136) [0x10c96e450] (running) 84-85
                                                                                                      1   ChromeMain + 94875475 (Brave Browser Framework + 94893171) [0x10c96e473] 86
                                                                                                        1   ChromeMain + 94875406 (Brave Browser Framework + 94893102) [0x10c96e42e] (running) 86
                                                                                                      1   ChromeMain + 94875454 (Brave Browser Framework + 94893150) [0x10c96e45e] (running) 87
                                                                                                      1   ChromeMain + 94875489 (Brave Browser Framework + 94893185) [0x10c96e481] (running) 88
                                                                                                      1   ChromeMain + 94875454 (Brave Browser Framework + 94893150) [0x10c96e45e] (running) 89
                                                                                                    1   ChromeMain + 94875440 (Brave Browser Framework + 94893136) [0x10c96e450] (running) 90
                                                                                                    9   ChromeMain + 94875475 (Brave Browser Framework + 94893171) [0x10c96e473] 91-99
                                                                                                      1   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 91
                                                                                                        1   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 91
                                                                                                      2   ChromeMain + 94875454 (Brave Browser Framework + 94893150) [0x10c96e45e] (running) 92-93
                                                                                                      2   ChromeMain + 94875463 (Brave Browser Framework + 94893159) [0x10c96e467] 94-95
                                                                                                        1   ChromeMain + 94566532 (Brave Browser Framework + 94584228) [0x10c922da4] (running) 94
                                                                                                        1   ChromeMain + 94566538 (Brave Browser Framework + 94584234) [0x10c922daa] (running) 95
                                                                                                      4   ChromeMain + 94875454 (Brave Browser Framework + 94893150) [0x10c96e45e] (running) 96-99

</details>

**Comment by corneliusroemer** [comment]
I may have figured out the reason for the crashes: I was fairly low on disk space (4 GB free). I thought that's ok, but the space may have been used as swap or something. Nextclade is definitely memory hungry and may thus have caused the crash indirectly.

I've cleaned up and now have 50 GB free on my disk. I'll close the issue and reopen if the crashes come back.

**Comment by ivan-aksamentov** [comment]
@corneliusroemer Thanks for the investigation!

Might be related: we had problems with Brave before. Not sure we can fix that, but we could perhaps at least warn users about the incompatibilities. I made an issue: https://github.com/nextstrain/nextclade/issues/439

**Comment by ivan-aksamentov** [comment]
I just realized that we are not releasing some of the resources, which may lead to increased memory consumption: https://github.com/nextstrain/nextclade/issues/445
