### ISSUE TITLE
Don't add "help wanted" and "good first issue" labels automatically to all new issues

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#444]
Ironically these labels are not auto-applied of you choose "discuss" as I did here

**Comment by ivan-aksamentov** [comment]
Most of the issues raised by users will fall into category "Nice to have" so far and the team will probably not have time to address them. We'd like more external code contributions, hence the tag spamming. Same reasoning as with covariants ;)

"Discuss" is more like a catch-all section here, where the need for contributions is not obvious. And it worked for this issue :)

**Comment by ivan-aksamentov** [comment]
@corneliusroemer  Now that you raised this issue twice, I am wondering if you have examples of issues that would not benefit from adding these labels right away? Or what is the reasoning?

**Comment by corneliusroemer** [comment]
Your memory is clearly better than mine, didn't remember raising it before.

I think the idea behind "good first issue" is for the label to be applied very carefully by the maintainers on select issues that are particularly well suited for people new on the project.

By adding it to all issues by default you reduce the information value of the tag. And end up having label overflow on top reducing visibility of the other labels.

I would only add "good first issue" after triaging on issues that you really feel are self-contained.

As to "help wanted", similar reasoning applied as above. To make it useful it would have to be applied in different cases than "good first issue". Maybe in those that are more complicated but still manageable for outside contributors from your point of view.

I'll add a few examples in a second.

**Comment by ivan-aksamentov** [comment]
@corneliusroemer 
Oh sorry.... I confused my contributor folks https://github.com/hodcroftlab/covariants/pull/133

**Comment by corneliusroemer** [comment]
No worries 🙂

Probably not good first issues: #30 #38 #325 and many more, as I said think the value is biggest if there is a curated set of good first issues. Auto-application goes against that spirit.

So maybe help wanted to could be applied by default and removed of help is *not* wanted, whereas good first issue could be added if you feel it's particularly well suited.

**Comment by ivan-aksamentov** [comment]
Alright, convinced! Feel free to make a PR :)
