### ISSUE TITLE
Analysis of fasta files does not work, error: std::bad_alloc

### ISSUE THREAD

**Issue by anneva1** [nextstrain/nextclade#446]
I tried to analyse fasta files in naxtclade but I got the following error: std::bad_alloc
Can you fix this?
![image](https://user-images.githubusercontent.com/85871849/121869587-7ca8d480-cd02-11eb-945f-4c925c7653ff.png)

Anwer to your questions: 

Operating System: windows 10
Browser: google chrome
Is the error reproducible? Does it happen again if you open a new tab, upload the same Fasta? yes
How big is the Fasta file in MB? I add the fasta file in attachment: 476 kb
Kind regards,

Anne

**Comment by corneliusroemer** [comment]
Thank you very much for reporting the error.

Could you please add the following additional information to enable investigation:
- Operating System
- Browser
- Is the error reproducible? Does it happen again if you open a new tab, upload the same Fasta?
- How big is the Fasta file in MB?

**Comment by ivan-aksamentov** [comment]
Hi @anneva1 ,

Nextclade can sometimes use a lot of memory. `std::bad_alloc` means it cannot find enough memory on your computer in order to run. And we definitely need a better error message here!

In order to help I need to know a few things:

 - how many sequences are you trying to analyze?
 - what operating system, browser and browser version are you using?
 - do you use any ad blocking browser extensions?
 - can you tell how much memory (RAM) does your computer have?
 - how much memory (RAM) is there free before you start sequence analysis?


A few things you might try:

 - try to run with less sequences, smaller fasta file
 - free up some memory by closing unused browser tabs and other programs and documents on your computer
 - try to run on another computer, with more memory resources, if available

**Comment by anneva1** [comment]
Dear,

I even tried to add 1 fasta sequence (SARS-CoV-2) and that even didn't work. It also does not work on the PC of my colleague. It worked perfect until last week. When I tried to analyze my sequences on friday (fasta containing 16 sequences for SARS-CoV-2 analysis) it did not work anymore.

Kind regards,

Anne



    [cid:a6294901-3be9-4216-be46-a9a745ba0e25]

Anne Vankeerberghen
Wetenschappelijk medewerker

Labo Moleculaire Biologie
T. 053/72.40.59
Onze-Lieve-Vrouwziekenhuis VZW Campus Aalst-Asse-Ninove
Moorselbaan 164, B-9300 Aalst
www.olvz.be<http://www.olvz.be/>


________________________________
Van: Ivan Aksamentov ***@***.***>
Verzonden: maandag 14 juni 2021 11:37
Aan: nextstrain/nextclade ***@***.***>
CC: ANNE VANKEERBERGHEN ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [nextstrain/nextclade] Analysis of fasta files does not work, error: std::bad_alloc (#446)


OPGELET ! Deze e-mail is afkomstig van buiten onze organisatie. Open links en/of bijlagen enkel van gekende afzenders en wanneer u weet dat de inhoud betrouwbaar is. Verdachte e-mails kunnen ter controle doorgestuurd worden naar ***@***.***


Hi @anneva1<https://github.com/anneva1> ,

Nextclade can sometimes use a lot of memory. std::bad_alloc means it cannot find enough memory on your computer in order to run. And we definitely need a better error message here!

In order to help I need to know a few things:

  *   how many sequences are you trying to analyze?
  *   what operating system, browser and browser version are you using?
  *   do you use any ad blocking browser extensions?
  *   can you tell how much memory (RAM) does your computer have?
  *   how much memory (RAM) is there free before you start sequence analysis?

A few things you might try:

  *   try to run with less sequences, smaller fasta file
  *   free up some memory by closing unused browser tabs and other programs and documents on your computer
  *   try to run on another computer, with more memory resources, if available

**Comment by anneva1** [comment]
Dear,

I even tried to add 1 fasta sequence (SARS-CoV-2) and that even didn't work. It also does not work on the PC of my colleague. It worked perfect until last week. When I tried to analyze my sequences on friday (fasta containing 16 sequences for SARS-CoV-2 analysis) it did not work anymore.

Kind regards,

Anne



    [cid:bb9603de-d215-437d-9b40-ffb3ea09ce63]

Anne Vankeerberghen
Wetenschappelijk medewerker

Labo Moleculaire Biologie
T. 053/72.40.59
Onze-Lieve-Vrouwziekenhuis VZW Campus Aalst-Asse-Ninove
Moorselbaan 164, B-9300 Aalst
www.olvz.be<http://www.olvz.be/>


________________________________
Van: Ivan Aksamentov ***@***.***>
Verzonden: maandag 14 juni 2021 11:37
Aan: nextstrain/nextclade ***@***.***>
CC: ANNE VANKEERBERGHEN ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [nextstrain/nextclade] Analysis of fasta files does not work, error: std::bad_alloc (#446)


OPGELET ! Deze e-mail is afkomstig van buiten onze organisatie. Open links en/of bijlagen enkel van gekende afzenders en wanneer u weet dat de inhoud betrouwbaar is. Verdachte e-mails kunnen ter controle doorgestuurd worden naar ***@***.***


Hi @anneva1<https://github.com/anneva1> ,

Nextclade can sometimes use a lot of memory. std::bad_alloc means it cannot find enough memory on your computer in order to run. And we definitely need a better error message here!

In order to help I need to know a few things:

  *   how many sequences are you trying to analyze?
  *   what operating system, browser and browser version are you using?
  *   do you use any ad blocking browser extensions?
  *   can you tell how much memory (RAM) does your computer have?
  *   how much memory (RAM) is there free before you start sequence analysis?

A few things you might try:

  *   try to run with less sequences, smaller fasta file
  *   free up some memory by closing unused browser tabs and other programs and documents on your computer
  *   try to run on another computer, with more memory resources, if available

**Comment by ivan-aksamentov** [comment]
@anneva1 
Dear Anne, 

I am sorry you are experiencing this. We've released a new version on Friday and that's why you might be having these issues.

For us to be able to help and to investigate the problem, it is essential for you to to other questions in my previous message. So if you a spare minute, we'd appreciate that. You might also try some of the other steps I listed. And let me know if you have more findings.


Thanks and best regards,
Ivan

**Comment by anneva1** [comment]
Dear,


You can find the answers beeath:



Thank you very much for reporting the error.

Could you please add the following additional information to enable investigation:

  *   Operating System: windows 10
  *   Browser: google chrome
  *   Is the error reproducible? Does it happen again if you open a new tab, upload the same Fasta? yes
  *   How big is the Fasta file in MB? I add the fasta file in attachment: 476 kb

Kind regards,

Anne




    [cid:6b064a8d-83f3-45bc-9064-84f601170d4b]

Anne Vankeerberghen
Wetenschappelijk medewerker

Labo Moleculaire Biologie
T. 053/72.40.59
Onze-Lieve-Vrouwziekenhuis VZW Campus Aalst-Asse-Ninove
Moorselbaan 164, B-9300 Aalst
www.olvz.be<http://www.olvz.be/>


________________________________
Van: Ivan Aksamentov ***@***.***>
Verzonden: maandag 14 juni 2021 11:57
Aan: nextstrain/nextclade ***@***.***>
CC: ANNE VANKEERBERGHEN ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [nextstrain/nextclade] Analysis of fasta files does not work, error: std::bad_alloc (#446)


OPGELET ! Deze e-mail is afkomstig van buiten onze organisatie. Open links en/of bijlagen enkel van gekende afzenders en wanneer u weet dat de inhoud betrouwbaar is. Verdachte e-mails kunnen ter controle doorgestuurd worden naar ***@***.***


@anneva1<https://github.com/anneva1>
Dear Anne,

I am sorry you are experiencing this. We've released a new version on Friday and that's why you might be having these issues.

For us to be able to help and to investigate the problem, it is essential for you to to other questions in my previous message. So if you a spare minute, we'd appreciate that. You might also try some of the other steps I listed. And let me know if you have more findings.

Thanks and best regards,
Ivan

**Comment by ivan-aksamentov** [comment]
@anneva1
Dear Anne,

I am sorry, I am not able to see the answers. There could be a problem in how GitHub sends emails.

Could you please come back to the GitHub thread using this link:
https://github.com/nextstrain/nextclade/issues/446
?

It is much faster and more straightforward. I'd be glad to continue there.

Thanks!

**Comment by anneva1** [comment]
Dear,

I tries to edit the answers in my original isuue on github, I hope it went well. I will add the answers also in this mail and add a fasta file:

  *   Operating System: windows 10
  *   Browser: google chrome
  *   Is the error reproducible? Does it happen again if you open a new tab, upload the same Fasta? yes
  *   How big is the Fasta file in MB? I add the fasta file in attachment: 476 kb

Kind regards,

Anne



    [cid:4541451a-99ce-4554-bce1-f27333a7625e]

Anne Vankeerberghen
Wetenschappelijk medewerker

Labo Moleculaire Biologie
T. 053/72.40.59
Onze-Lieve-Vrouwziekenhuis VZW Campus Aalst-Asse-Ninove
Moorselbaan 164, B-9300 Aalst
www.olvz.be<http://www.olvz.be/>


________________________________
Van: Ivan Aksamentov ***@***.***>
Verzonden: maandag 14 juni 2021 12:06
Aan: nextstrain/nextclade ***@***.***>
CC: ANNE VANKEERBERGHEN ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [nextstrain/nextclade] Analysis of fasta files does not work, error: std::bad_alloc (#446)


OPGELET ! Deze e-mail is afkomstig van buiten onze organisatie. Open links en/of bijlagen enkel van gekende afzenders en wanneer u weet dat de inhoud betrouwbaar is. Verdachte e-mails kunnen ter controle doorgestuurd worden naar ***@***.***


@anneva1<https://github.com/anneva1>
Dear Anne,

I am sorry, I am not able to see the answers. There could be a problem in how GitHub sends emails.

Could you please come back to the GitHub thread using this link:
#446<https://github.com/nextstrain/nextclade/issues/446>
?

It is much faster and more straightforward. I'd be glad to continue there.

Thanks!

**Comment by ivan-aksamentov** [comment]
@anneva1
Anna,

Thanks!
But you are replying to the message Cornelius wrote. But there is another message from me, right after it, that contains many more questions and some potential solutions. PLease take a look.

**Comment by anneva1** [comment]
Dear Ivan,

I add the answers in the text beneath:

In order to help I need to know a few things:

  *   how many sequences are you trying to analyze? 16
  *   what operating system, browser and browser version are you using? windows 10, google chrome Version 91.0.4472.101 (Official Build) (32-bit)
  *   do you use any ad blocking browser extensions? not that I know
  *   can you tell how much memory (RAM) does your computer have? 117 GB
  *   how much memory (RAM) is there free before you start sequence analysis? 56.5 GB

A few things you might try:

  *   try to run with less sequences, smaller fasta file: 1 fasta file does not work (40000bp).
  *   free up some memory by closing unused browser tabs and other programs and documents on your computer: not done
  *   try to run on another computer, with more memory resources, if available: same problem




    [cid:306ef39b-32fd-4174-b47b-b99803b6ffdc]

Anne Vankeerberghen
Wetenschappelijk medewerker

Labo Moleculaire Biologie
T. 053/72.40.59
Onze-Lieve-Vrouwziekenhuis VZW Campus Aalst-Asse-Ninove
Moorselbaan 164, B-9300 Aalst
www.olvz.be<http://www.olvz.be/>


________________________________
Van: Ivan Aksamentov ***@***.***>
Verzonden: maandag 14 juni 2021 11:37
Aan: nextstrain/nextclade ***@***.***>
CC: ANNE VANKEERBERGHEN ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [nextstrain/nextclade] Analysis of fasta files does not work, error: std::bad_alloc (#446)


OPGELET ! Deze e-mail is afkomstig van buiten onze organisatie. Open links en/of bijlagen enkel van gekende afzenders en wanneer u weet dat de inhoud betrouwbaar is. Verdachte e-mails kunnen ter controle doorgestuurd worden naar ***@***.***


Hi @anneva1<https://github.com/anneva1> ,

Nextclade can sometimes use a lot of memory. std::bad_alloc means it cannot find enough memory on your computer in order to run. And we definitely need a better error message here!

In order to help I need to know a few things:

  *   how many sequences are you trying to analyze?
  *   what operating system, browser and browser version are you using?
  *   do you use any ad blocking browser extensions?
  *   can you tell how much memory (RAM) does your computer have?
  *   how much memory (RAM) is there free before you start sequence analysis?

A few things you might try:

  *   try to run with less sequences, smaller fasta file
  *   free up some memory by closing unused browser tabs and other programs and documents on your computer
  *   try to run on another computer, with more memory resources, if available

**Comment by ivan-aksamentov** [comment]
Thanks! That's a powerful computer, so probably not related to resource availability. I think there might be a problem with Nextclade algorithm then. I unfortunately unable to see the fasta file. GitHub does not pass attachments through, I think.

Can you upload the file somewhere and link here? It would be very useful to reproduce the bug. Note that it will be available publicly.


Thanks!

**Comment by anneva1** [comment]
Dear,

When I open nextclade in Microsoft Edge it works well. Maybe there is a problem with microsoft chrome? I will continue with Micrsoft Edge.

Thanks a lot for your help.

Anne





    [cid:da9b9113-5b4e-4533-8e79-480204da33d2]

Anne Vankeerberghen
Wetenschappelijk medewerker

Labo Moleculaire Biologie
T. 053/72.40.59
Onze-Lieve-Vrouwziekenhuis VZW Campus Aalst-Asse-Ninove
Moorselbaan 164, B-9300 Aalst
www.olvz.be<http://www.olvz.be/>


________________________________
Van: Ivan Aksamentov ***@***.***>
Verzonden: maandag 14 juni 2021 12:37
Aan: nextstrain/nextclade ***@***.***>
CC: ANNE VANKEERBERGHEN ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [nextstrain/nextclade] Analysis of fasta files does not work, error: std::bad_alloc (#446)


OPGELET ! Deze e-mail is afkomstig van buiten onze organisatie. Open links en/of bijlagen enkel van gekende afzenders en wanneer u weet dat de inhoud betrouwbaar is. Verdachte e-mails kunnen ter controle doorgestuurd worden naar ***@***.***


Thanks! That's a powerful computer, so probably not related to resource availability. I think there might be a problem with Nextclade algorithm then. I unfortunately unable to see the fasta file. GitHub does not pass attachments through, I think.

Can you upload the file somewhere and link here? It would be very useful to reproduce the bug. Note that it will be available publicly.

Thanks!

**Comment by ivan-aksamentov** [comment]
Interesting! Nowadays both Chrome and Edge use the same engine underneath. Could it be that there are more tabs open in your Chrome instance than in Edge? I am not quite sure how memory is allocated for different tabs.

I'd still appreciate if you can share the sequence in order to reproduce the issue. You can find my email on this page: https://www.biozentrum.unibas.ch/research/researchgroups/group/unit/neher/

**Comment by Batsi-2015** [comment]
Hi @ivan-aksamentov and @anneva1. I also had the same problem, its giving the same error @anneva1 mentioned on Chrome and Firefox, but its working okay on Edge.

**Comment by ivan-aksamentov** [comment]
@Batsi-2015 @anneva1 
I have a hypothesis about why that may happen.

Can you share your computer specs? Notably the number of cores/threads, and if it's the case, the number of CPUs (sockets).

@Batsi-2015  How much memory (RAM) do you have on your computer and how much of it is free before you run Nextclade?

Thanks!

**Comment by Batsi-2015** [comment]
@ivan-aksamentov i am running on Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz 1.90 GHz Processor. It has 4 cores, 1 socket and 8 logical processors. The installed RAM is 16.0 GB (15.8 GB usable). 2.4 G memory was available before running

**Comment by ivan-aksamentov** [comment]
@Batsi-2015 Can you confirm that you see "Starting 8 threads..." status message in the top section of results page shortly after the analysis is started?

**Comment by Batsi-2015** [comment]
Yes its starting 8 threads

**Comment by ivan-aksamentov** [comment]
@Batsi-2015 2.4G per 8 threads, leaves only 300 Mb per thread. I'm afraid it might not be enough. Is it possible for you to free up some memory on your computer and to try to run it again, to see if that will fix it?

**Comment by ivan-aksamentov** [comment]
This should be better now, after the improvements in https://github.com/nextstrain/nextclade/pull/451. There were no more responses, so I am closing this issue. Please comment or submit another issue if there are still problems.

**Comment by anneva1** [comment]
Indeed, it works again.

Kind regards,

Anne



    [cid:51c03ac0-8071-48c4-8266-4c38fa851f2d]

Anne Vankeerberghen
Wetenschappelijk medewerker

Labo Moleculaire Biologie
T. 053/72.40.59
Onze-Lieve-Vrouwziekenhuis VZW Campus Aalst-Asse-Ninove
Moorselbaan 164, B-9300 Aalst
www.olvz.be<http://www.olvz.be/>


________________________________
Van: Ivan Aksamentov ***@***.***>
Verzonden: woensdag 8 september 2021 17:14
Aan: nextstrain/nextclade ***@***.***>
CC: ANNE VANKEERBERGHEN ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [nextstrain/nextclade] Analysis of fasta files does not work, error: std::bad_alloc (#446)


OPGELET ! Deze e-mail is afkomstig van buiten onze organisatie. Open links en/of bijlagen enkel van gekende afzenders en wanneer u weet dat de inhoud betrouwbaar is. Verdachte e-mails kunnen ter controle doorgestuurd worden naar ***@***.***


This should be better now, after the improvements in #451<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnextstrain%2Fnextclade%2Fpull%2F451&data=04%7C01%7Canne.vankeerberghen%40olvz-aalst.be%7C7bf7ba0571104532494608d972db54a7%7Cc4d03ee3d8a5446bbf4a62e7cc63eda0%7C0%7C0%7C637667108603799607%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=a%2FTDizn54CuAvNz5NjefnLq5dQh77W9aKvH9h6QAN3U%3D&reserved=0>. There were no more responses, so I am closing this issue. Please comment or submit another issue if there are still problems.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnextstrain%2Fnextclade%2Fissues%2F446%23issuecomment-915328806&data=04%7C01%7Canne.vankeerberghen%40olvz-aalst.be%7C7bf7ba0571104532494608d972db54a7%7Cc4d03ee3d8a5446bbf4a62e7cc63eda0%7C0%7C0%7C637667108603799607%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3HOKCWgwgQafOKN2R%2BZxiikuNCNaS%2B7yMEcrWCEVMgg%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUPEZ2L2Q7YH7CRN2U7GNXDUA54UTANCNFSM46U25WAA&data=04%7C01%7Canne.vankeerberghen%40olvz-aalst.be%7C7bf7ba0571104532494608d972db54a7%7Cc4d03ee3d8a5446bbf4a62e7cc63eda0%7C0%7C0%7C637667108603809601%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rvLDi2rfkqN5x5Ct9qht9hjcTW3RbIgbcIeCuBixyqQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Canne.vankeerberghen%40olvz-aalst.be%7C7bf7ba0571104532494608d972db54a7%7Cc4d03ee3d8a5446bbf4a62e7cc63eda0%7C0%7C0%7C637667108603809601%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gnnE0HGTAL8%2B9%2B%2FjV%2FuqYjfvwVEwfoGIgGw9oa7kFnk%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Canne.vankeerberghen%40olvz-aalst.be%7C7bf7ba0571104532494608d972db54a7%7Cc4d03ee3d8a5446bbf4a62e7cc63eda0%7C0%7C0%7C637667108603819591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nFMCqFqsKTbaX%2BYylh35SpqRfmj6jL1V7EKIovl2KpQ%3D&reserved=0>.
