### ISSUE TITLE
Nextclade/Nextalign releases can't be installed on Mac: Unidentified developer

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#482]
When trying to install nextclade and nextalign from the nextclade website on my Mac, I get the following error message:
```
“nextclade-MacOS-x86_64” cannot be opened because it is from an unidentified developer.
macOS cannot verify that this app is free from malware.
```

![image](https://user-images.githubusercontent.com/25161793/125948752-fed4388e-100d-48d9-bde3-6fd0eb96970b.png)

**Comment by ivan-aksamentov** [comment]
Explained in the user's guide for Nextalign:
https://github.com/nextstrain/nextclade/blob/master/packages/nextalign_cli/README.md#-users-guide. Same principle for Nextclade.

We would have to pay for Apple Dev account and probably own a mac to be able to sign the binaries (not sure about that). 

Many CLI users know about these things.

Should be in the final docs.

**Comment by corneliusroemer** [comment]
Thanks! This should maybe be indicated better on the nextclade website. If you put a release there that I can download there should be a note that you need to do xyz to make it work.

**Comment by ivan-aksamentov** [comment]
This is now explained in the [user documentation](https://docs.nextstrain.org/projects/nextclade/en/stable/user/nextclade-cli.html#installation-local). Should be good enough.
