### ISSUE TITLE
planning ahead for dockerhub pull limits

### ISSUE THREAD

**Issue by kapsakcj** [nextstrain/nextclade#483]
Hi Ivan and the Nextstrain/Nextclade team,

First - thanks for developing and maintaining such an awesome set of tools. They have been invaluable to have during this pandemic.

Second - I was curious to see if you all have encountered dockerhub pull limits with the nextclade docker images (or any of the various containers that you host on dockerhub). I haven't been hit by pull limits with the nextclade images yet, but have with a few of the [images hosted by the StaPH-B group](https://github.com/StaPH-B/docker-builds) (of which I'm a contributor). Due to this, we have applied for the [Docker Open Source Program](https://www.docker.com/blog/expanded-support-for-open-source-software-projects/), which removes the docker pull limits that were introduced last November.

Docker was kind enough to approve our application today, and soon all the StaPH-B images will no longer be affected by the pull limits 🎉 

I would like to encourage & ask you all to do the same, to ensure no one is hindered from using your amazing tools. @k-florek was the one who applied for our group and said it was a relatively painless process. Only took a couple of weeks to get approval.

One other workaround would be to mirror docker images on quay.io, which should not have any pull limits as long as your repositories are publicly visible. I have found [`skopeo` to be a great tool ](https://github.com/containers/skopeo)for easily syncing docker images between dockerhub and quay.io 

Best,
Curtis

**Comment by kapsakcj** [comment]
Ah! This is related to #422

**Comment by ivan-aksamentov** [comment]
Hi Curtis @kapsakcj,

Thanks for sharing. Yes, we might do that. I'll talk with the team.

**Comment by ivan-aksamentov** [comment]
This was setup internally some time ago. Thanks gain Curtis for heads up!
