### ISSUE TITLE
Nextclade CLI throws error `File not found: ""` instead of more descriptive error

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#489]
On Mac, when I run nextclade with just an input fasta file specified (any file that exists does here, it's not checked for content, just for existance), I get an error saying `File not found: ""` rather than a more informative error message that tells me that some concrete required arguments/flags are missing.

Minimal reproducible example (just make sure you use a file that actually exists, in my case `README.md`):
```
❯ /Users/cr/code/nextclade/.build/Debug/packages/nextclade_cli/nextclade-MacOS-x86_64 --input-fasta=README.md 
[ERROR] Nextclade: Error: File not found: "". Please verify correctness of input flags. If a dataset is used, check that the dataset is not corrupted.
```

**Comment by ivan-aksamentov** [comment]
I am confused. Does this only happen on the `feat/data-distribution` branch? It's not finished yet, so these things are definitely possible.

Let me know if you also notice this on the release version or on master. That would be an urgent problem to solve then and to release a fix.

**Comment by ivan-aksamentov** [comment]
I checked the release version 1.2.0 and it's not the case. So I assume it's the problem on `feat/data-distribution` only.

**Comment by corneliusroemer** [comment]
My bad, it's on `feat/data-distribution` as you guessed correctly.
