### ISSUE TITLE
Feat: Output aligned nucleotide sequences per gene

### ISSUE THREAD

**Issue by bigben446** [nextstrain/nextclade#500]
nextclade.gene.<gene_name>.fasta-**NA**  - aligned **nucleotide sequences** corresponding to each gene

by the **Nextalign CLI alignment tool for command line**

**Comment by corneliusroemer** [comment]
Do I understand it correctly that you're making a feature request for the coding nucleotide sequence of each gene to be output by Nextalign (part of Nextclade) as well?

It would help if you could explain a bit more about the motivation for your request. Why do you think it'd be useful? What's the current alternative and why is it not good enough?

**Comment by bigben446** [comment]
Thank you for your reply.

I found that for the comparison of large amount of virus genomes, such as hundreds of thousands of new coronavirus genomes, Nextalign CLI alignment tool for command line is the most efficient and fastest, much faster than the commonly used mafft.

However, after viral genome alignment, it is often necessary to extract the nucleic acid sequences of viral genes for the next step of analysis, such as evolutionary tree analysis. Nextalign is very convenient for sequence alignment of viral genomes, peptide sequences of viral proteins and, I believe, nucleic acid sequences of viral genes.

**Comment by bigben446** [comment]
Thank you for your reply.

I found that for the comparison of large amount of virus genomes, such as hundreds of thousands of SARS-2 genomes, Nextalign CLI alignment tool for command line is the most efficient and fastest, much faster than the commonly used mafft.

However, after viral genome alignment, it is often necessary to extract the nucleic acid sequences of viral genes for the next step of analysis, such as evolutionary tree analysis. Nextalign is very convenient for sequence alignment of viral genomes, peptide sequences of viral proteins and, I believe, nucleic acid sequences of viral genes.


> Do I understand it correctly that you're making a feature request for the coding nucleotide sequence of each gene to be output by Nextalign (part of Nextclade) as well?
> 
> It would help if you could explain a bit more about the motivation for your request. Why do you think it'd be useful? What's the current alternative and why is it not good enough?

**Comment by corneliusroemer** [comment]
Thanks for explaining. Are you aware that you can simply get the nucleic acid sequence from the aligned output by using gene start and end positions from a genemap? This can be achieved in a few lines of code in a Python script, for example.
