### ISSUE TITLE
Cannot have nextclade dataset working

### ISSUE THREAD

**Issue by sybrohee** [nextstrain/nextclade#517]
Hi,

I tested the docker versions of nextclade (1.2.3 and 1.2.1) as well as the nextclade executable (linux).

From the readme file of the data repository, I understood that I had to use to the nextclade dataset command. However, it seems that the nextclade command does not accept the dataset argument.

```
$nextclade dataset       
Error: ErrorCliOptionInvalidValue: Error: argument `--input-fasta` is required
```

```
$nextclade dataset get --name='sars-cov-2' --reference='MN908947' --output-dir='data/sars-cov-2_MN908947'
Error: OptionParseException: Option ‘name’ does not exist
```

I am surely doing something wrong but I really don't know what. Hopefully, you can help me.

Kind regards,

Sylvain

**Comment by sybrohee** [comment]
Dear Ivan,

Thank you for your fast answer. I think I'll wait for the docker image containing the dataset feature!

Again, thank you for answering and for the time you spent on this really nice tool.

Regards,.

**Comment by ivan-aksamentov** [comment]
Hi @sybrohee,

Nextclade CLI 1.3.0 with datasets feature have been released earlier today. Please give it a new try!

Changelog and binaries: https://github.com/nextstrain/nextclade/releases/tag/1.3.0

Docker tags: https://hub.docker.com/r/nextstrain/nextclade/tags
(run `docker pull nextstrain/nextclade` to get the fresh version)

**Comment by sybrohee** [comment]
Many thanks for telling me. I'll do it really soon.

Sylvain
