### ISSUE TITLE
[Nextclade Web] Improve dataset selector

### ISSUE THREAD

**Issue by ivan-aksamentov** [nextstrain/nextclade#521]
The dataset selector is currently implemented as a dropdown above the file drop box.

There is very little space available and the text is crammed into multiple lines. Also it might be challenging for users to select datasets as the number of datasets is expected to grow substantially in the future.

We might implement a better dataset selector widget.

I can think of a table, which displays 1 dataset per row. Clicking on a row or on a "Load" button in the row would load the dataset.

We could group rows by pathogen and ref sequence, as well as allow to optionally show older versions. We might display more useful information and even provide links for downloading zip archives of datasets.

The table would go to the left side of Nextclade main page, replacing the "marketing" widget.

Related:
  - #520

**Comment by ivan-aksamentov** [comment]
#525 implements this

**Comment by corneliusroemer** [comment]
Resolved by #525
