### ISSUE TITLE
when build wasm locally, it fails with BUILD_ARCH unknown.

### ISSUE THREAD

**Issue by modoree** [nextstrain/nextclade#541]
I am using Linux system below.
  Linux nextstrain 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux

and this system's uname command with option -p or -i returns "unknown". 
as a result of that, build_locally.sh is failed around line 65.

Thank you.

**Comment by ivan-aksamentov** [comment]
Hi @modoree,

Sorry for the trouble. Your message does not tell me much. Please provide the full log verbatim. 

If you think that the problem with line 65 assigning "unknown", and if your machine is x86_64, feel free to change the `BUILD_ARCH` manually

```diff
- BUILD_ARCH="$(uname -p || uname -m)"
+ BUILD_ARCH="x86_64"
```

But that's just a guess at this point, as I don't have pretty much any information about what exactly you are doing and what happened.

**Comment by reyus2** [comment]
I modify it as below and solve it. thank you. 

BUILD_ARCH="$(uname -m)"
