### ISSUE TITLE
High quality SARS-CoV assemblies fail to align on NextClade Webserver

### ISSUE THREAD

**Issue by brittanysuttner** [nextstrain/nextclade#567]
Hello, I have assembled a complete SARS-CoV genome from some control RNAseq datasets. These are very high quality assemblies (i.e. single contig of target expected length for SARS-CoV genome and matches with 100% coverage and 99% ID to SARS-CoV on NCBI blast websit). However, when I try to type these on NextClade webserver, I get an error that says, "Unable to align: no seed matches". I have attached the two genomes in the fasta text file. Do you see any issue with these and can say why they are failling to complete clade typing on the webserver?
[BA426_427_CoV-scaffolds.fa.txt](https://github.com/nextstrain/nextclade/files/7325052/BA426_427_CoV-scaffolds.fa.txt)
"

**Comment by ivan-aksamentov** [comment]
I submitted a feature request to allow for reverse-complemented sequences: https://github.com/nextstrain/nextclade/issues/569
