### ISSUE TITLE
Is there a way to disable output of alignments/gene extraction?

### ISSUE THREAD

**Issue by charlesfoster** [nextstrain/nextclade#570]
Hi,

Thanks for the useful tool. I'd like to use nextclade_cli in a pipeline purely to get the `*..auspice.json` and `*.tsv` (clade assignment, QC etc.) files. I don't need the other output files, including extraction of genes into individual files, or an alignment.  Is there a way to disable these files being output? Or do I just need to unfortunately delete them post-hoc?

I tried reading through the help online and for the version I'm currently using (v1.4.1 via Docker).

Cheers,
Charles

**Comment by charlesfoster** [comment]
Thanks for the fast response. I had wondered about whether the alignment, peptides etc. were needed for the final QC results. 

For now, I can add a rule to my workflow to collect and remove the alignments etc. - no problem. Moving forward, if there were to be an added option to the cli, I suppose there might be flags to stop the creation/saving of output fasta files for the alignment and the extracted genes. Something like:

```
--no-output-alignment      Disable output of aligned input sequences
--no-extracted-genes       Disable output of extracted protein-coding genes from input sequences
--peptides-only            Only output translations of extracted protein-coding genes (no nucleotide sequences)
--nucleotides-only         Only output nucleotide sequences of extracted protein-coding genes (no peptide sequences)
```
Obviously some of these would be mutually exclusive, and the wording might need to be finessed. Not sure how they would work, either. Intermediate files sent to /tmp or /dev/null? Or written to disk then removed? 

Cheers,
Charles

**Comment by rneher** [comment]
v2 can do this.
