### ISSUE TITLE
Using Nextclade for clade assignment with short stretches, such as Spike only

### ISSUE THREAD

**Issue by gbbio** [nextstrain/nextclade#571]
I noticed that nextclade works if I only give the S gene sequence as input instead of the full genome. The nextclade.tsv file does not show any errors as far as I can see and I get a clade classification. I wonder if someone knows if the output is reliable because there are some clade specific mutations outside the S gene.

I see a warning icon in the webinterface but it does not indicate that it is not possible. It just tells that ORF1a is not included in the alignment for example. I think I was expecting a "sequence to short" error so got curious.

**Comment by ivan-aksamentov** [comment]
This pull request may bring some improvements to the analysis of short/incomplete sequences https://github.com/nextstrain/nextclade/pull/613

**Comment by corneliusroemer** [comment]
The 20I/B misassignment was fixed with the most recent dataset release. The misassignment was likely caused because the spike was closer to the recombinant XA than B.1.1.7

We're now excluding recombinants pango lineages so assignment using Spike only should be more stable.

**Comment by corneliusroemer** [comment]
This should sort of work now - though there will be much uncertainty with short sequences as there's much less phylogenetic information. We're working on surfacing placement uncertainty.

**Comment by gbbio** [comment]
Even closed I can still leave a comment. At the time this was solved by removing the recombinants, after the removal clade 20I and 20B where classified correct with spike only most of the time (on top of my head). For a long time spike only was good enough but not anymore. In my latest test it looks like 22B can not be classefied with spike only and 22C had a 9% incorrect classification **on my set on spike only**. This is all very logical but just for people that are going to try it keep it in mind.

**Comment by corneliusroemer** [comment]
Are you using the non-recombinant dataset for this?

That should work much better for Spike only.
