### ISSUE TITLE
[docs] Nextalign quick example uses outdated way to download example dataset

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#584]
Spotted by @kevinlibuit here: https://github.com/openjournals/joss-reviews/issues/3773#issuecomment-953199551

> [I] noticed that the NextAlign quick example suggests grabbing data files from the defunct data/sars-cov-2 directory.
>Would be great if there was a similar nextalign dataset get functionality to grab reference data. Not something super critical to my recommendation for acceptance to JOSS, but this would be very useful for laboratories running these from the nextstrain/nextalign docker image--especially in some kind of larger Augur workflow.

See point 1 in the screenshot below, it should use `nextclade dataset get` or `nextalign dataset get` but I don't think nextalign CLI has this feature.

![image](https://user-images.githubusercontent.com/25161793/139142846-4c3de18c-23c5-4361-82b2-b7fbe035c591.png)

https://docs.nextstrain.org/projects/nextclade/en/stable/user/nextalign-cli.html#quick-example

**Comment by ivan-aksamentov** [comment]
We discussed internally and decided that we keep the files in `data/` for Nextalign, so this remains the recommended way to get data for Nextalign. For Nextclade we recommend using datasets. I will close this for now.

In the future we may (or may not) unify this. Adding networking makes binaries bigger and slower and we want Nextalign to be as fast as possible. Plus, in `data/` we have more pathogens than in the Nextclade datasets. And we currently have a notion of Nextalign dataset. This is something to think about, but does not seem to be a priority currently.
