### ISSUE TITLE
Spike only sequences from VOC alpha aren't assigned the 20I (Alpha) but 20B

### ISSUE THREAD

**Issue by rneher** [nextstrain/nextclade#605]
The presence of recombinant lineage `XA` with Alpha spike in a non-alpha background attracts Spike only Alpha sequences. 

Unsure how to handle this, but as a stop-gap solution we could remove recombinant lineages from the reference tree.

**Comment by corneliusroemer** [comment]
Since I've implemented only the stop-gap solution, I'll reopen and label with `hard problem`.
