### ISSUE TITLE
Questionable amino acid alignments when there are frame shifting deletions

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#608]
Sequences: 
[sequences.txt](https://github.com/nextstrain/nextclade/files/7547023/sequences.txt)

Screenshots
![image (5)](https://user-images.githubusercontent.com/25161793/142002359-f3a8b27e-0ec2-43e8-b0d9-68de35492a49.png)
![image (6)](https://user-images.githubusercontent.com/25161793/142002363-aa797b00-0ba5-46f1-af03-5b84de8c61ca.png)

**Comment by corneliusroemer** [comment]
Possibly related to #565 and #507

**Comment by rneher** [comment]
related to #565, but not #507

**Comment by rneher** [comment]
should be closed by #613

**Comment by corneliusroemer** [comment]
Yes, this is resolved
![image](https://user-images.githubusercontent.com/25161793/145051447-97379261-7d14-4c8e-b8b9-71fe897795d5.png)
