### ISSUE TITLE
Spurious and wrong deletions in Spike when aligning with Nextalign

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#609]
Cross-post from https://discussion.nextstrain.org/t/large-novel-spike-deletions-of-unknown-origin-not-reproducible-outside-nextstrain-framework/845

Minimal reproducible example sequences: https://gitlab.com/-/snippets/2206864

![image](https://user-images.githubusercontent.com/25161793/142003897-d07dcf34-9cf6-4782-a506-9fd4107c6686.png)

Original report by Guy Shapira:
> I was alerted by my colleagues that a newly sequenced SARS-CoV-2 sample had multiple novel deletions in the starting amino acids of the Spike protein.
>
> Bracing for another variant of concern, I ran the sequencing data through my own pipeline (bwa-mem2+iVar) and submitted both to nextclade.
>
> Nextclade identified large Spike deletions in both sequences:
>
> However, I could not find a single indication of these deletions outside of the nextclade results.
>
>Both consensus sequences had the Spike start codon fully in-tact.
>
> My variant caller (iVar) found no such deletions, save for the well known ones further down the gene (69-70 and so forth).
>
> Other tools, such as the GISAID CoVsurver and cov-glue, didn’t find anything out of the ordinary either.
>
> The consensus sequences (same sequencing data, different piplines) can be obtained here.
>
> Do you have any idea what happened here?

Response from @rneher:

> Thanks for flagging this. You are right, these deletions aren’t real.
> 
> the reason seems to be that the amino acid alignment is thrown off by the large numbers of N early in the sequence preceding the deletion around position 65 in spike. We’ll try to fix…

**Comment by rneher** [comment]
@ivan-aksamentov can be make this function skip the `seedAlignment` when `shift` and `bandwidth` are provided as arguments?

https://github.com/nextstrain/nextclade/blob/master/packages/nextalign/src/align/alignPairwise.cpp#L449

Then we could replace this call

https://github.com/nextstrain/nextclade/blob/master/packages/nextalign/src/translate/translateGenes.cpp#L136

with one that already provides `shift` and `bandwidth` and skip the seed matching. We would also be able to get rid of the amino acid seed matching command line arguments. 

We reason we can do this is that we already know the rough alignment from the nucleotide sequences. The bandwidth would simply be 

`bandwidth = `max(query.size() - query_stripped.size(), ref.size() - ref_stripped.size())/3 + 3;`

(plus there is some buffer). 

The shift would be `shift = bandwidth/2`

**Comment by corneliusroemer** [comment]
It looks like #609 is fixed by this PR now! Well done 🎉 
![image](https://user-images.githubusercontent.com/25161793/143150304-0fef47b0-7f8c-4017-af23-31ef41d5886d.png)
![image](https://user-images.githubusercontent.com/25161793/143150309-03c52a90-7f1c-4d39-a98d-ee2f8e439960.png)
