### ISSUE TITLE
Allow examples sequences to be loaded together with user submitted by ticking of checkbox

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#639]
When investigating whether a particular sequences is a contaminant or recombinant, I need to take that sequence in question and spike in some other clades like Delta, Alpha etc.

This is a bit annoying manually, it would be great if there was a checkbox where I could append the example sequences to my user submitted sequence.

**Comment by rneher** [comment]
this would be quite useful... but we would probably want this to be high quality sequences, rather than our examples with variation in quality.

**Comment by ivan-aksamentov** [comment]
As a first step I might try to allow dropping or selecting multiple files in Nextclade Web. This way you could provide one file with background sequences and another with the spiked ones.

Checkbox with example sequences might be trickier, and will require moving things around quite a bit.

**Comment by corneliusroemer** [comment]
What if you make ticking of checkbox act like a file being downloaded from URL, while other one is dropped/pasted?

The pain points are twofold right now: 1. Getting the comparison sequences, 2. Joining them together manually

Your suggestion would fix 2, while also being generally useful in broader use cases.

**Comment by ivan-aksamentov** [comment]
> What if you make ticking of checkbox act like a file being downloaded from URL, while other one is dropped/pasted?

Not how it works currently. These 2 places are far away from each other.

**Comment by ivan-aksamentov** [comment]
Implemented in https://github.com/nextstrain/nextclade/pull/859, https://github.com/nextstrain/nextclade/pull/1082
