### ISSUE TITLE
Previous assignation 20C now report 20A

### ISSUE THREAD

**Issue by nbargues** [nextstrain/nextclade#650]
Hi,

Since this week I have an assignation 20A for certain sample that are supposed to be 20C if you have a closer look of the SNP list.

I also re-run certain sample from last week that had a 20C assignation and now their are identified as 20A.

What has changed since this week ? 

I noticed you update from 1.9.0 to 1.10.0, is that why I have this change ?

Regards

**Comment by corneliusroemer** [comment]
Hi Nick,

Clade assignment is done by nearest neighbour placement on a reference tree (you can have a look at how this works by going to https://clades.nextstrain.org/ click `show me example` then click on tree symbol at the top right):
![image](https://user-images.githubusercontent.com/25161793/145852585-49544c4a-73ac-40db-8609-c32636aa6057.png)

We update the reference tree regularly, you can see the changelog here: https://github.com/nextstrain/nextclade_data/blob/master/CHANGELOG.md

It is possible that clade assignments change a little bit from version to version, but the changes should be small, we do check that there are no big movements.

Nextclade software updates (in contrast to Nextclade data updates) like 1.9.0 to 1.10.0 should only very unusually have an impact on clade assignments.

If you give me the strain names or EPI_ISLs of the sequences in question, I can have a look at what happened.

Best, Cornelius

**Comment by nbargues** [comment]
Hi Cornelius, 

Thanks for the quick response. 

The samples that used to be assigned 20C and are now 20A have the same lineage B.1.640

Regards

**Comment by corneliusroemer** [comment]
Thanks for getting back with specifics. Could you please share a few strain names?

B.1.640 is under 20C in the current reference tree: https://nextstrain.org/groups/neherlab/ncov/nextclade-reference/2021-12-06-draft

And it was there in the previous version too, so I'm not quite sure what's going on. Without a sequence there's not much I can do.

**Comment by corneliusroemer** [comment]
@nbargues I edited my post above, now it's correct. You may not get an email/notification that it change so wanted to let you know like this.
