### ISSUE TITLE
Clade graph needs updating for Omicron and Delta 21I/J

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#657]
This is how it looks right now, we need to add 21H (Mu), 21 I/J (Delta), 21 K/L/M (Omicron)

![image](https://user-images.githubusercontent.com/25161793/147007487-0cbe1cb2-1c8f-44d7-bbb8-ffd149ec0da1.png)

**Comment by ivan-aksamentov** [comment]
The schema now lives in
https://github.com/nextstrain/ncov-clades-schema
and can be updated and generated there

**Comment by corneliusroemer** [comment]
Fab, I'll take it from here, generating the clades.json from the hierarchy.tsv

**Comment by ivan-aksamentov** [comment]
Not sure if we need that level of complexity, but if science calls, then why not. I'd simply add a couple of JSON objects manually.

**Comment by corneliusroemer** [comment]
There will be more clades to come and automation reduces errors. I'm on holiday anyways so this is a fun challenge :D

**Comment by corneliusroemer** [comment]
It's up to date now: https://github.com/nextstrain/ncov-clades-schema/blob/master/clades.svg

**Comment by ivan-aksamentov** [comment]
This was resolved in #666
