### ISSUE TITLE
ENH: Add QC rule to spot potential contamination/co-infection/recombination

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#662]
For various reasons, it can happen that a sequence is a patch work from two or more clades.

It might be helpful if Nextclade flagged such sequences through a new QC rule.

The algorithm could be as simple as:
1. For each major clade, count how many of the private mutations occur in it

Say if the sequence is placed as Omicron, but has private mutations 681R, 452L, it would be flagged as potential Delta contamination/co-infection/recombination.

Motivation: There've been quite some issues with Omicron being contaminated by Delta. With our current QC rules, we are not very sensitive to this with up to ~20 private mutations being OK. With a specific contamination QC rule we could already notice something up with just 2 private mutations.

See for example this case where such a QC rule may have helped: https://twitter.com/AdrianaHeguy/status/1477053001676300289?s=20

**Comment by rneher** [comment]
I think should be fairly straightforward to implement. We would need to have access to the `mutations -> clade` map here:

https://github.com/nextstrain/nextclade/blob/master/packages/nextclade/src/qc/rulePrivateMutations.cpp#L92-L109

We would need to extend the corresponding result type:
https://github.com/nextstrain/nextclade/blob/4f236b58277bdaef72e2f84d26207dbbbc0b8502/packages/nextclade/include/nextclade/nextclade.h#L28

to contain the break down of mutations into `reversions`, `other_clade_mutations`, and `unassigned` mutations.

**Comment by corneliusroemer** [comment]
Reversions can be identified as such in this branch:
https://github.com/nextstrain/nextclade/blob/ce16aa0d35573e429a22497c5853ee1185577cc3/packages/nextclade/src/tree/findPrivateMutations.cpp#L234

The `SubstitutionSimple` could be extended with a boolean property `reversion` that's true in this branch and false in the rest.
