### ISSUE TITLE
ENH: Display ambiguous mutations in gene/nuc view tooltip

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#700]
Ambiguous nucleotides are currently displayed only in the tooltip of the corresponding column:
![image](https://user-images.githubusercontent.com/25161793/151008404-192877fc-f898-4406-96d8-d350ca9ec79d.png)

In gene view, ambiguous bases turn the corresponding AA into an X. It would be nice, if the X tooltip showed corresponding ambiguous nucleotides, like AA mutation tooltips show the mutated nucs.

Current:
![image](https://user-images.githubusercontent.com/25161793/151008857-822ef143-8792-4fba-9b87-252121a6c8b9.png)

Something like this would be cool, potentially even with a range of possible amino acids that is compatible with the ambiguity.
![image](https://user-images.githubusercontent.com/25161793/151008890-cde13239-1869-4bcf-9092-00e186565f9a.png)

**Comment by ivan-aksamentov** [comment]
The translation of ambiguous nucs is a cool feature we discussed with Richard even in the early days of Nextclade. It can be implemented quite easily, by modifying the [decoding map](https://github.com/nextstrain/nextclade/blob/af35dfa8fed04c362ec80aac2650d0a45fdbed7d/packages_rs/nextclade/src/translate/translate.rs#L11-L78). Someone needs to actually build the map and put triplet-to-aa entries above the catch-all case which resolves to AA `X`.

The coolness of this I see in that it will reduce the number of `X`, and salvage some amount of useful info even from mediocre data.

Regarding showing how ambiguous nucs and AAs are linked - it's trickier. We currently don't track why an AA became an `X` and there are multiple reasons. Also X are tracked as ranges, and within a range there could be multiple reasons by itself, so some deeper code changes will be needed.

**Comment by corneliusroemer** [comment]
Just wanted to open a duplicate then found this: I was surprised that we don't indicate ambiguous nucleotides in the nuc view. Quite unexpected, I think we don't need to overcomplicate things: just add them like a single missing nuc.
<img width="174" alt="image" src="https://github.com/nextstrain/nextclade/assets/25161793/2ed6f0bd-0290-4978-aec6-d20af7c8b329">

**Comment by corneliusroemer** [comment]
Some shade of grey would be the obvious choice I think. Doesn't matter so much what it is, as long as there's something that can be hovered to see extra information.

I don't think we need to add anything related to AA there, just showing that there might be something in nuc view is good enough. Just putting the relevant entry from the table tooltip into the marker tooltip would be great:
<img width="349" alt="image" src="https://github.com/nextstrain/nextclade/assets/25161793/c89acbad-99ec-4c80-9630-0f6fb8280e91">

While we're at it, it would be neat to maybe add what the various ambiguity codes stand for. This is a simple lookup:

```
R = A or G
K = G or T
S = G or C
Y = C or T
M = A or C
W = A or T
B = not A (C, G or T)
H = not G (A, C or T)
D = not C (A, G or T)
V = not T (A, C or G)
```

So the tooltip could read:
```
Ambiguous 
11514: Y (C or T)
```

**Comment by corneliusroemer** [comment]
Would be great to add this @ivan-aksamentov - this would have really helped me some time investigating this case: https://github.com/yatisht/usher/issues/354 - not showing ambiguous nucs/aa would be a big win for the sequence viewer. Color doesn't really matter, we can always tweak later.

**Comment by ivan-aksamentov** [comment]
@corneliusroemer prototype is here: https://github.com/nextstrain/nextclade/pull/1273
