### ISSUE TITLE
BUG/Visual: Display positions of single N markers differ slightly from non-Ns in nuc seq view

### ISSUE THREAD

**Issue by danrlu** [nextstrain/nextclade#708]
Nextclade is SO useful. Thank you for building it and always improving it!! 

We noticed a minor issue. We have 2 sequences, 1 has lots of Ns where they are mutations in the other sequence. The bars don't quite line up:

![image](https://user-images.githubusercontent.com/20667188/151392005-b53ffb54-86fc-4a69-b562-94b8256d8971.png)

Take the blue bar for example:
The position of N:
![image](https://user-images.githubusercontent.com/20667188/151392415-aa9dc5c0-c236-46f7-87d4-d79a75cdafdf.png)

The position of blue bar:
![image](https://user-images.githubusercontent.com/20667188/151392492-376d7526-2bfd-49b9-ae47-6a1839ee6ab3.png)

The yellow bar:
![image](https://user-images.githubusercontent.com/20667188/151392597-04b0117f-013d-4367-a8a0-1c9a790f7539.png)

![image](https://user-images.githubusercontent.com/20667188/151392631-9501b1c0-cbac-437c-9a84-af522ffd678c.png)

**Comment by corneliusroemer** [comment]
Thank you very much for reporting this issue. I agree that single Ns should align with single substitution markers.

The root problem is that to make markers visible, they are magnified. We've tried to improve alignment in the past, centering ranges of mutations - but we may have forgotten about Ns, or single Ns.

May be related to either or both of these commits: https://github.com/nextstrain/nextclade/commit/4048a7b6c959c716fffd5ff79ea485bd0a17cfa2 https://github.com/nextstrain/nextclade/commit/e0d3b379ea006e65e5ccdd3082cba59ebda9fef0

**Comment by rneher** [comment]
this is likely due to one of markers being centered and the other left-aligned. We changed mutations to be centered a while back, but might not have handled the missing marker the same way.

**Comment by ivan-aksamentov** [comment]
I attempted to address this and a similar issue with other sequence markers in the PR https://github.com/nextstrain/nextclade/pull/709

@danrlu Could you please check if it looks any better with the fix, by using this preview app:
https://nextclade-git-fix-center-markers-nextstrain.vercel.app/
?

**Comment by danrlu** [comment]
Beautiful! Thank you all!!
![image](https://user-images.githubusercontent.com/20667188/151428200-3c2e77e9-e9e9-480d-a640-d2739f158af6.png)
