### ISSUE TITLE
G21987A included in labeledSubstitutions even though sequence assigned to 21J

### ISSUE THREAD

**Issue by AngieHinrichs** [nextstrain/nextclade#711]
First, thanks for adding the privateNucMutations columns!  🚀 

If I understand correctly, when a sequence is assigned to a clade, mutations associated with that clade will *not* be counted against it in labeledSubstitutions.  For example, if a sequence is assigned to 20B, then it is expected to have the 20B-defining mutations at 28881, 28882 and 28883 and those mutations will not appear in labeledSubstitutions.

However, COG-UK sequence England/QEUH-2F63613/2021 is assigned to 21J (Delta) but also has "G21987A|21J&21I&21A&21L&21B" in labeledSubstitutions -- even though G21987A is expected in Delta and 21J is included in the &-separated list.  I would expect the 21J in the &-separated list to prevent G21987A from being included in labeledSubstitutions.

**Comment by AngieHinrichs** [comment]
(All COG-UK sequences are freely available from https://www.cogconsortium.uk/tools-analysis/public-data-analysis-2/ ; I'm attaching [QEUH-2F63613.fa.gz](https://github.com/nextstrain/nextclade/files/7954254/QEUH-2F63613.fa.gz) here for convenience.  I'm using nextclade version 1.10.1 with dataset downloaded two days ago, tag 2022-01-18T12:00:00Z.)

**Comment by corneliusroemer** [comment]
Thanks for raising this issue. I think a case can be made for both conventions: including and excluding from the list of labeled mutations.

One argument for including is that if that sequence was clean, why doesn't it attach to a node that includes that mutation. Not all labeled mutations occur at 100% in a clade, the threshold is >30% or at least 100k sequences. So something like S:145H would be labelled if it were to be a private mutation within 21J. In that case, it's a sign of potential contamination/recombination (or homoplasy) if the attachment node doesn't contain S:145H.

This is definitely something that can be discussed. I think one reason for doing it the current way is that it's easier to implement and the impact is unlikely to be massive.

**Comment by rneher** [comment]
I think this is the expected behavior. We have made the decision to not only label mutations that are at 100% within a clade, but also label significant within-clade variation. I think private mutations like this should be labeled, even if the that mutation belongs to the same clade as the attachment node.

**Comment by AngieHinrichs** [comment]
OK, I didn't realize that being considered a *private* mutation according to placement in the tree is what determines inclusion in labeledSubstitutions (if I'm interpreting your comments correctly) -- I assumed it was any mutation associated with clade(s) other than the one that was assigned.

> One argument for including is that if that sequence was clean, why doesn't it attach to a node that includes that mutation.

In this particular case, I guess because the node was affected by whatever made G21987A problematic in Delta?  🙂   

But for my purposes, it's easy enough to parse labeledSubstitutions and remove items from the assigned clade.
