### ISSUE TITLE
Spike details column

### ISSUE THREAD

**Issue by fnaveca** [nextstrain/nextclade#715]
First of all, Nextclade is a wonderful and very usefull tool, congrats. I suggest including columns with specific reports for the Spike. For example, missing nucleotides in the spike coding region. This would allow other analyzes to be more straightforward.

**Comment by corneliusroemer** [comment]
I'm glad you find Nextclade useful.

I think you're suggesting two things:
1. Add position of missing nucleotides to tsv/csv
2. Add columns specifically for spike

Incidentally, I've actually noticed the lack of missing nuc / `N` positions as well. I'll open a separate targeted enhancement proposal for this.

Regarding the extra column just for spike: while it may be convenient to have such a column, if we added a column for everything that was convenient, the files would grow even further in size and have redundancy, something that's to be avoided.

With a little bit of scripting, you can create such a column yourself. The AA mutations are already marked as `S:`, for nucleotide mutations, you can simple use everything between `21563-25384`. Same would be true if there were missing nucs in the output files.
