### ISSUE TITLE
PERF: Slow start of analysis when more than 1 thread used on M1 mac

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#717]
Raised by Stacia Wyman (through CDC Spheres)

Analysis startup takes ~20 seconds when using more than 1 thread with Nextclade web on a recent (i.e. probably M1) Mac (browser unknown as of now).

**Comment by ivan-aksamentov** [comment]
In this formulation, this is not something I can help with immediately.

I'd say 20 seconds is not too bad for a laptop. Nextclade is computationally expensive and loads large WebAssembly modules from network. The "startup" actually includes some of the computation. 

Running on AC power, closing the unused tabs (especially other copies of Nextclade), and freeing up some memory might help.

We might make the startup status messages more clear, to give a better idea about what's happening.

There's of course always a room for improvement of performance. But as soon as it's decent for most users, I think we should be focusing on features.

**Comment by corneliusroemer** [comment]
The interesting apart was the "more than 1 thread"

I'll try to find out more about the exact conditions.

I agree this isn't high priority.

**Comment by corneliusroemer** [comment]
Stale, I think this should be solved by now
