### ISSUE TITLE
Inconsistency in how Ns are handled for genes vs nucleotide view

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#730]
When I upload a partial genome, it is not evident in gene view that there are missing parts. It looks like the sequence is equal to reference in parts that are cut out.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/25161793/153910823-77d2eb5f-b03a-416f-8c96-c31efe883b91.png">

The same is true for the column `Ns` or `missing`. It doesn't count missing parts of the genome.

In nucleotide view, however, unsequenced parts are marked up and distinguishable (grey, with tooltip).

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/25161793/153910797-2a18c7d7-a639-42d0-9ee8-20d11680ccc3.png">

It may be good to surface missing beginnings and ends in gene view and in the `Ns` column tooltip. I think we have the information, it should be available through alignment start/end. It could be displayed in the same tooltip but under a separate heading (as missing start/end) and maybe counted in parentheses (like we display known frame shifts).

**Comment by corneliusroemer** [comment]
To reproduce, you can use this sequence
[short.txt](https://github.com/nextstrain/nextclade/files/8063045/short.txt)

**Comment by ivan-aksamentov** [comment]
> missing beginnings and ends

They are mentioned in the alignment start and end. However it is unclear how to map that to aminoacids.

**Comment by corneliusroemer** [comment]
Spotted someone raising this issue independently in the wild. Would be great if we could display alignmentStart/End on the gene view
https://github.com/cov-lineages/pango-designation/issues/843#issuecomment-1196584005
