### ISSUE TITLE
flag to print shortenered list of dataset

### ISSUE THREAD

**Issue by ammaraziz** [nextstrain/nextclade#739]
When running `nextclade dataset list` the output is ~200 lines of information. The number of datasets may grow in the future and so would the output. It would be super handy to have a flag that reduces the verbosity of the `list` output. Possible truncated output might be:

```
Dataset
-------
Friendly name        : SARS-CoV-2
Safe name             : sars-cov-2
Default reference   : MN908947 Wuhan-Hu-1/2019
Tag                        : 2022-02-07T12:00:00Z

Friendly name     : Influenza A H1N1pdm HA
Safe name         : flu_h1n1pdm_ha
Default reference : CY121680 A/California/07/2009
Tag                   : 2022-01-18T12:00:00Z
```

Slightly related, the dataset printout has many repeating lines. For example these two lines repeat for every dataset:

> (In this case, repeated downloads may produce updated files in the future: after releases of new versions of this dataset. Reference sequence will stay the same even if the dataset's default changes. If you want to use a specific version, see section "Specific versions" below.)
> (In this case repeated downloads will always produce the same files. This is only recommended if you need strictly reproducible results. Note that with stale data, updated clades and other features will not be available. We recommend to update data periodically.)

Printing them once at the start or end would also reduce the number of lines.

**Comment by ivan-aksamentov** [comment]
Hi @ammaraziz,

True, the current list is horrible. The idea was to expose users to the concept of freezing ref sequence and version, but it all ended up really weird and confusing.

I have some plans for the list command outputs as well for some more output formats (such as JSON) in an upcoming new shiny version of Nextclade. No ETA yet, but it is likely happening.

**Comment by ammaraziz** [comment]
Hi Ivan,

I think the latest nextclade v2 solves this issue! Happy for this to be closed.
