### ISSUE TITLE
Allow submission of multiple input files

### ISSUE THREAD

**Issue by rkdover** [nextstrain/nextclade#740]
Hi Nextstrain team!

I was wondering if you could allow for submission of multiple files for the nextclade pipeline (clades.nextstrain.org). In my organization consensus sequences arrive as a batch of FASTA files, and while it is simple to concatenate these with a script it is a bit of a barrier to entry to less technically experienced colleagues. Shame as it is outstanding in terms of usability!

Thank you for your work!

**Comment by ivan-aksamentov** [comment]
Hi @rkdover,

Yes, this was requested a few times now (e.g. https://github.com/nextstrain/nextclade/issues/342, https://github.com/nextstrain/nextclade/issues/639). Seems like an interesting feature to add.

I will close this issue to avoid duplication, but we've noted your vote on this feature.

**Comment by rkdover** [comment]
@ivan-aksamentov I apologize for the duplicate. I couldn't find the issues you mention. Thanks!
