### ISSUE TITLE
BUG: Mutation at position 1 reported as at position 0

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#745]
Trying out synthetic lineage sequences, I was startled to find that one of them got a nucleotide mutation reported at position 0, which shouldn't be possible in the front end, since there we use 1-indexing.

<img width="333" alt="image" src="https://user-images.githubusercontent.com/25161793/156611323-aee71e05-20d8-45c0-8c60-143722f4f9b3.png">

To reproduce, try this sequence:
https://pastebin.com/raw/6DBJuxiz

It seems like only the 1st nuc is treated wrong. Since when I change the first two nucs to C, the first is reported as `0C`, second as `2C`

Some coordinate system mishap, I think. Worth checking what happens if there's a mutation at the last position. (I just did and it looks good for now).

**Comment by corneliusroemer** [comment]
It could be that the problem is restricted to the front end/web app, since Auspice shows correct mutations:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/25161793/156614059-b5ec94cc-c5c4-434a-978b-3601626e2425.png">

**Comment by ivan-aksamentov** [comment]
@corneliusroemer This should be fixed in https://github.com/nextstrain/nextclade/pull/747. Please double check.
