### ISSUE TITLE
Documentation: Images not found

### ISSUE THREAD

**Issue by chaoran-chen** [nextstrain/nextclade#752]
On the [Quality control page of the documentation](https://docs.nextstrain.org/projects/nextclade/en/stable/user/algorithm/07-quality-control.html), two images are not loaded. The page links to the following two images which, however, are not at the specified location:

- https://docs.nextstrain.org/docs/user/assets/algo_private-muts.png
- https://docs.nextstrain.org/docs/user/assets/algo_private-muts-classification.png

**Comment by ivan-aksamentov** [comment]
Thansk! Fixed in #753
