### ISSUE TITLE
Error in Nextclade-Pangolin annotation

### ISSUE THREAD

**Issue by animesh-workplace** [nextstrain/nextclade#760]
hCoV-19/India/KA-CBR-1402CTD094/2022

[Issue raised for this particular sequences in pangolin-designation](https://github.com/cov-lineages/pango-designation/issues/484)

This is supposed to be a XF lineage (Delta X BA.2 recombination), but nextclade is calling it XE lineage (BA.1 X BA.2). Kindly look into it

![image](https://user-images.githubusercontent.com/55780901/160424731-d9d555b2-7748-4661-99db-9cee64884d81.png)
![image](https://user-images.githubusercontent.com/55780901/160424814-b6da72f5-2a2f-4825-8a91-5c7c2fd82374.png)

![image](https://user-images.githubusercontent.com/55780901/160423301-1a314422-49d1-4197-b0d4-f467a08c3067.png)

**Comment by animesh-workplace** [comment]
![image](https://user-images.githubusercontent.com/55780901/160425804-7e310bf2-8805-480e-96de-ee9bce220ba1.png)
Just my own analysis to showcase the same.

**Comment by corneliusroemer** [comment]
Thanks for raising this.

The software does exactly what it's supposed to. Let me explain.

We find the nearest neighbour in the reference tree for the sample. The pango lineage reported is then that of the nearest neighbour.

If there are lots of reversions and labeled mutations (i.e. `P` circle is red, as in this case) it means that there's no good fit in the tree. So you can't trust the pango lineage reported - it is likely not correct, as in this case.

There's no pango lineage for this sequence (yet) so there's also no right way to call it.

`pangolin` is very conservative, they would give this sequences a label of `None` probably. We just report the likeliest lineage - which can be wrong but may still be informative. In this case, it's correctly classified as a recombinant, though the exact Pango lineage is wrong.

I'll think about whether it might be worth adding parentheses about Pango lineage calls when the results are not trustworthy.

You can read more about caveats here: https://docs.nextstrain.org/projects/nextclade/en/latest/user/algorithm/nextclade-pango.html

It's worth noting that we don't claim to be 100% accurate. 98% accuracy means we expect to be wrong in 1 sequence out of 50. This sequence is very unusual, so it's not surprising Nextclade is wrong.

Also this:
>Recombinants: Recombinant Pango lineages are now included in the reference tree. Each recombinant is attached to the root node so as not to spawn false internal nodes in the tree that would attract bad sequences. As long as recombinants do not qualify for a Nextstrain clade, they will receive the place holder clade name recombinant. Pango lineages are provided if present. Beware that new unnamed recombinants with similar donors but slightly different breakpoint will attach to existing recombinants in the reference tree and thus get a wrong Pango lineage. A number of reversions and labeled mutations is a sign that you may have a similar but different recombinant.
https://github.com/nextstrain/nextclade_data/blob/master/CHANGELOG.md#sars-cov-2
