### ISSUE TITLE
Nextclade web run error with MinION sequences

### ISSUE THREAD

**Issue by Afrad84** [nextstrain/nextclade#762]
I am trying to run the Nextclade with Sars-Cov-2 genomic sequences, and every time I run the sequences it Nextclade shows the following error. The sequence inputs are fasta from Nanopore minION.

An error has occurred.
allocator<T>::allocate(size_t n) 'n' exceeds maximum supported siz
<img width="1287" alt="Screen Shot 2022-03-30 at 7 36 38 AM" src="https://user-images.githubusercontent.com/102636777/160733450-f8eb85d0-caad-43b7-bbd0-26029ad7612e.png">
e

**Comment by ivan-aksamentov** [comment]
Hi @Afrad84,

Could you share an example fasta file that causes this error, in order for me to reproduce and investigate this internally?

What error says is that Nextclade ran out of available memory. This can happen for a variety of reasons:

 - For some low quality sequences, alignment algorithm may consume lots of memory, sometimes more than there's available. Nextclade Web uses WebAssembly underneath, which has a 32-bit architecture, and is limited to 4GB of total memory.
 - You are trying to run too many sequences. In Nextclade Web we recommend running at most a couple of hundreds or so at a time.
 - The number of parallel threads Nextclade is using was not detected properly or you have set it too high. Threads are running concurrently, and each consumes a certain amount of memory. Click "Settings" and try to reduce number of threads to reduce overall memory consumption.
 - Your computer does not have enough system memory available. Either it's a small amount installed physically or it is occupied by other applications and browser tabs. Try to close other applications, and browser tabs. If you have a computer with more system memory available, try that.
 - We [don't recommend](https://docs.nextstrain.org/projects/nextclade/en/latest/user/nextclade-web.html#performance-tips) running Nextclade in Safari browser. It has numerous bugs and sloppy implementation of the web technologies required for Nextclade to run. Try Chrome or any other Chromium-based browser for the best experience.

In the meantime you can also try the [command-line version of Nextclade](https://docs.nextstrain.org/projects/nextclade/en/latest/user/nextclade-cli.html), which does not have these limitations and which you can run on a more powerful machine.

**Comment by Afrad84** [comment]
Hi Ivan!
Thanks for the quick response.
We usually run alignment for 24 sequences (as attached) and these fasta are generated from the Nanopore epi2me software.
We have been using Nextclade over the last 12 months and this kind of issue never happened.
This issue is happening in both Chrome and Safari.

Regards
Afrad



On Mar 30, 2022, at 9:20 AM, Ivan Aksamentov ***@***.******@***.***>> wrote:


External email, use caution



Hi @Afrad84<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAfrad84&data=04%7C01%7Chassan.afrad%40icddrb.org%7Cd89030a87d4f4961dc8a08da11fc3183%7Cebc3b063df9a4de0b42641a71f84e296%7C0%7C0%7C637842072102425163%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wWAyGkntwrpIvnSNyU04aSgISQOsM8wCtZyGBkjJhk0%3D&reserved=0>,

Could you share an example fasta file that causes this error, in order for me to reproduce and investigate this internally?

What error says is that Nextclade ran out of available memory. This can happen for a variety of reasons:

  *   For some low quality sequences, alignment algorithm may consume lots of memory, sometimes more than there's available. Nextclade Web uses WebAssembly underneath, which has a 32-bit architecture, and is limited to 4GB of total memory.
  *   You are trying to run too many sequences. In Nextclade Web we recommend running at most a couple of hundreds or so at a time.
  *   The number of parallel threads Nextclade is using was not detected properly or you have set it too high. Threads are running concurrently, and each consumes a certain amount of memory. Click "Settings" and try to reduce number of threads to reduce overall memory consumption.
  *   Your computer does not have enough system memory available. Either it's a small amount installed physically or it is occupied by other applications and browser tabs. Try to close other applications, and browser tabs. If you have a computer with more system memory available, try that.
  *   We don't recommend<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.nextstrain.org%2Fprojects%2Fnextclade%2Fen%2Flatest%2Fuser%2Fnextclade-web.html%23performance-tips&data=04%7C01%7Chassan.afrad%40icddrb.org%7Cd89030a87d4f4961dc8a08da11fc3183%7Cebc3b063df9a4de0b42641a71f84e296%7C0%7C0%7C637842072102425163%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tAhLf6o9yTxB5i4DH2kVkl6IztMGFUiIv9cypMo3PPQ%3D&reserved=0> running Nextclade in Safari browser. It has numerous bugs and sloppy implementation of the web technologies required for Nextclade to run. Try Chrome or any other Chromium-based browser for the best experience.

In the meantime you can also try the command-line version of Nextclade<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.nextstrain.org%2Fprojects%2Fnextclade%2Fen%2Flatest%2Fuser%2Fnextclade-cli.html&data=04%7C01%7Chassan.afrad%40icddrb.org%7Cd89030a87d4f4961dc8a08da11fc3183%7Cebc3b063df9a4de0b42641a71f84e296%7C0%7C0%7C637842072102425163%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cmG2%2BH6DUlRWLSwCsef6K0gvSD%2BOA0%2FXILkIQNIxevs%3D&reserved=0>, which does not have these limitations and which you can run on a more powerful machine.

**Comment by ivan-aksamentov** [comment]
@Afrad84 I don't see sequences attached. The GitHub email replies don't work well. Please reply on GitHub website instead:
https://github.com/nextstrain/nextclade/issues/762

**Comment by Afrad84** [comment]
Hi Ivan
I could not try over other operating systems over the weekend and this morning I did. Seems like the problem is with my Mac. In windows OS, this worked perfectly.
Thanks a lot for the support.

Regards
Afrad

On Mar 30, 2022, at 10:17 AM, Ivan Aksamentov ***@***.******@***.***>> wrote:


External email, use caution



@Afrad84<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAfrad84&data=04%7C01%7Chassan.afrad%40icddrb.org%7Cffb8fc1bc5354d1eb11d08da120437a3%7Cebc3b063df9a4de0b42641a71f84e296%7C0%7C0%7C637842106567647522%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cpOQ803Z6MtiKgEvZT1dbkfSBkInwQREWOxwfkHpfL8%3D&reserved=0> I don't see sequences attached. The GitHub email replies don't work well. Please reply on GitHub website instead:
#762<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnextstrain%2Fnextclade%2Fissues%2F762&data=04%7C01%7Chassan.afrad%40icddrb.org%7Cffb8fc1bc5354d1eb11d08da120437a3%7Cebc3b063df9a4de0b42641a71f84e296%7C0%7C0%7C637842106567647522%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Un7%2FNjpA59xL8EoqrmLumuu%2BC61KGEQxfAB7MbIjv8Q%3D&reserved=0>

**Comment by corneliusroemer** [comment]
@Afrad84  Let us know if the problem reoccurs, best with files so we can reproduce.

These errors sometimes happen when one navigates back and forth in the browser while analysis is going on.
