### ISSUE TITLE
ENH: Surface insertions in mutation view

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#769]
Apparently there's a Danish BA.2 lineage with an insertion around S:212. BA.1 had an insertion, so did other lineages.

It would be nice if we could show them graphically in the alignment/mutation view, not just in the table.

We'd want to make it visually clear that these are insertions - but I'm sure we can figure something out.

It would be a great addition to see insertions in detail view the same way we show deletions in detail view in tooltips.

I can think of a few ways to differentiate insertion mutation strips from normal mutations: we could make them half height, or have a little bar through them, like we do with frameshifts.

**Comment by ivan-aksamentov** [comment]
This should be pretty easy. `SequenceView` and `PeptideView` components already have all the necessary information passed-into. We just need someone brave to add new marker components (SVG rectangles) by analogy with already existing markers, while I am working on higher priority tasks.

**Comment by rneher** [comment]
We should probably do something not too different from IGV:
https://static.igem.org/mediawiki/2018/thumb/3/3c/T--McMaster--NGS1.png/800px-T--McMaster--NGS1.png
