### ISSUE TITLE
Question about updating datasets

### ISSUE THREAD

**Issue by charlesfoster** [nextstrain/nextclade#770]
Hi,

Thanks for this useful tool. I just have a question about updating the datasets. To initially download the dataset for SARS-CoV-2, I initially run a command like the following:

```
docker run -v $PWD:$PWD -w $PWD -t --rm nextstrain/nextclade:1.11.0-alpine nextclade dataset get --name sars-cov-2 -o $PWD/nextclade_datasets/sars-cov-2
```
This command works well. However, if I want to periodically update the dataset, do I just run the same command again? Will this download all of the files again even if they're the latest version, or will it only download the latest version(s)? 

Something equivalent to `pangolin`'s `--update` option would be ideal. For example, running `pangolin --update` today yields:

```
pangolin already latest release (v4.0.6)
pangolin-data already latest release (v1.6)
constellations already latest release (v0.1.8)
scorpio already latest release (v0.3.17)
```

Thanks!

**Comment by ivan-aksamentov** [comment]
Hi @charlesfoster,

Yes, as explained in the documentation, if you want to get the best results, we recommend to download datasets often. 

In particular, if you are running a pipeline or some sort of automation, we recommend to make the `dataset get` command a part of it. 

Yes, the `dataset get` command will always download and overwrite existing files. Most of the time it will just write the same files, which is somewhat wasteful. It will download new files when a new dataset is released. You can keep track of the new dataset releases here:
https://github.com/nextstrain/nextclade_data/releases

Compared to pango, nextclade datasets are small, about a few megabytes, so they are downloaded almost instantly for most users. It probably does not worth the hassle of implementing version checks. It will be an involved task and we are a small team. Ww prefer to focus on features that have some more scientific impact for now. Contributions are welcome though.

We are considering adding a flag to the `run` command to auto-download the dataset, and avoid an extra step (see https://github.com/nextstrain/nextclade/issues/766).

**Comment by charlesfoster** [comment]
Thanks for the clarification! And a flag to automatically download, as per your comment, sounds great. Cheers.
