### ISSUE TITLE
docs: broken image links on QC page

### ISSUE THREAD

**Issue by victorlin** [nextstrain/nextclade#772]
Example: https://docs.nextstrain.org/projects/nextclade/en/stable/user/algorithm/07-quality-control.html

https://github.com/nextstrain/nextclade/blob/ccf2a0429e239e29a20dd4da1148b908ed2d8515/docs/user/algorithm/07-quality-control.md?plain=1#L51

gets rendered as:

```html
<img alt="Identification of private mutations" src="/docs/user/assets/algo_private-muts.png">
```

and the absolute path is not valid in the context of docs.nextstrain.org/projects/nextclade.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/13424970/165821143-1008337e-d052-4cec-8990-2914e75b8563.png">

---

However, this [Nextclade Web](https://docs.nextstrain.org/projects/nextclade/en/stable/user/nextclade-web.html) image

https://github.com/nextstrain/nextclade/blob/ccf2a0429e239e29a20dd4da1148b908ed2d8515/docs/user/nextclade-web.md?plain=1#L21

gets rendered with a different relative path which is fine:

```html
<img alt="Select virus" src="../_images/web_select-virus.png">
```

Any idea why one works but the other doesn't?

**Comment by ivan-aksamentov** [comment]
Hm... weird stuff. Both work correctly when editing locally with shpinx. Perhaps some misconfiguration? We need someone with a PhD in readthedocs to fix that.

**Comment by tsibley** [comment]
The images appear fine on the "latest" build on RTD: https://docs.nextstrain.org/projects/nextclade/en/latest/user/algorithm/07-quality-control.html.

The links @victorlin posted were to the "stable" build. I wouldn't be surprised if those didn't render correctly locally either, but you'd have to check out the corresponding git commit not `master`.

To investigate, I'd look at what changed in this repo's docs content/setup between latest and stable.

It could also be a bug fix in some dep used during the docs build, and the "latest" build happened to get the newer, fixed version of the dep.

**Comment by tsibley** [comment]
The [RTD build logs for the last "stable" build](https://readthedocs.org/projects/nextclade/builds/16700647/) also show an error:

```
/home/docs/checkouts/readthedocs.org/user_builds/nextclade/checkouts/stable/docs/user/algorithm/07-quality-control.md:: WARNING: image file not readable: /docs/user/assets/algo_private-muts.png
/home/docs/checkouts/readthedocs.org/user_builds/nextclade/checkouts/stable/docs/user/algorithm/07-quality-control.md:: WARNING: image file not readable: /docs/user/assets/algo_private-muts-classification.png
/home/docs/checkouts/readthedocs.org/user_builds/nextclade/checkouts/stable/docs/user/nextclade-web.md:: WARNING: image file not readable: /docs/user/assets/web_select-advanced.png
/home/docs/checkouts/readthedocs.org/user_builds/nextclade/checkouts/stable/docs/user/nextclade-web.md:: WARNING: image file not readable: /docs/user/assets/web_advanced-ui.png
```

**Comment by victorlin** [comment]
QC page on "stable" build has valid image links now:

![image](https://github.com/nextstrain/nextclade/assets/13424970/1e712982-6d73-4005-b019-e7db487a297e)
