### ISSUE TITLE
GUI nextclade gives pangolin lineage will this feature be available for nexclade CLI

### ISSUE THREAD

**Issue by mabvakureb** [nextstrain/nextclade#773]
Hi Nextclade team, I get a pangolin lineage when using the GUI nextclade, will this feature be available for nextclade CLI? And will the nextclade method for assigning pangolin lineages be also made possible in pangolin?

**Comment by ivan-aksamentov** [comment]
Hi @mabvakureb,

> will this feature be available for nextclade CLI?

It should be available. You need to update the dataset with `nextclade dataset get` command. Datasets are equivalent to pango data and they bring [new clades and sometimes new features](https://github.com/nextstrain/nextclade_data/releases), like lineages.

With a fresh dataset you should be able to see the lineages in the TSV and JSON outputs. 

More information is in the docs: 
 - https://docs.nextstrain.org/projects/nextclade/en/stable/user/datasets.html
 - https://docs.nextstrain.org/projects/nextclade/en/stable/user/nextclade-cli.html#quick-example


> And will the nextclade method for assigning pangolin lineages be also made possible in pangolin?

It is probably better to address this question to pango maintainers. I am currently not aware of such plans.
