### ISSUE TITLE
Deletion vs. Missing

### ISSUE THREAD

**Issue by cazzlewazzle89** [nextstrain/nextclade#783]
Hi,

This might be a basic question but how does Nextclade differentiate between deletions and regions that are missing or not sequenced (eg. due to low coverage)?

Thanks,
Calum

**Comment by corneliusroemer** [comment]
Hi Calum,

I'm not sure I completely understand your question. Sequences usually contain `N` for missing/unknown bases. Any `-` contained in the provided sequence are stripped before analysis. This may not answer your question, please rephrase if it doesn't.

**Comment by corneliusroemer** [comment]
Stale
