### ISSUE TITLE
ENH: Show forward and reverse strands in mut view on separate rows, like Auspice does

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#830]
Now that we have a dsDNA virus dataset, it would be nice if the genemap displayed at the bottom of mut view differentiated between forward and reverse strands, similar to how Auspice does it:

![image](https://user-images.githubusercontent.com/25161793/171253245-7835f0d3-3634-4139-a6b8-8ab6b0ae4161.png)

See here for Auspice issue: https://github.com/nextstrain/auspice/issues/1515#issuecomment-1142373392

Right now the Nextclade genemap is so dense it's hard to make sense of it. Splitting in forward reverse rows would make it more comprehensible.

This is the current status:
<img width="1573" alt="image" src="https://user-images.githubusercontent.com/25161793/171253399-f9256804-e277-4773-be6c-fc2dee1fa92e.png">

**Comment by ivan-aksamentov** [comment]
@corneliusroemer Currently gene map view uses vertical offset to denote reading frame (see SARS-CoV-2 for example). I see how showing the strand is also important. How would we combine the two features?

**Comment by ivan-aksamentov** [comment]
This is implemented as a part of https://github.com/nextstrain/nextclade/pull/815
