### ISSUE TITLE
ENH: When switching dataset, a dropped file should not be deleted

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#832]
It happens sometimes that I drop a file in Nextclade web, just to realize the dataset is still set to the wrong version.

When I then switch, the dropped file is gone. This is unnecessary and can be frustrating to the user.

We should keep the file dropped even if we switch dataset.

**Comment by ivan-aksamentov** [comment]
I clear all the inputs, including the advanced ones, to make sure they correspond to the dataset.

In v1 there was a validation step, that checks that some of the inputs which depend on each other are compatible when you drop them into the box. This was removed in v2, but I planned to bring it back later.

Would you expect that the advanced inputs are kept when switching?

**Comment by corneliusroemer** [comment]
I think advanced inputs should be deleted since they are dataset specific

Also advanced inputs are used maybe 100x less frequently so it's ok to clear, no usability problem there.
