### ISSUE TITLE
ENH: Avian flu datasets, e.g. H5

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#870]
I've received a request for Avian flu datasets e.g. H5, via Twitter DM.

If you'd like this feature, feel free to leave a thumbs up here to signal support.

**Comment by ivan-aksamentov** [comment]
I wanted to add that if you are reading this and is an expert in Avian flu, consider contributing some of your expertise. Check out:
 - data repo: that's where the raw dataset files are stored, processed and deployed to the internet: https://github.com/nextstrain/nextclade_data
 - tree preparation repo: that's where reference trees (the `tree.json` part of the dataset) are prepared (including Augur config): https://github.com/neherlab/nextclade_data_workflows
 - dataset docs: https://docs.nextstrain.org/projects/nextclade/en/stable/user/datasets.html

**Comment by ABMicroBioinformatics** [comment]
This would be very much a welcomed addition. Also schemes for swineH1, H7, and H9 if something has been settled.

**Comment by mcroxen** [comment]
Agree this would be great. Also swineH1, H7 and H9 schemes if there are acceptable ones would be fantastic.

**Comment by ammaraziz** [comment]
I also agree that this would be extremely helpful to avian influenza research and surveillance. 

@corneliusroemer please let me know what I can do to assist. I can start collating data for H5 for the initial tree.

**Comment by Wen1953** [comment]
Great idea. It will be very useful for avian influenza research :)

**Comment by ivan-aksamentov** [comment]
We now have H5 community datasets by @lmoncla and @jordan-ort. Currently there's 3:

```
community/moncla-lab/iav-h5/ha/all-clades
community/moncla-lab/iav-h5/ha/2.3.2.1
community/moncla-lab/iav-h5/ha/2.3.4.4
```

 - Nextclade Web (all-clades): https://clades.nextstrain.org/?dataset-name=community/moncla-lab/iav-h5/ha/all-clades

 - Nextclade CLI: run with `--dataset-name=` and one of the names from above

 - Nextclade data repo: https://github.com/nextstrain/nextclade_data/tree/master/data/community/moncla-lab/iav-h5/ha

 - Sources: https://github.com/moncla-lab/h5nx-Clades
 

Please comment or create a new issue if there's still outstanding questions.

**Comment by AMPByrne** [comment]
Hi, the H5 Nextclade datasets have been really useful, thanks for making these available. There's been a recent publication detailing an updated classification for H9 avian influenza viruses (https://pubmed.ncbi.nlm.nih.gov/39043566/). Is anyone interested in developing a Nextclade build for this? I'd be happy to be involved.

**Comment by lmoncla** [comment]
Hey @AMPByrne! I'm so glad to hear that you are finding the H5 datasets useful. We are definitely planning to expand the same approach out for the H7s and H9s, though we would be happy to have help/collaboration on this. But yes, this is definitely in the plans!

**Comment by AMPByrne** [comment]
Hi @lmoncla thanks for getting back to me. I made a start with the H9 build just for my own learning and to get a hang of what is needed for the dataset itself. I'm just doing some testing on that but it would be great to collaborate on this if possible.
