### ISSUE TITLE
Got an error when submitting FASTA file for SARS-CoV-2 analysis

### ISSUE THREAD

**Issue by ladypiper58** [nextstrain/nextclade#871]
Dragged and dropped FASTA file onto Provide sequence data for SARS-CoV-2.  It accepted the file, but when I hit RUN, got an error page.  Repeated the process with a FASTA file from last week that worked just fine at that time and got the same error
<img width="798" alt="Nextclade error" src="https://user-images.githubusercontent.com/95105333/174388194-e01ee774-1a74-484a-8fcf-0e6cba7b0308.png">
.

**Comment by ivan-aksamentov** [comment]
Hi @ladypiper58,

Thanks for your report!

The error message is not particularly informative unfortunately. Can you please share your file so that we could reproduce it locally?

What operating system, browser and browser version you are using?

**Comment by ladypiper58** [comment]
MacOS Catalina, V 10.15.7
Google Chrome V 102.0.5005.115 (Official Build) (x86_64)

Nothing has changed with my computer or browser since Monday.

I attached the FASTA that worked fine last Monday.  In fact, these sequences have already been submitted to GISAID.

N


Nancy A. Wilson, Ph.D.
Sr Scientist
AIDS Vaccine Research Laboratory
University of Wisconsin-Madison
555 Science Drive
Madison, WI 53711
***@***.******@***.***>


From: Ivan Aksamentov ***@***.***>
Date: Friday, June 17, 2022 at 2:29 PM
To: nextstrain/nextclade ***@***.***>
Cc: Nancy Wilson ***@***.***>, Mention ***@***.***>
Subject: Re: [nextstrain/nextclade] Got an error when submitting FASTA file for SARS-CoV-2 analysis (Issue #871)

Hi @ladypiper58<https://github.com/ladypiper58>,

Thanks for your report!

The error message is not particularly informative unfortunately. Can you please share your file so that we could reproduce it locally?

What operating system, browser and browser version you are using?

**Comment by ivan-aksamentov** [comment]
Thanks Nancy,

Unfortunately, GitHub does not show the attachments, if you reply to an email directly. It has been a bit of a confusing feature.

Could you please return to your GitHub thread and post there instead:
https://github.com/nextstrain/nextclade/issues/871

**Comment by ladypiper58** [comment]
I rebooted my computer and it seems to be working fine now.  Sorry, should have rebooted first.


Nancy A. Wilson, Ph.D.
Sr Scientist
AIDS Vaccine Research Laboratory
University of Wisconsin-Madison
555 Science Drive
Madison, WI 53711
***@***.******@***.***>


From: Ivan Aksamentov ***@***.***>
Date: Friday, June 17, 2022 at 2:47 PM
To: nextstrain/nextclade ***@***.***>
Cc: Nancy Wilson ***@***.***>, Mention ***@***.***>
Subject: Re: [nextstrain/nextclade] Got an error when submitting FASTA file for SARS-CoV-2 analysis (Issue #871)

Thanks Nancy,

Unfortunately, GitHub does not show the attachments, if you reply to an email directly. It has been a bit of a confusing feature.

Could you please return to your GitHub thread and post there instead:
#871<https://github.com/nextstrain/nextclade/issues/871>

**Comment by ivan-aksamentov** [comment]
Oh! That's unexpected.
I will close this issue then, but if the problem returns, please feel free to open again, with as many details as possible in order for the dev team to reproduce and fix it.

**Comment by ladypiper58** [comment]
I like the new feature that allows input of more than one FASTA at once.  Very efficient.  Thanks for all your hard work!


Nancy A. Wilson, Ph.D.
Sr Scientist
AIDS Vaccine Research Laboratory
University of Wisconsin-Madison
555 Science Drive
Madison, WI 53711
***@***.******@***.***>


From: Ivan Aksamentov ***@***.***>
Date: Friday, June 17, 2022 at 2:54 PM
To: nextstrain/nextclade ***@***.***>
Cc: Nancy Wilson ***@***.***>, Mention ***@***.***>
Subject: Re: [nextstrain/nextclade] Got an error when submitting FASTA file for SARS-CoV-2 analysis (Issue #871)

Oh! That's unexpected.
I will close this issue then, but if the problem returns, please feel free to open again, with as many details as possible in order for the dev team to reproduce and fix it.
