### ISSUE TITLE
ENH: Make unsupported browser warning "louder", block "run" button

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#896]
I think we should make the notice much "louder" though - not orange but red, make it bold, maybe not just at the top but as an overlay that needs to be clicked away?

Also, we should probably not even allow the user to proceed with "run", blocking the button.

Right now, one really needs to read that orange text at the top, that's the only warning. Otherwise it errors as before.

<img width="1669" alt="image" src="https://user-images.githubusercontent.com/25161793/175939272-f4708a51-0274-425c-a16f-dc878d64c485.png">

_Originally posted by @corneliusroemer in https://github.com/nextstrain/nextclade/issues/866#issuecomment-1167280818_

**Comment by ivan-aksamentov** [comment]
We can make it louder, but I would not break the "Run" button. Browser detection is somewhat unreliable and there might be false positives, especially if new browsers, and different privacy extensions are involved. Also, Apple may eventually fix the problem. There is no point of not allowing users to try.
