### ISSUE TITLE
ENH: Allow custom "display_name" of custom node attributes in auspice.json

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#898]
Right now, custom node attribute `lineage` is the only coloring that is lower cased - it would be nice if we could customize how this is shown in auspice.json, `Nextclade Pango Lineage` would be better than `lineage`

This can possibly be done quite easily by configuring auspice_config.json or the auspice tree output by Nextclade.

<img width="2090" alt="image" src="https://user-images.githubusercontent.com/25161793/175940785-123bb295-d7fb-4b59-a60e-5a634b9f5f55.png">

**Comment by corneliusroemer** [comment]
I think we've completed this too, haven't we @ivan-aksamentov ?

**Comment by ivan-aksamentov** [comment]
yes
