### ISSUE TITLE
BUG: Retry reverse complement flag should not expect arg

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#901]
I see the following in CLI help:
```
--retry-reverse-complement <RETRY_REVERSE_COMPLEMENT>
            Retry seed matching step with a reverse complement if the first attempt failed
```

The `<RETRY_REVERSE_COMPLEMENT>` should not be there I think as this is a binary flag - or is this supposed to be true/false? In that case, we should mention that in the help.

EDIT: I tested and indeed, one can add true/false (optionally), and if false, it does not reverse complement.

**Comment by corneliusroemer** [comment]
I guess there should be brackets around something like `[true/false]` to indicate possible options?

**Comment by ivan-aksamentov** [comment]
>  I think as this is a binary flag - or is this supposed to be true/false

Yes, as you've checked it can have value. But I would not be focusing on that possibility, as all boolean flags already work without values.

There is some unfortunate architectural shenanigans I had to commit to to make alignment params work okay-ish.

In particular, I am using `optfield` crate to create a copy of the struct, where all the fileds are same as in original, but `Option<>`.
https://github.com/nextstrain/nextclade/blob/348e65cff85db7d1412a5426189a78c0ddc33b1a/packages_rs/nextclade/src/align/params.rs#L17

This is needed to make sure that all flags are optional as well as what comes from virus properties. However, clap's handles `bool` and `Option<bool>` differently, therefore the observed behavior.

One solution is to have the optional struct defined manually, and then copy the fields over from CLI and virus properties, however this is additional, highly non-DRY code, and I am 99% certain I forget to copy whenever a new filed is added.

If someone knows how to fix that - contributions are welcome.

Right now I don't think anyone will notice that the flag accepts values. But for now, can we just say ignore it? :)

**Comment by corneliusroemer** [comment]
What about adding some extra comments in the help? Like that it optionally accepts false/true? Then it's clear for the user what happens - not perfect but better than having something there with unclear/unexplained function.

**Comment by ivan-aksamentov** [comment]
> Like that it optionally accepts false/true?

I don't see much value on focusing user's attention on that little quirk. You'd need to also add it to all other booleans in this struct. But not outside the struct. And not forget to add it for new booleans. Otherwise it will be asymmetric.

Me personally, I never read these values, they are just noise to me. But feel free to submit a PR if you feel extra explanations are needed.
