### ISSUE TITLE
DATA_FULL_DOMAIN without prefix http://

### ISSUE THREAD

**Issue by xzhub** [nextstrain/nextclade#923]
Can I use a relative path in DATA_FULL_DOMAIN?
for example, I'd like to set it to "/nextcladedata" in .env, so that my http proxy can recognize it then redirect the network request to the right server. 

I tried to set 
```
DATA_FULL_DOMAIN=/nextcladedata
```

however, after nextclade is up and I load the example data then click run, I see this error:

```
An error has occurred: Network connection failed
We tried to download the file from
[/nextcladedata/datasets/sars-cov-2/references/MN908947/versions/2022-06-27T12:00:00Z/files/sequences.fasta](http://192.168.18.19:10086/nextcladedata/datasets/sars-cov-2/references/MN908947/versions/2022-06-27T12:00:00Z/files/sequences.fasta)
but were unable to establish a connection.
Please verify that:
you are connected to the internet
the address to the file is correct
the address to the file is reachable from your browser
the are no browser extensions interfering with network requests1
the server allows Cross-Origin Resource Sharing (CORS)2
there are no problems in domain name resolution of your server3
1Some of the adblocking browser extensions (AdBlock, uBlock, Privacy Badger and others) and privacy-oriented browsers (such as Brave) are known to prevent Nextclade from making network requests to other servers. Nextclade respects your privacy, does not serve ads or collects personal data. All computation is done inside your browser. You can safely disable adblockers on https://localhost and/or allow https://localhost to make network requests to your data source server.
2[en.wikipedia.org/wiki/Cross-origin_resource_sharing](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing)
3[en.wikipedia.org/wiki/Name_server](https://en.wikipedia.org/wiki/Name_server)
Error: Unsupported protocol /nextcladedata/datasets/sars-cov-2/references/MN908947/versions/2022-06-27T12:
    at _next/static/chunks/pages/_app-e23e629203b16b59.js:3:933191
    at u (_next/static/chunks/main-9c3c3e678ac23665.js:1:1333)
    at Generator._invoke (_next/static/chunks/main-9c3c3e678ac23665.js:1:2623)
    at a.<computed> [as throw] (_next/static/chunks/main-9c3c3e678ac23665.js:1:1736)
    at l (_next/static/chunks/pages/_app-e23e629203b16b59.js:3:929773)
    at h (_next/static/chunks/pages/_app-e23e629203b16b59.js:3:930006)
If you think it is a bug, report it at https://github.com/nextstrain/nextclade/issues so that developers could investigate this problem. Please provide as much details as possible about your input data, operating system, browser version and computer configuration. Include other details you deem useful for diagnostics. Share the example sequence data that allows to reproduce the problem, if possible.
```

If I click on the link `/nextcladedata/datasets/sars-cov-2/references/MN908947/versions/2022-06-27T12:00:00Z/files/sequences.fasta](http://192.168.18.19:10086/nextcladedata/datasets/sars-cov-2/references/MN908947/versions/2022-06-27T12:00:00Z/files/sequences.fasta` I can download the sequence without any issue.

**Comment by xzhub** [comment]
index_v2.json should have been processed correctly otherwise we should see warnings before this step. right?

**Comment by ivan-aksamentov** [comment]
I cannot tell for sure what's happening here. There might be more information in browser's dev console, especially if the app is built in dev mode.

It seems that in your case, the dataset index is downloaded correctly, and the URL is taken from it. However, after index download Nextclade converts the relative URLs to absolute URLs, by prefixing it with `DATA_FULL_DOMAIN`:
https://github.com/nextstrain/nextclade/blob/ca1c74dffa2b4e71e2e65faa49983fa0f5457f68/packages_rs/nextclade-web/src/io/fetchDatasetsIndex.ts#L31-L34

Perhaps in your case you need some more complex logic there.

The default fasta is then downloaded here:
https://github.com/nextstrain/nextclade/blob/ca1c74dffa2b4e71e2e65faa49983fa0f5457f68/packages_rs/nextclade-web/src/io/AlgorithmInput.ts#L105

And it seems `axios` cannot understand the relative URL. Maybe is can be taught to handle relative URLs?

I don't see why `axios` can download the index, but not other files.

If you find a solution, feel free to propose a PR.

**Comment by xzhub** [comment]
Using the public folder to serve the file directly from nextclade server does not fix the issue. The relative url is still not working.

Not sure if this could be the fix: https://stackoverflow.com/questions/52947579/relative-url-not-working-with-axios-in-node

We can check if DATA_FULL_DOMAIN is not start with `http`, then the real URL should be prefixed with a real domain, and it could be retrieved from the request header (i.e. req.headers.origin)

**Comment by ivan-aksamentov** [comment]
> Using the public folder to serve the file directly from nextclade server does not fix the issue. The relative url is still not working.

I did not say it will fix it. I said you can use public directory as a way to host files from the same domain during development, for convenience.

Also, we don't consider this an issue that needs a fix, because this is not needed for our application.  


> We can check if DATA_FULL_DOMAIN is not start with http

If you will be working on an improvement, please prefer to high-quality URL processing libraries instead of creating a handcrafted solution.


Our team will not have resources to support third-party Nextclade installations. But if you want to include an improvement into the codebase, feel free to make a PR.

**Comment by xzhub** [comment]
With 0 knowledge of TS, I searched the resolution for adding http origin. The modification works in my local environment, with  DATA_FULL_DOMAIN set to '/' (I am using the yarn static file server). 

https://github.com/nextstrain/nextclade/pull/930
