### ISSUE TITLE
UI not working correctly with more than 12 MPXV sequences

### ISSUE THREAD

**Issue by dbtara** [nextstrain/nextclade#940]
I uploaded a file with 21 MPXV sequences and the UI updated correctly for 0-12 and then started from top and filled in 0-7 with rest of the 8 sequences and it looks like this now. it now thinks there are only 13 sequences and all of the datasets downloaded refer to only 13 sequences. This only started happening with the latest version 2.3.0. I have tested using Chrome/Edge/Firefox and with cleaned cache with each. 
Not sure if this is limited to MPXV or others as well.
![image](https://user-images.githubusercontent.com/17458998/179314366-979fa975-a112-4ca3-9563-d2dbb03667eb.png)

**Comment by ivan-aksamentov** [comment]
@dbtara

I cannot reproduce this.

 - Does this happen every time, or is this a one-off?
 - Are you able to share the sequences, so that I could try to run and debug on my machine?
 - How do you initiate the run exactly? (one or multiple files? autorun enabled or not? clean run or after previous run?)
 - There is 3 monkeypox datasets in the "Select pathogen" list, could you please confirm which one you are using?

**Comment by dbtara** [comment]
* Every time I tried today.
* I can share but only privately for now, I can try to replicate it with
public data.
* Two files first and then combined in one, the split did not match the
number of files.
* hMPXV  dataset

**Comment by ivan-aksamentov** [comment]
@dbtara Could you please additionally check if your FASTA file contains sequences with duplicate names? i.e. that sequence names are not unique.

**Comment by dbtara** [comment]
Ok I feel a little embarrassed, I thought I checked that there were no name duplication but now I believe the problem was due to duplicate fasta headers.

**Comment by ivan-aksamentov** [comment]
@dbtara No worries! We actually planned to move Nextclade from using sequence names to the indices (order) of sequence in the fasta file. Headers in fasta cannot uniquely identify sequences, so this is considered a known defect in the software. I hope we can fix it soon.
