### ISSUE TITLE
ENH: Use brotli compression for datasets and wasm files

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#951]
Brotli compresses datasets and wasm much better than gzip, it would be nice if we could take advantage of that.

Using max compression comparison on SC2 tree and sample sequences, we can see that brotli is 4-6 times better:
<img width="667" alt="image" src="https://user-images.githubusercontent.com/25161793/182363437-2d0394ba-f25d-4735-bb8c-f31c4dc5a41d.png">

Wasm seems to be uncompressed at the moment? I download 2MB for each chunk - with gzip we reduce by a factor of 3 (from 2MB to 600kB), with brotli by another 30% (400kB):
<img width="580" alt="image" src="https://user-images.githubusercontent.com/25161793/182365043-9127cb84-742f-4eac-81ad-8678ade52c86.png">

**Comment by corneliusroemer** [comment]
I think you've completed this haven't you @ivan-aksamentov 🎉

**Comment by ivan-aksamentov** [comment]
Yes
