### ISSUE TITLE
BUG: `The target 'col-clade_13_OP205131' could not be identified in the dom, tip: check spelling`

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#957]
I just got this bug and I have no idea what it means! Check spelling of what?

This is the link I used: https://master.clades.nextstrain.org/?dataset-name=MPXV&input-fasta=https%3A%2F%2Fmpox-lapis.genspectrum.org%2Fv1%2Fsample%2Ffasta%3ForderBy%3Drandom%26limit%3D200%26country%3DUnited%2BKingdom%26yearFrom%3D2022%26downloadAsFile%3Dtrue

I'm running this on Chrome on an M1 Pro mac (Version 104.0.5112.79 (Official Build) (arm64))

**Comment by ivan-aksamentov** [comment]
What are the steps for reproducing?

**Comment by corneliusroemer** [comment]
I just clicked on the link - that was it.

I'll try again tomorrow.

**Comment by corneliusroemer** [comment]
Hmm - can't reproduce anymore
