### ISSUE TITLE
BUG: Cannot read properties of undefined (reading 'toLowerCase') when typing in filtering field

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#961]
I got this error when typing `S:346T,S` in the amino acid mutation search field

<img width="1299" alt="image" src="https://user-images.githubusercontent.com/25161793/185503073-4f728e4b-66f4-4926-9ef2-b3bafa7cfa32.png">

```
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at r (https://clades.nextstrain.org/_next/static/chunks/pages/_app-b60b2942a9bfab30.js:3:992801)
    at aH (https://clades.nextstrain.org/_next/static/chunks/pages/_app-b60b2942a9bfab30.js:1:462512)
    at fp (https://clades.nextstrain.org/_next/static/chunks/pages/_app-b60b2942a9bfab30.js:1:474560)
    at https://clades.nextstrain.org/_next/static/chunks/pages/_app-b60b2942a9bfab30.js:1:505350
    at aA (https://clades.nextstrain.org/_next/static/chunks/pages/_app-b60b2942a9bfab30.js:1:461808)
    at https://clades.nextstrain.org/_next/static/chunks/pages/_app-b60b2942a9bfab30.js:1:491851
    at https://clades.nextstrain.org/_next/static/chunks/pages/_app-b60b2942a9bfab30.js:3:996344
    at Array.filter (<anonymous>)
    at get (https://clades.nextstrain.org/_next/static/chunks/pages/_app-b60b2942a9bfab30.js:3:995772)
    at z (https://clades.nextstrain.org/_next/static/chunks/pages/_app-b60b2942a9bfab30.js:3:52659)
```

M1 Pro Mac running macOS 12.5 on Brave browser

**Comment by ivan-aksamentov** [comment]
@corneliusroemer Can't reproduce. Are you using a particular data for this? Please provide data and steps.

**Comment by corneliusroemer** [comment]
If I knew how to reproduce I would have mentioned 😬 

I don't know exactly what I typed but this happened during very innocent usage so I thought I raise it as it may occur to others, too.

**Comment by ivan-aksamentov** [comment]
https://github.com/nextstrain/nextclade/pull/962 **might** fix it, but impossible to say without repro

**Comment by ryhisner** [comment]
When trying to upload a collection of sequences, I'm getting a similar error. I tried downloading the sequences again, but got the same error. I tried a slightly different set of sequences (leaving a few sequences off) but got the same result. Now it seems that I can't even try to upload anything. When I try to go to https://clades.nextstrain.org/, I just see the same error message. When I click the red "Restart Nextclade" button at the bottom of the screen, nothing happens. 
![image](https://user-images.githubusercontent.com/33738461/187041277-34aa4a63-dd08-4075-b3f5-4e74d8f73c30.png)

**Comment by corneliusroemer** [comment]
This is a different error @ryhisner

Which Nextclade dataset did you select? Can you try again?

**Comment by ryhisner** [comment]
I can't try again because when I go to the website, all I get is that error message. I've tried clearing my cache, but it didn't help. I'll try restarting my computer.

**Comment by ivan-aksamentov** [comment]
@ryhisner There's been a problem with website's infrastructure. This should be resolved now. Please try again and let us know if it works for you.

**Comment by ryhisner** [comment]
Yes, it seems to be working again. Thanks!

**Comment by corneliusroemer** [comment]
Thanks @ryhisner for reporting, that's very helpful!
