### ISSUE TITLE
Error in BF.15 Nextclade

### ISSUE THREAD

**Issue by FedeGueli** [nextstrain/nextclade#966]
Hi @corneliusroemer just to highlight something went wrong with the last nextclade update regarding BF.15 : it is defined by S:248H and it is around 150sequences but the nextclade Bf.15* query on covspectrum  finds more than 4000 sequences and just a tiny bit with S: 248H

Nextclade for BF.15
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=BF.15*&

Real BF.15:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A248H&nextcladePangoLineage=BA.5.2.1*&

**Comment by corneliusroemer** [comment]
Thanks for reporting, I'll have a look.

You can check out the Nextclade tree here: https://nextstrain.org/nextclade/sars-cov-2

**Comment by corneliusroemer** [comment]
Branch leading to BF.15* has these mutations - is that wrong?
<img width="906" alt="image" src="https://user-images.githubusercontent.com/25161793/186648886-d654671b-08e8-4eec-8957-e9a376bfa852.png">

The reason it's getting so many non-248 is that the branch is 3 mutations long, so having 2 mutations is enough to call this as BF.15

Not much I can do right now with the Nextclade algorithm as it is. Having the parent designated would help, so have BF.15 be broadened to the non-248, and then BF.15.1 be the 248 child.

Didn't you propose something like this anyways?

This is effectively what Nextclade does:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3ABA.5.2.1*+%26+T6979G+%26+%5B2-of%3A+T22304C+%2C+C26625T+%2C+C27371T%5D&

**Comment by FedeGueli** [comment]
Thx @corneliusroemer ! Yeah i have proposed the parental lineage with Orf1a:P57L but i have closed the issue after it was designated first the child lineage >>> https://github.com/cov-lineages/pango-designation/issues/932

**Comment by corneliusroemer** [comment]
@FedeGueli let's find out ;) I'll create a new BA.2/4/5* Pango tree
