### ISSUE TITLE
Nextclade webpage not working

### ISSUE THREAD

**Issue by Arash-Iranzadeh** [nextstrain/nextclade#971]
The Nextclade webpage has not been working for a while and displayed the below error after uploading a Fasta file:
An error has occurred.
When parsing virus properties JSON: When parsing JSON: expected value at line 1 column 1Error: When parsing virus properties JSON: When parsing JSON: expected value at line 1 column 1
    at M (https://clades.nextstrain.org/_next/static/chunks/68.a2718d4f2d7346ab.js:1:15568)
    at https://clades.nextstrain.org/_next/static/wasm/a8327bbae75e8f98.wasm:wasm-function[134]:0xc095e
    at https://clades.nextstrain.org/_next/static/wasm/a8327bbae75e8f98.wasm:wasm-function[1101]:0x17b4c3
    at new a (https://clades.nextstrain.org/_next/static/chunks/68.a2718d4f2d7346ab.js:1:9462)
    at https://clades.nextstrain.org/_next/static/chunks/68.a2718d4f2d7346ab.js:1:23850
    at u (https://clades.nextstrain.org/_next/static/chunks/444.ca2625476ee8666b.js:1:24015)
    at Generator._invoke (https://clades.nextstrain.org/_next/static/chunks/444.ca2625476ee8666b.js:1:25305)
    at a.<computed> [as next] (https://clades.nextstrain.org/_next/static/chunks/444.ca2625476ee8666b.js:1:24418)
    at p (https://clades.nextstrain.org/_next/static/chunks/68.a2718d4f2d7346ab.js:1:21635)
    at d (https://clades.nextstrain.org/_next/static/chunks/68.a2718d4f2d7346ab.js:1:21832)

**Comment by corneliusroemer** [comment]
Hi Arash, thanks for reporting! @ryhisner reported something similar.

Weirdly, I haven't been able to reproduce. Do you know what steps you took prior to this error being shown?

You said you uploaded a fasta file, which dataset did you have selected? SARS-CoV-2?

In case something doesn't work at clades.nextstrain.org, you can always try master.clades.nextstrain.org - it's a preview build.

Also, you can try clearing your cache - that sometimes helps too.

**Comment by ivan-aksamentov** [comment]
@Arash-Iranzadeh There's been a problem with website's infrastructure. This should be resolved now. Please clear cache or reload the page using Ctrl+F5 and let us know if it works for you. Otherwise caches should expire automatically in about a week. Sorry for the troubles.

**Comment by corneliusroemer** [comment]
You can also use an incognito window if things don't work - or try a different browser (just not Safari)

**Comment by Arash-Iranzadeh** [comment]
Thanks for the feedback. It was about SARS-CoV-2. It seems the issue is resolved now.


______________________________________________________

Arash Iranzadeh

Ph.D. candidate

University of Cape Town | Bioinformatics | 2022

***@***.***

<https://www.linkedin.com/in/arashbioinformatics/>http://www.cbio.uct.ac.za/

________________________________
