### ISSUE TITLE
ENH(web): Allow preselection of dataset configuration without immediate running

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade#998]
It's amazing that one can pass dataset and sequences via URL parameters, this makes nice integrations possible for e.g. covSpectrum.

I often use a particular configuration of dataset that's always the same. Right now I can't preselect that by saving a URL. It'd be great if we could make the URL-param feature a bit more flexible to not require sequences to be passed.

Basically I want all input options to be set like one can through the UI - but not requiring the sequences yet, which I would then just drop.

For an example: I usually use `nextclade.dev` with the dataset `sars-cov-2-21L` and the reference tree downloaded from `https://api.codetabs.com/v1/proxy?quest=https://nextstrain.org/charon/getDataset?prefix=staging/nextclade/sars-cov-2/21L`

Right now, I always have to click to insert that tree link, but I don't see why we can't make this selection via URL when I open Nextclade, something like:
`master.clades.nextstrain.org?dataset=sars-cov-2-21L&input-tree=https://api.codetabs.com/v1/proxy?quest=https://nextstrain.org/charon/getDataset?prefix=staging/nextclade/sars-cov-2/21L` etc, of course properly URL encoded.

This would be super useful as it would allow Nextclade configuration sharing by link - making it less "clicky".

**Comment by ivan-aksamentov** [comment]
@corneliusroemer I think it should mostly work in https://github.com/nextstrain/nextclade/pull/999.

Give it a try. Note that the correct URL param for setting a dataset is `dataset-name` (there is also `dataset-reference` and `dataset-tag`).

For your example tree, the URL will be:

https://nextclade-git-feat-web-url-read-dataset-witho-0511cb-nextstrain.vercel.app/?dataset-name=flu_yam_ha&input-tree=https%3A%2F%2Fapi.codetabs.com%2Fv1%2Fproxy%3Fquest%3Dhttps%3A%2F%2Fnextstrain.org%2Fcharon%2FgetDataset%3Fprefix%3Dstaging%2Fnextclade%2Fsars-cov-2%2F21L


The app initialization is quite complicated, there are many sources of incoming data and it is not easy to test. Would be nice if you could test that the normal flows did not break with this change.
